### ISSUE TITLE
Warning: Unresponsive Script

### ISSUE THREAD

**Issue by robert-yelas-1516** [jmoenig/Snap--Build-Your-Own-Blocks#1001]
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://snap.berkeley.edu/snapsource/morphic.js:1155

Occurred while trying to load my saved game, the game had a lot of scripts and commands. 
Error came up in all browsers while attempted troubleshoot. Located in morphic.js

**Comment by jmoenig** [comment]
can you share the project and the url? tnx!

**Comment by robert-yelas-1516** [comment]
http://snap.berkeley.edu/snapsource/snap.html#present:Username=fruitgod&ProjectName=Game

**Comment by jmoenig** [comment]
Thanks for sharing! Loads fine for me on my computers.

Two week ago at a blocks implementers workshop in Atlanta, Neil Fraser of Blockly mentioned that most of the time when something really breaks in Blockly it's because someone just copied the same block over and over and over again, and he went on to claim that knowing about loops would be pretty good practice to encourage. I was among those who laughed. I was wrong:

![loop](https://cloud.githubusercontent.com/assets/2596285/11132086/4dae844e-898e-11e5-916c-df025b713e32.png)

**Comment by cycomachead** [comment]
This error is a Firefox error, and it really dependent on computer hardware, which is why i's hard to track down....

See http://stackoverflow.com/questions/1917380/how-to-avoid-the-unresponsive-script-popup-in-firefox-with-long-running-javascri

**Comment by jmoenig** [comment]
Right, but he says that it happens "in all browsers".

For me, opening the project works fine on my MacBook Pro in Chrome, Opera and Firefox, but Safari literally crashes without protesting about an unresponsive script. On the s-l-o-w Windows 10 compute stick Brian sent me the project opens fine and very quickly in Chrome and Opera, somewhat slower but alright in Edge and IE11, but Firefox first complaines about the "unresponsive script" and then just crashes.
