### ISSUE TITLE
Load failed: Error: Missing required element: <list>!

### ISSUE THREAD

**Issue by canhcutvl** [jmoenig/Snap--Build-Your-Own-Blocks#1004]
I cannot open one of my students' work: http://snap.berkeley.edu/snapsource/snap.html#present:Username=brittanyhurst12&ProjectName=bricks. I could a couple of weeks back. What else can be done here?

**Comment by jmoenig** [comment]
Ugh. This project appears to have been doctored. I can see what the problem is. Is it possible the student played a prank on you or that the browser was hopelessly outdated at the time this project was created (IE9)?

There are four very little scripts in this single-sprite / no media project / no custom blocks project. The XML project structure is missing the last level in some places. This can't be a transmission problem and also not a backend database issue. The only way to reproduce this is to either modify Snap or use a very old browser.

**Comment by canhcutvl** [comment]
The student created it at school so I believe it's Mac but her home machine is old. She herself could not open it as well. Is it possible to export this to another place so one of us can open it?

**Comment by brianharvey** [comment]
No, sorry, too much is missing.
