### ISSUE TITLE
Impossible to drop a variable into a ring that's an input

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1006]
For example, take `map`

If you drag a varialbe over the %ring it replaces the ring, but sometimes you want to drop a variable into a ring such as in #640

**Comment by brianharvey** [comment]
This is a feature.  Back in BYOB3 we tried to have nice simple uniform rules, and the result was that people found it unusable.  This time around, we recognized that 99% of the time, when people drop a variable onto a ring, the variable is a formal parameter of a custom block that implements a control structure, like the RUN ACTION in the definition of FOR.  (I think this doesn't feel like a kludge to users partly because users don't think of variable blobs as reporters in the first place.)

For the other 1%, they have to learn about the RINGIFY and UNRINGIFY options in reporters' context menus.  The right way to do it is to ringify the variable after it's in place.

As for the λx.x case, somewhat to my surprise this now seems to work straightforwardly -- just drag the #1 into the ring.

**Comment by cycomachead** [comment]
> As for the λx.x case, somewhat to my surprise this now seems to work straightforwardly -- just drag the #1 into the ring.

That only works if the ring isn't an input to a block, which is likely where I'd likely want to use it. 
Still, if it's a feature that's a fine line to draw.

**Comment by brianharvey** [comment]
Oh.  *That's* a misfeature -- rings should have a consistent behavior.  We'll put this on the list for the Jens-Brian summit meeting next week.

**Comment by jmoenig** [comment]
Wait, would you please explain the misfeature?

**Comment by cycomachead** [comment]
Drag out a map block, then make #1 be a parameter in the ring. Then try to drag the #1 reporter and place it in the ring. 

-- 
Michael Ball
From my iPhone
michaelballphoto.com

**Comment by jmoenig** [comment]
Okay. The ring disappears because the #1 parameter is just a variable block. So, then you choose "ringify" from the #1 blob's context menu and expand the ring by one. Works, right? Alternatively you drag the ring off the MAP block into the scripting area, and *there* you can just place other rings or variable blobs inside.

My point is: That's the *design*. I don't understand the *misfeature*. Brian?

**Comment by brianharvey** [comment]
Oh, what I meant is that it's weird that loose rings behave differently from rings in input slots.  That makes the behavior harder to explain.

I'm not proposing any particular alternative.  I just want to raise the question for discussion.

I also have always wanted the behavior when dropping a ring into a ring to be changed so that formal parameters don't get lost -- the usual case I'm thinking about is dragging a ring with parameters into the unadorned ring in an input slot.  The one with parameters should be the winner, I think.

**Comment by jmoenig** [comment]
Oh, now I'm puzzled. As far as I remember we specifically wanted ring-slots to have this special behavior, and rings in the scripting pane to have the "normal" nesting features, so we can easily do Church numerals and lambda calculus...

Hey, this'll make food for great discussions next week, looking forward to it!

**Comment by bb010g** [comment]
Also, there's the confusion from having a free floating `#1` that you can then reringify. Are ringed variables just lexically scoped with whatever variable shares their name?

**Comment by jmoenig** [comment]
yes, all variables are lexically scoped in Snap! Formal parameters are just variables.

**Comment by cycomachead** [comment]
> Oh, now I'm puzzled. As far as I remember we specifically wanted ring-slots to have this special behavior, and rings in the scripting pane to have the "normal" nesting features, so we can easily do Church numerals and lambda calculus...

The reason: that dropping a variable be in is already something that is ringified and doesn't need to be re-ringifed, right? I think this still make sense, I guess it depends on the common error case -- I actually think Snap<em>!</em>'s current behavior makes sense, but I think it should be _possible_, though (more) _difficult_ to drop a variable or ring inside a ring that is in an input slot.

**Comment by brianharvey** [comment]
Okay, I think I've decided this behavior is correct.

**Comment by cycomachead** [comment]
I still maintain, that it should _possible_ to do this. Though I think the default is correct to replace. I guess my view would be that if I drag the variable closer to the input there's a smaller highlight that appears.

**Comment by brianharvey** [comment]
It's possible; just drag it in, then ringify from the context menu.

We had distance-sensitive drop semantics in BYOB3 and everybody hated it.
