### ISSUE TITLE
Location of Sprite Unclear - make sprite translucent?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1013]
The good thing about the head being the “location” of the sprite (and therefore the origin of its drawing) is that it’s an easy to identify feature. But it’s very common to expect the trace to be left behind the turtle sprite rather than at its head and, moreover, small moves (e.g., 20) with the pen down appear not to be drawing because the sprite covers the trace. Can the turtle sprite (probably only that sprite shape) be translucent except for a small “dot” at the head, so that the trace is always visible?

**Comment by brianharvey** [comment]
That's a good idea!  But the dot at the head should be there only when the pen is down.

**Comment by jmoenig** [comment]
No, it's not a good idea, because then people want options to hide and show the dot and select a shape for it etc. You can open the costume editor and show the rotation point. You can also discover the exact location by using watchers both for a sprite and for the mouse coordinates. AND you CAN make the sprite translucent in Snap itself and then use the pen to show the rotation point.

No way I am ever going to turn Snap into MS Office.

**Comment by brianharvey** [comment]
Okay, so, putting the rotation point in the middle (which really should be the back but never mind) makes pictures look kind of like what you want.  As for translucency, we have ghost effect, which sort of does what you want too.   So I grudgingly agree that Jens's rant is right this time and we don't need another feature.  :-)

**Comment by cycomachead** [comment]
> Okay, so, putting the rotation point in the middle (which really should be the back but never mind) makes pictures look kind of like what you want.

We could change the default location of the rotation center of the turtle? It _is_ currently a context-menu option, but users have little way of discovering it...
