### ISSUE TITLE
Touching? Sensitivity

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1022]
This script behaves as one would expect 
![image](https://cloud.githubusercontent.com/assets/6549787/11277383/4f68d3b8-8eb4-11e5-90e5-b09f87d0081a.png)
 except for the timing, which causes the boundary to be dependent on mouse speed. One would want the following script to behave well, too, but it does not. 
![image](https://cloud.githubusercontent.com/assets/6549787/11277398/5f92a2aa-8eb4-11e5-8cc0-351aa15ca106.png)
 In this case, “touching” is more sensitive to the tail of the turtle-sprite than to the head and it’s not even possible to make it touch the edge toward which the sprite is turned.

**Comment by jmoenig** [comment]
Collision detection is always pixel-precise in Snap. The Problem in the above script is that the GOTO block moves the sprite's *rotation center* to the mouse pointer. You can set a costume's rotation center in the paint editor:

![costume editor](https://cloud.githubusercontent.com/assets/2596285/11286678/a0f18600-8f16-11e5-85f3-ef6ea549e1a3.png)

If it is more in the center of the costume, it will easier collide with the edge if the mouse leaves the stage. However, sometimes it makes sense to move the rotation center somewhere else, perhaps even *outside* of the costume:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=funny%20face&editMode

Then the sprite even *avoids* colliding with the mouse.

The default Logo-Turtle arrow head costume has the rotation point at its tip. I decided to put it there because I regard the "Turtle" to be a pen, and a pen draws at the tip, which also makes it easier and very clear to see what's going on. However, old LOGO people have been complaining about this, they want the rotation point / drawing tip to be in the *middle* of the Arrow-shaped Turtle. You can select this in the default costume's context menu:

<img width="222" alt="rotation point" src="https://cloud.githubusercontent.com/assets/2596285/11286801/6c457118-8f17-11e5-9f76-a0790d0c7cc9.png">

Now the sprite will center around the mouse pointer, which and this it will also have a buffer of colored pixels surrounding it that will collide with the edge before the mouse does.

This isn't an issue of sensitivity, but of choosing the sprite's rotation point.

**Comment by brianharvey** [comment]
Nitpick:  In Logo, the pen is at the *back* of the turtle, not the center.  That way, the drawn line is always behind the turtle, and also, turning the turtle puts its body *into* the picture it's drawing, rather than away from the picture.

**Comment by jmoenig** [comment]
Nitpick: The Turtle's *back* is in the middle of its *bounding box*.
