### ISSUE TITLE
Snap Cloud Problem Again?!? :(

### ISSUE THREAD

**Issue by Evanforest62** [jmoenig/Snap--Build-Your-Own-Blocks#1041]
So recently, I made a post on here that my project for Snap won't load. I did get it to work again shortly after, but it was barely loading. Like sometimes it would work using the link but other times it don't. As of today, I tried to open my project again and now it just won't load at all. I tried over and over again but it won't open, not even once. This project is gonna be due for school soon and I don't have enough time to redo it again. I really don't want to fail! Anyway to fix this problem before then? Here's the link below:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=Evanforest62&ProjectName=The%20Heroic%20Starship%20-%20Final%20Project

**Comment by Evanforest62** [comment]
Btw, this problem happens at home and at school. Even the teacher and some of the students in my class is experiencing this problem.

**Comment by brianharvey** [comment]
If the teacher is having the same problem, you won't fail because of it.  :-)  We know this is happening to a lot of people and we're working on it.

**Comment by jmoenig** [comment]
I can also not load the project, I'm also getting a "could not connect to the cloud" error. This is clearly not your fault, looking into this....

**Comment by jmoenig** [comment]
Try retrieving your project now! It now works for me. You might have to clear you browser cache and also make sure to clear you cookies once. Then it should work.

BUT, we need to have a serious conversation.

This project is nearly 50 MB big, with only little code. Of those 50 MB roughly 46 MB is music, 25 minutes of original, high-sampling, stereo Star Wars sound track in 4 tracks. This project has - over the course of the last week as you and others were repeatedly trying to download it - been blocking one of ten web servers on and off and thus single-handedly caused much of the cloud hiccup we've experienced in the last days. When we were developing the cloud backend we did not expect people to store that much massive HD media in school projects. It's clear that these kinds of projects not only are a massive burden on the backend but also in many other respects, for example for the bandwidth of school networks (imagine a class of up to 30 students saving and downloading such projects at roughly the same time, no wonder things are timing out!), since we cannot even stream that data (because it needs to be completely downloaded before we can open it in Snap).

So, we've manage to tweak both the backend and the frontend somewhat today so that downloading such giant projects is possible, but ultimately this is breaking many things. We should have a talk with teachers about what's going on their class. There are also legal issues about sharing such media, and I'd like to know more about how and why teachers encourage, oversee or deal with this.

So, please, take out some of that music, and then save your project again.

Oh, and do let me know whether that now works for you!
Tnx

**Comment by Evanforest62** [comment]
Thank you so much! My project works again and I got rid of most of the music. After that, it loads pretty fast and the cloud problem is gone now. :)

**Comment by jmoenig** [comment]
Haha, you just scared me - I got a notification email with this subject and my pulse accelerated, then I found out you'd only closed it :-)

**Comment by cycomachead** [comment]
Hah, yep! I'm going to try and clean up a lot of the older issues in the next couple weeks. :-)
