### ISSUE TITLE
Support Renaming for Upvars, Formal Params, Script Vars

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#1049]
We want our kids to refactor their code as they mature, and one of the advantages Snap! has over text languages is that if you rename a block, it propagates to every instance of usage. Because it's easy and instantaneous, kids are almost encouraged to do it. That's great.

However, the same cannot be said of formal parameters, upvars and script variables.  I had a script variable 'n' used 10 times or so, and wanted to change its name to something better, which was "recursion level". It took me 10 minutes to drag the new name to all the expressions that used to have "n" in it, and I actually missed a few. There's no equivalent of emacs "search and replace", so we need the system to help us here.  In the case that there's already a variable of the same name already, it could just warn you to go ahead or cancel with the rename.  It's also important to remember to change the name in the "set/change _name_ to _value" blocks.

That we don't support this makes users not want to refactor these names, because the effort is so high.

**Comment by cycomachead** [comment]
For reference:
#46 

I agree this is needed. :)

**Comment by jmoenig** [comment]
So, this is essentially a tool request. I agree that more tools would be nice, e.g. show all references to a block or a variable, all implementors and callers of a function, message, event etc.

**Comment by cycomachead** [comment]
No, I don't think it's a tool, I think the idea is that it would be _automatic_ that you don't even need a tool.

Like renaming a script var from "a" → "name" would just find all "a" in that scope and replace them with "name", just like renaming a block does.

**Comment by jmoenig** [comment]
Yeah, see, that part I don't like at all, because it somehow conveys the misconception, that the block somehow *is* identical with the variable, whereas I personally use variables out of their scope all the time, often even creating variable references even *before* declaring the variable. The problem with doing more and more things automatically is that we're taking such possibilities away. That's why I claim it should be tools, if at all. Then users can choose for themselves if they actually want to rename all references to a variable or just this particular reference or definition. Same with delete etc. See, automatisms are all nice and well, except often enough it's not what users really want. So, by introducing ten-dollar words and - questionable and even downright ideologically burdened, I believe - concepts like "refactoring" (how does that even work without built-in unit testing?) we also need to impose all kinds of "best practices". And *that's* something that I personally abhor for students.

That said, tools would be nice... :-)

**Comment by brianharvey** [comment]
I have no strong position on this issue.  I think "the right thing" depends on the user's intention.  Sometimes it's that the user has thought of a better name for a variable, or wants to avoid shadowing a same-name variable from an outer scope.  But sometimes it's that the user has realized that this variable should be replaced with something with different semantics, and so every use of the old variable might be replaced with a function of the new variable, e.g., replace ANGLE with RADANGLE and each use of ANGLE with RADANGLE * 180 / PI.  That change process is easier if the name *isn't* automatically changed in all references.  So I guess it depends which of those situations you think will come up most often for beginners.

But, @jmoenig, I think there is an inconsistency in your philosophical approach, and I could use some clarity about it.  Here you are saying that a variable blob is not associated with a variable at all, but rather with a variable *name.*  But elsewhere you've argued that blocks programming shouldn't boil down to names of things; that (for example) a sprite *has* a name, but when you drag a sprite into an expression you're getting the sprite itself, not its name.  Similarly with blocks; it's the block that's fundamental, not its name (its prototype).  I don't understand why variables are different in your mind.

**Comment by cycomachead** [comment]
Ugh, I lost my long discussion on this. However, I have a few thoughts:

* I do not think that making certain actions "harder" by picking good defaults is bad. Hell, that _is_ the basis of Snap<em>!</em> and the web browser. Whether Dan's suggestions merit the correct default is a separate discussion, and the one we should be having, but doing things automatically and making these tough decisisions if why Snap<em>!</em> is great!

* Tools are certainly useful, and would be great, but they also come with their own burderns and complexity. 

* On the teaching side: Half the point of BJC is to teach a proper and sane way to write to code! Maybe not half, but by teaching lambda, and recursion, and properly abstracting things - we are all "imposing" concepts on students, regardless of whether they really need them. (Scratch alone, is turing complete afterall.) "Refactoring" doesn't have to be a horrible concept that we impose on students, we don't even have to call it.  And, with all due respect, you __can__ refactor code without units! Because, I do it for the Snap<em>!</em> codebase all the time! (Also, you _can_ write unit tests in Snap<em>!</em>, so there's that too!)

* Dan's central problem: Visual Languages make certain actions slow, and this makes a variety of tasks quite hard. Renaming variables is certainly a chore right now, forntunately we all seem to agree. I have (sadly) left typos in sample code sent to students because it's just too slow to fix.

**Comment by bromagosa** [comment]
If I may contribute to the discussion, I think Pharo Smalltalk got that right by letting you do both things, as it is true there are cases where you may need to do one thing or the other.

A less technical naming should be used in Snap!, but in Pharo you can either just ``rename`` a variable or ``refactor → rename`` it. Pharo will then smartly do what needs to be done regardless of scope.

**Comment by brianharvey** [comment]
Ah, if Smalltalk does it, Jens has to like it!  :-)
I vote for "rename here only" vs "rename with callers."

**Comment by cycomachead** [comment]
> I vote for "rename here only" vs "rename with callers."

What are you saying is the distinction?

**Comment by brianharvey** [comment]
"Rename here only" changes the name in the particular orange blob you right-clicked.  "Rename with callers" (which is an option only for the places where vars are declared) renames this variable in all the blobs that are in this scope.

**Comment by cycomachead** [comment]
Ah, I see. 

In that case should "rename with callers" also update the drop down menu in SET blocks?

Also in that sense I'd suggest the following names:

Relabel (in the context menu of a blob)
And Rename all (in the context menu of a declaration). Perhaps it could actually say "all in this script" or the help text could provide more description. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Yes, about the dropdown menu.

Declarations will have *both* options.  (Maybe you are doing the name change because you've just realized the code in this block refers to a same-name variable from an outer scope.)  And I'm trying to avoid making users have to distinguish word pairs like "relabel" vs "rename"; I wouldn't know which meant which!  That's why I'm using "rename" for both, and adding words to both options that clarify the meaning.

**Comment by kbakalar** [comment]
This discussion seems to be focused on renaming orange blobs. I will change the subject only slightly.

I can make a block and delete a block.  I can also rename a block (in the block editor) and the change is propagated to all uses. 

I can make a global variable and delete a global variable on the variables pane.   I cannot rename a global variable.

I am surprised and chagrined by the asymmetry between block names and global variable names. I often regret in leisurely review a global variable name chosen in haste.

**Comment by cycomachead** [comment]
Closing this because of Bernat's work - some of these aren't yet handled but are documented in more recent threads.
