### ISSUE TITLE
Should there be a 'devel' branch for merging PRs?

### ISSUE THREAD

**Issue by Arthur2e5** [jmoenig/Snap--Build-Your-Own-Blocks#1053]
It appears that many PRs are tagged with a to-merge status i.e.*blessed by Jens ;-)*. If you make a devel branch and set it to the default branch in repo settings, people will automatically make PRs to that branch and you can resolve potential merge conflicts ahead of time.

**Comment by jmoenig** [comment]
The "blessed by Jens ;-)" tag is just a reminder to myself that I've already reviewed the PR and decided to pull it with the next batch of changes. Usually I also pull other PRs, so that tag doesn't mean much, except it tells me I don't have to look at those (usually very simple and straightforward) PRs again.
