### ISSUE TITLE
Should a menu morph know if it's shift clicked?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1064]
I'm working on #983 to support shift-clicking menus...It seems like things would be easier if a MenuMorph  maintained a property `isShiftClicked` that could be accessed when building menus. That would reduce a small but consistent bit of duplication in code.

**Comment by jmoenig** [comment]
Well, the world already remembers all held down keys, and each menu that want to use that only has to check once...
I see your point but this is just a convenience cache, and such caches have a habit of getting out-of-synch, therefore my own personal preference is to don't cache a particular key state again in each menu...

**Comment by jmoenig** [comment]
(Thanks for working on this, let me know if I can help!)

**Comment by jmoenig** [comment]
Oh, and if it's any easier feel free to add extra "hidden" menu items that only appear if the menu is shift-clicked.

**Comment by jmoenig** [comment]
(totally hijacking this thread): How do you feel about imposing a 10 MB size limit for the media component of a project only? That way projects can have unlimited code but no more than 10 MB of costumes and sounds?

The downside is that we'll only find out once the student actually saves the project, which might be at the end of the school period. If we tell them *then* that their project wasn't saved and cannot be saved unless they change something about it, we'll likely cause panic all over.

So, maybe we shouldn't impose a size limit after all...

**Comment by cycomachead** [comment]
RE Size limits: We could in the IDE maintain a count of serialized media size. However, I think t might be better to wait until necessary. Also, the hard part about giving students a limit is that base64 balloons the file size so no matter what we do it's not easy for kids to check on their own. 

--- 

RE Menus:

My thought was this: Since the check for shift clicking is always (to my knowledge) done when the menu is created, making it a property of the menu wouldn't make much difference, at least in terms of caching. 

My process for adding the shift-click menus was going to be to add a switch

```js
    if (shiftClicked) {
        menu.addItem(
            localize(text) + ' ' + localize('(in a new window)'),
            function,
            null,
            new Color(100, 0, 0)
        );
    } else {
        menu.addItem(
            text,
            function
        );
    }
```
To _every_ method of exporting XML and change what parameters `function` is called with, but this seems like a LOT of code duplication. So, I was thinking I could make a generic function like `addExportMenuItem`, but there's not really a good place to put that.

**Comment by jmoenig** [comment]
I don't want to keep serialized media around just to check the size. A size limit of some kind seems really necessary, because I've actually seen a lot of giant projects already, and students (and teachers!) claiming that they aren't, which makes it even worse. You're right about base64 blowing up the size of media, but that's the standard thing for data uris, and changing that requires deeper changes. I think it's fair to implement a media size limit, if push comes to shove students can simply remove media files from their projects and then save it again.

Let's stick with querying the world hand for shift-click in such menus that we feel we need to know about it. Sure, it duplicates some code, but it's also very direct code, easy to read and very maintainable.

I like your switch solution!

**Comment by cycomachead** [comment]
Ah, I didn't mean keeping the actual data around, just a counter whenever some media is dropped in. Basically whenever some drops in data, we can increment a project counter, and the delete the serialization, and when a project is opened, the size counter would start with whatever the current size of media is.

**Comment by jmoenig** [comment]
Right, that could work. But - as with every cached value - it's hard to detect when that value is no longer valid, especially when we use JS libraries to manipulate, create, copy and delete costumes and sounds.

**Comment by brianharvey** [comment]
Re media size:  Here is a radical proposal.  We store media separately from the project.  We save a costume/sound as soon as it is created/imported into a project.  When the user saves the project, we re-save only costumes/sounds that have been edited since import, which will be relatively few of them, especially the ones that are humungous sound files.  This spreads out the load on the network.

**Comment by jmoenig** [comment]
We already are smart about media.

we can't store it when it's imported because the project might still be unnamed, or it might be another project that the user wants to rename later.

We *are* storing media and blocks separately, and we only update the media if it has been changed. If a user only edits the blocks and saves the project again, only the blocks get uploaded.
