### ISSUE TITLE
Passing `undefined` causes repeat to infinitely loop

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#1073]
(The actual value, not just the string.)

**Comment by jmoenig** [comment]
How can you trigger this?

**Comment by cycomachead** [comment]
Now that the `length of` thing is fixed, it's probably hard, though certainly possible if you use JSFunction, but that's uncharted territory.

I'm fine thinking this one over, but hanging issues make me _very_ nervous, that's why I filed it.

**Comment by jmoenig** [comment]
Oh for sure, I could hardly sleep knowing there's a hanging issue "live" in Snap right now. You can easily crash Snap with JS functions, so I'd vote to not address this issue at this time. Actually, I'd like to know when this would happen anyway, because if it would then *that* would point to a different issue altogether.

**Comment by cycomachead** [comment]
```js
function f() { return; }
```
Returns `undefined`, correct? 

It's a simple enough error (and fix), that I don't think this harms things, but I'm fine sitting on the change. In the past few years I've definitely seen/heard cases of hanging, but nothing recently and I have no idea that this particular issue is what would have caused them.

**Comment by jmoenig** [comment]
Sure. Same as ```while (true) {}``` is totally going to trash a browser tab... :-)
