### ISSUE TITLE
Sub-Par Method of Converting String to Number

### ISSUE THREAD

**Issue by J0SLAN** [jmoenig/Snap--Build-Your-Own-Blocks#1123]
I see that the way you convert strings to numbers is by using " +string ". This is generally slower than simply using " Number(string) ", and can be shown to be by this benchmark test:
[http://jsperf.com/best-of-string-to-number-conversion/43](http://jsperf.com/best-of-string-to-number-conversion/43)
I was hoping you could do some testing where you are and decide on the fastest one. Thanks a bunch.

**Comment by jmoenig** [comment]
Wow, that test is pretty dramatic! I'd be interested to know, however, if using the ```Number(string``` conversion for Snap! would actually result in a noticable difference. We went fro ```parseFloat()``` to implicit ```+string``` because the semantics were a better fit, not for performance reasons...

**Comment by cycomachead** [comment]
I don't think there's a way to win in the case of benchmark based optimizations. In Safari, `parseFloat()` is the fastest, and `Number()` is actually the slowest...

**Comment by liam4** [comment]
Do an on the fly speed test to decide which method to use? ;)

**Comment by J0SLAN** [comment]
Well, seeing as most of the benchmarks (You can see past benchmarks on the same page) show " Number(string) " or " parseFloat(string) " to be the fastest for _most_ browsers, I'd think that that'd be the one to use. I use numbers _quite a lot_, and all these operations add up. 3D rendering is no joke.

Also, I like liam4's idea. Why not, at the start of every session, decide which to use based on the browser? I'm sure there's a way to test which browser the client is running. I had some function for detecting IE/Edge at some point, so there oughta be similar things for other browsers.

**Comment by jmoenig** [comment]
Well, I think Michael is right. This is a JS internal issue and likely doesn't have any noticeable impact on Snap at all. I've decided to leave it like it is now. Thanks.

**Comment by cycomachead** [comment]
To add to what Jens is saying:
It's not that we _couldn't_ do it, but that there's lots of potentially unforeseen side effects. I don't think anyone here disputes that we all use numbers a lot. (I mean, we're talking about computers and graphics and nerdy-people-types. I like my numbers too! I'm sure Jens does, as well!) We all do want Snap<em>!</em> to be fast, but I think we want Snap<em>!</em> to work before it works fast.

Consider that even if we do something like checking browsers, that means adding an additional custom function call wherever we need a number, and custom function calls have lots of overhead. This is why `for (;;) {}` loops almost always show up as being faster than a `obj.forEach(function () {})` thing...but we just use forEach because it's easier to maintain, and when you're doing a lot of operations in the function, the overhead doesn't matter as much.

**Comment by J0SLAN** [comment]
Where would the extra call come from when you convert the numbers? At the start of the session, you'd check the browser and change the string that the number blocks compile to (Like from " return +a + +b " to " return parseFloat(a) + parseFloat(b) "), before anything even happens.

**Comment by jmoenig** [comment]
see, ```parseFloat()``` also has slightly different semantics that we specifically decided against when making the change to implicit ```+string```:

```JavaScript
parseFloat('123ABC')
```

evaluates to the number ```123```. That used to cause a lot of worries in Snap.

Bottom line: We value semantic correctness over rabbulistic optimizations :-)
