### ISSUE TITLE
cannot connect to miosoft

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1144]
This is weird.

I can't connect to miosoft in Chrome right now (on only one computer). It's fine in Safari and on other computers, but not in Chrome on my MBP. I can't save or open anything.

![image](https://cloud.githubusercontent.com/assets/6549787/13230112/163fc1ce-d972-11e5-9f11-f3c079d917d3.png)

**Comment by maryfries** [comment]
cache clear does not help

**Comment by jmoenig** [comment]
seems to work for me...

**Comment by maryfries** [comment]
Yeah, it works for Paul, it works in Chrome on my Airbook, and it works in Safari on my MBP, but it's still not working in Chrome on my MBP.

The only thing I can think to do is to restart Chrome (now that I think about it, that probably **will** fix it), but I'm not ready to do that at the moment... ;)

I'll update this issue when I do.

Let me know if you want any troubleshooting data from me before I do that.

**Comment by cycomachead** [comment]
If there are cloud issues, I think clearing the cache is probably not likely since we haven't changed the cloud.js file -- clearing cookies or clearing local storage could possibly fix things, but I'm not sure if there's an easy way to do it. (Clearing local storage will also delete projects that are saved to the browser, so you'd need to be careful.)

**Comment by bromagosa** [comment]
Funny... I'm having cloud issues again, and I can't recall what I've done to trigger them... I probably logged in from Snap4Arduino, but I've done that before. Here's what Chrome devtools say:

```
Failed to load resource: the server responded with a status of 400 (Bad Request)
snap.html:1 XMLHttpRequest cannot load https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m16. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://snap.berkeley.edu' is therefore not allowed access. The response had HTTP status code 400.
```

What's weird is I can log in when in private mode, and removing cache, localStorage, cookies and every possible other thing doesn't help:

![gas](https://cloud.githubusercontent.com/assets/1016697/13254568/1a659f8c-da42-11e5-8135-6e16df265d86.png)
![gas](https://cloud.githubusercontent.com/assets/1016697/13254577/28a3e9b4-da42-11e5-8fc0-d1a4e2f83253.png)
![gas](https://cloud.githubusercontent.com/assets/1016697/13254583/33532ee2-da42-11e5-9014-b2bca9a42dcb.png)
![gas](https://cloud.githubusercontent.com/assets/1016697/13254590/3c8fb688-da42-11e5-868c-47f57e0b210d.png)
![gas](https://cloud.githubusercontent.com/assets/1016697/13254599/4716edb0-da42-11e5-8923-0e7a2160d94a.png)

I'm not saying this is a bug in Snap! (clearly it is not, since incognito mode lets me log in), I'm just wondering what could I have done and what can I do to revert it...

**Comment by maryfries** [comment]
Interesting. I'm still having problems with Chrome, but like you, I _can_ use Chrome in Incognito mode...

I also see this:

https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m07 Failed to load resource: the server responded with a status of 400 (Bad Request)
snap.html:1 XMLHttpRequest cannot load https://snap.apps.miosoft.com/SnapCloud?SESSIONGLUE=.sc1m07. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://snap.berkeley.edu' is therefore not allowed access. The response had HTTP status code 400.

Sounds like whatever it is, it's the same problem.

**Comment by maryfries** [comment]
Teachers have begun running into (seemingly) the same error:

![image](https://cloud.githubusercontent.com/assets/6549787/13267918/a59c370e-da4d-11e5-9fcb-dae9b41e117d.png)

**Comment by maryfries** [comment]
Deleting all of the cookies from snap.apps.miosoft.com fixed the problem. I'll alert the teacher to this fix, but I think it's probably still a bug that needs attention, right?

**Comment by cycomachead** [comment]
Closing since this is over, but I specifically created #1795 Around related cookies issues.
