### ISSUE TITLE
glitchy block redraw

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1145]
I deleted two blocks one at a time from the if section of this if-else, and I got these weird relics...

![image](https://cloud.githubusercontent.com/assets/6549787/13230132/2eb04b52-d972-11e5-9c56-d51a67aaa958.png)

**Comment by jmoenig** [comment]
Thanks! This one's also fixed in the next (upcoming version - v4.0.5):
http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=mfries&ProjectName=U6L1-Tree&editMode

**Comment by maryfries** [comment]
Verified. I cannot reproduce the bug on dev. :)

**Comment by jmoenig** [comment]
This bug is the long nose of optimizing the project loading code slightly by avoiding seemingly redundant redraws of blocks and stacks. Turns out, those weren't all "redundant" after all, so now, months after the optimization there are still cases surfacing that need special-case tweaking (now that the general case has been "optimized"). Hmm... I'm half expecting there to be more...

Thanks, Mary, for finding and reporting these, and for all the quick testing!

**Comment by brianharvey** [comment]
Ugh, special cases are annoying.  Sorry about that, Jens.  There isn't any unifying characteristic that these special cases have in common?

**Comment by jmoenig** [comment]
Well, they're not hard to fix, but the general case was ... too general. See, the problem with making things faster is that it often enough requires special casing instead of generalizing. Just keep reporting these glitches and I'll fix them as they come up!

**Comment by jmoenig** [comment]
fixed with df0269f5ccfce06e3c577aadb5b3559263edb9b2
