### ISSUE TITLE
mutating reporter?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1162]
Here is a selection sort that I'd written with a swap (**script variables**, **set**, **replace**, **replace**) in it.

I found the behavior of the mutator surprising.

After setting **names** to the starting list and then calling **sort** (**names**), the list stored in **names** is changed but to _neither_ the starting list _nor_ the sorted list; it's changed to the list run through the **for** loop once.

What seems to be happening is that when **sort** (**names**) is called, the first pass through the recursive case of the script mutates the inputted variable, but then when sort is called recursively with a different input list (i.e. _not_ **names**) the mutator is not impacting the original **names** variable.

I can see why that happens, but I was surprised by this behavior for a reporter. I would have expected a reporter to leave the inputted variable untouched.

Was this an oversight or a choice? If it's a choice, why? Shouldn't reporters _not_ mutate?

![image](https://cloud.githubusercontent.com/assets/6549787/13649364/5f3ab9a6-e60b-11e5-92b0-3a54afe2c79b.png)

**Comment by brianharvey** [comment]
Just because you use a reporter doesn't mean you're doing functional programming!  It's up to the programmer to follow, or not follow, the functional programming paradigm.  The only thing guaranteed about a reporter is that it reports a value.

I find your algorithm confusing.  You could write an entirely functional selection sort, or you could write one that works by mutating the input list.  Both of those would be understandable code.  But not this half-and-half thing.  Why bother mutating the list if all you're doing is finding the smallest item?
COMBINE WITH (MIN) ITEMS OF (LIST).   :-)
