### ISSUE TITLE
Connection Issues: error connecting to miosoft cloud AND Load Failed: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1172]
Two possibly related connection issues came up in the last two days:

A few of my students are having trouble logging in and accessing their cloud account projects. The error message is something like - error connecting to miosoft cloud. Students are using chromebooks so they only have the chrome browser. We've tried deleting cookies, clearing cache, and restarting the computer. This error is still happening to just a few of the students. Is there anything else I can try? Seems to be something specific to these students' computers.
https://piazza.com/class/h8yx482idav52y?cid=729

My students are trying to open previously saved files and they are getting the error:
Load Failed: TypeError: undefined is not a function.  It's saying this error for every file they try to open.  We have already cleared the cache.
https://piazza.com/class/h8yx482idav52y?cid=728

**Comment by jmoenig** [comment]
I would love to investigate this, if they could share their projects and let me know the links I can try to reproduce and fix the problem / salvage the projects

**Comment by maryfries** [comment]
On the first issue, it sounds like they can't even get into their accounts, so sharing is not going to be possible.

On the second, they can't open these files, so I doubt they'll be able to get to the URL at all.

BTW, I'm having intermittent trouble getting onto http://snap.berkeley.edu/ right now. It seems to be in and out.

**Comment by jmoenig** [comment]
Oh right. If they can't access the cloud they can't share their projects. Dang. But if they do manage to access the cloud they can just share the problematic projects in the project dialog, and then let me know the project names and their user ID's, so I can look at those projects myself and see what I can do to help.

**Comment by maryfries** [comment]
"One of my students thinks it was because he selected "table lines" and "table support" after viewing the table in the old format.  Is this possible?"
https://piazza.com/class/h8yx482idav52y?cid=728

**Comment by maryfries** [comment]
"When I click on the link to open the U4L3 project file, it gives me a message that says "unable to retrieve project." Please help, my kiddos will be up to that part in class tomorrow!
 
"The link is: http://snap.berkeley.edu/snapsource/snap.html#open:http://bjc.edc.org/bjc-r/prog/4-internet/U4L3-BigNumbers.xml "

https://piazza.com/class/h8yx482idav52y?cid=732

**Comment by jmoenig** [comment]
This is very unlikely. I'd really love to investigate, but I *need* a shared project, otherwise there is nothing I can do.

**Comment by bigmoose316** [comment]
Hi, I'm one of the teachers who reported the connection error. This only affects the students who logged out and try to log in again in the last few days. The students who have remained logged in haven't had connection problems. Students are using Chromebooks so they only have access to chrome browser on those devices. We tried deleting cookies, clearing cache, and restarting the computer - still had the error. When we switched these students w/ connection errors to PC laptops (chrome browser), they were able to log in to SNAP.

**Comment by jmoenig** [comment]
Ah, thanks for this information. Logging out should not affect connectivity in any way, because technically Snap simply remembers the user credentials and actually logs in for each individual access to the data base and then logs out again automatically. The only thing that happens when you "log out" is that you tell Snap to no longer remember your user credentials, which also removes them from local storage.

I don't know what may be causing this, and I don't have a Chromebook myself. One thing you could check would be how much space is taken up by the browser's local storage. I would assume it not to be much, if any at all, because Chromebooks are meant to be connected to the cloud mostly, but if somebody saved a particularly big project to localstorage instead of the cloud then perhaps that quota could be used up, in which case - well, I don't know about that - maybe, just maybe, the browser refuses to store the user credentials afterwards.
