### ISSUE TITLE
Problem to save locally the picture of a script

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1174]
![capture d ecran 2016-04-01 a 21 20 48](https://cloud.githubusercontent.com/assets/17542520/14214728/ad02201a-f84f-11e5-8bc9-b8e5846f5ded.png)

It is not possible to have the image of script saved on your computer with snap! 4.0.6.
It was possible with Snap! 4.0.4.

I need them to help my students. I have to  copy part of the screen to save the image, actually. Like this picture :
http://nathalierun.net/lycee/piwigo/picture.php?/5690/category/82

Thanks for your help.
Nathalie (a french-Reunion island teacher)

**Comment by cycomachead** [comment]
Which browser are you using and where did you try saving the image from?

**Comment by nathalierun** [comment]
I use Firefox last update. It is the same with Chrome.

**Comment by nathalierun** [comment]
Hello, 
I still have the problem.
I cannot save an image of a script on my computer when I try to save it.

![capture d ecran 2016-04-13 a 16 29 16](https://cloud.githubusercontent.com/assets/17542520/14493287/c3f95e60-0195-11e6-8e5a-7c87e10e3d51.png)
![capture d ecran 2016-04-13 a 16 29 30](https://cloud.githubusercontent.com/assets/17542520/14493291/cab3caf6-0195-11e6-8a65-f6438a22eeb7.png)
![capture d ecran 2016-04-13 a 16 26 21](https://cloud.githubusercontent.com/assets/17542520/14493303/d6fa634c-0195-11e6-9014-43bfbf6ba314.png)

Is it a bug ?
Please help. I need this for my students. Thanks a lot.
Nathalie

**Comment by jmoenig** [comment]
Hmmm... this is strange. I can save exported script pics both from Firefox and also Chrome. It appears that the script pic is indeed shown in another browser tab here. Can't you just right-click on the picture to save it? Alternatively, can't you just press ctrl-s, or - better yet - if it's a Mac you're working on simply drag the pic out of the browser and drop it either on the desktop or into the finder?

**Comment by nathalierun** [comment]
When I right-click on the picture, nothing appens.

![capture d ecran 2016-04-13 a 19 01 42](https://cloud.githubusercontent.com/assets/17542520/14498203/94bab9c2-01aa-11e6-85c9-6b3535c63b18.png)

When I drag the pic out of the browser and drop it on the desktop, it gives me the link.

![capture d ecran 2016-04-13 a 19 06 49](https://cloud.githubusercontent.com/assets/17542520/14498312/ffed47b4-01aa-11e6-9127-86a93f18acfe.png)

**Comment by jmoenig** [comment]
How strange! So, you are using a Mac, but the OS appears to be somewhat old-ish, which might explain what happens here. But then again, I don't know, because Firefox clearly is able to display the pic. Any possibility that you could update your Mac to a more current OS version?

I'm roping @cycomachead back into this discussion. Michael, could it be the case the the new blob-uri mechanism causes this on older OS/browser versions? It looks like Firefox and Chrome are able to display the blob-uri encoded image, but then somehow prevent it from being saved.

@nathalierun can you perhaps let us kmow exactly which version of OS/X you're using, and also which browser version exactly? Some browsers (I know this of Chrome) stop updating on older OSs, so that could be a possible cause.

Michael, do you think it could make sense to simply export script pics the "old" way (i.e. with regular data-urls instead of blob-uris)?

**Comment by nathalierun** [comment]
I am sure it is not related to my OS because I have several computers on Linux, it is the same.

This computer is on dual boot Mac/Linux. 

![capture du 2016-04-14 09 17 49](https://cloud.githubusercontent.com/assets/17542520/14517831/e66ef6a2-0222-11e6-9d4e-b4ecb9aaec66.png)

I am sure that the problem comes with your blob technology because I did not have this problem before.

![capture du 2016-04-14 09 13 25](https://cloud.githubusercontent.com/assets/17542520/14517886/7154c95e-0223-11e6-8ea2-4c14f8d407f8.png)

Look : the image has 0px x 0px

![capture du 2016-04-14 09 13 57](https://cloud.githubusercontent.com/assets/17542520/14517905/9acd69da-0223-11e6-85cd-a45d215ae15f.png)

**Comment by cycomachead** [comment]
Which version of Firefox are you using?

I think this is a Firefox bug. Try clicking on the background (not the image) and selecting the option "Save Page As...".

![screen shot 2016-04-13 at 11 02 58 pm 2](https://cloud.githubusercontent.com/assets/1505907/14518362/009ed01c-01cc-11e6-8830-18aabb9b6fb3.png)

**Comment by cycomachead** [comment]
Ugh wrong image. :/

<img width="2560" alt="screen shot 2016-04-13 at 11 02 58 pm" src="https://cloud.githubusercontent.com/assets/1505907/14518377/1bf34136-01cc-11e6-8e75-56dfb8f63e18.png">

**Comment by nathalierun** [comment]
I think that my Firefox is up to date on all f my computers.

![capture du 2016-04-14 11 17 21](https://cloud.githubusercontent.com/assets/17542520/14519883/8a9d16e6-0232-11e6-894c-6b75a7ea3f54.png)

**Comment by nathalierun** [comment]
I have already tried to save the image by this way. Nothing appends.

**Comment by cycomachead** [comment]
This is very odd. :/ Is there a "Save Page" command in the file menu perhaps that you could try? This certainly should work. 

Can you ever get to some from of a save window where it asks for a file name?

Also, can you use the export project function OK in your version of Firefox?

**Comment by cycomachead** [comment]
> Michael, do you think it could make sense to simply export script pics the "old" way (i.e. with regular data-urls instead of blob-uris)?

The old way was still prone to the Chrome crashing bug. Which we could add (back) the code for detecting... blobs overall don't crash browsers or have adverse effects on browser history (Snap! URLs would noticeably slow Safari). We could allow an option which downloads blobs to disk instead of displaying them which should get around this issue - but it's nice to see images.

**Comment by nathalierun** [comment]
"Save Page" 

![capture d ecran 2016-04-15 a 07 02 50](https://cloud.githubusercontent.com/assets/17542520/14550298/752328a4-02d8-11e6-8de5-0ce40c615b9e.png)

Here is my save window

![capture d ecran 2016-04-15 a 07 04 25](https://cloud.githubusercontent.com/assets/17542520/14550305/889d8ce4-02d8-11e6-93ca-413a3bec5b11.png)

And the result 

![capture d ecran 2016-04-15 a 07 04 45](https://cloud.githubusercontent.com/assets/17542520/14550308/91a447e2-02d8-11e6-9534-2d085a949c5a.png)

**Comment by cycomachead** [comment]
And those files don't show up on your computer? Last ditch effort: Have you tried giving the files different names? (no `()` or `,` in the name.)

At this point, this looks very much like a browser--OS communication problem. That is definitely supposed to save the page as an image.

**Comment by nathalierun** [comment]
@jmoenig 

Good morning,

I think that you are not taking my request seriously.
I ask you to take it seriously because I have made a lot of tests with the computer scientist of my high school and it still doesn't work, neither on chrome, neither on firefox, on Windows, Mac and Linux...

**Comment by jmoenig** [comment]
Hi @nathalierun ,

on the contrary, we're trying all kinds of things to reproduce the issue! But, so far, neither of us has been able to *not* save script pictures even once on either Mac OS or Windows using either Chrome or Firefox. Many people are relying on this feature and use it on a daily basis, including myself, folks at EDC and UC Berkeley and various research institutions, so I agree with you that it *has* to just work, no questions asked, and I really would like to understand what's going on here.

Personally, I don't have access to a Linux computer, but people at the Citilab in Barcelona use Linux at lot (roping @bromagosa into this discussion here...) and apparently are able to export and save script pics.

@bromagosa , am I correct in assuming that exporting script pics works for you from Linux?

As a last resort I'm thinking about exporting script pics "the old way" again in the next version, i.e. as data urls instead of blob uris. However, as @cycomachead has pointed out, this method has the disadvantage of sometimes causing Chrome to crash without warning, because data uris are discouraged by some browser vendors.

Frankly, the fact you noone at your school is able to save exported scripts pics on *any* OS using *any* browser is somewhat disconcerting and might point to a different problem altogether, perhaps one related to some obscure "security" feature that's installed on all these computers?

Anyway, let's keep investigating into this issue, we've *got* to get this solved!

**Comment by cycomachead** [comment]
After looking at the images again, this is not entirely a Snap<em>!</em> issue, I'm fairly certain. The browser is able to correctly generate the files, but can't seem to write them to the disk.



> As a last resort I'm thinking about exporting script pics "the old way" again in the next version, i.e. as data urls instead of blob uris.

I know we don't need more settings, but Blob's are going to be the better solution going forward, so it seems like a 'compatibility setting' would be the best here. I really feel like this would be a regression stability for many students if going back to `data:` URIs were the default mode.

What version of Ubuntu were you using? I think I might have access to one to try.

**Comment by jmoenig** [comment]
I agree that going back to data uri as default would not be beneficial, and I certainly agree about avoiding yet another setting. One option would be to "hide" the option behind a shift-click gesture. But there are already too many of those, too.

As you point out, I'm almost sure that this is not a Snap issue at all. However, from @nathalierun 's perspective it certainly looks like one, especially because the problematic behavior seems to be consistent across all platforms and browsers.

**Comment by bromagosa** [comment]
I confirm saving images is working just fine in all of my GNU/Linux computers, both under Chrome and Firefox.

Maybe the best would be to set up a test case where Snap! is not involved at all, something like:

```
var canvas = document.createElement('CANVAS'),
    context = canvas.getContext('2d');

canvas.width = 120;
canvas.height = 90;

context.rect(20, 20, 80, 50);
context.stroke();

window.location = canvas.toDataURL();
```

This should show an image like this one in your current tab:

![image](https://cloud.githubusercontent.com/assets/1016697/14668801/4b2d0fe4-06e6-11e6-85ee-10e9ba146f58.png)

To run this code in Chrome, open the developer console and paste it there. In GNU/Linux it's done by pressing Control+Shift+J, I'm not sure about Mac and Windows...

If you can't download this image either, we can be sure it's not a Snap!-related issue.

**Comment by jmoenig** [comment]
Thanks for checking and confirming that exporting and saving script pics works on Linux in various browsers, Bernat!

Problem with your suggested test is, that this code uses ```toDataURL()``` which is discouraged by browser vendors recently and caused many Chrome crashes. Therefore Michael changed the mechanism to use blob uris, and it may just be that there is an issue with *that*.

Hmm...

But then I would assume that *somebody* else would be able to reproduce this. Dang!

**Comment by bromagosa** [comment]
Oh, I missed that change, sorry!

So let's set up a test code that uses blobs instead.

**Comment by cycomachead** [comment]
Oh yes, I'm not doubting there's certainly an issue, especially since the old method did work in this case. 

I'm still quite confused as to why things are failing, and without knowing that it seems hard to make a real fix.
I like the suggestion of trying this outside of snap.  


Actually, now that I think about it- there's a conditional in the saving images code that checks if the Canvas::toBlob() method is defined. I suppose that could be removed, and the rest of the exporting code should still convert the data URI to a blob if it's too long -- though this is much slower and would need some testing. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by habib256** [comment]
Hi !
Under my OSX 10.11.4 El Captain Computer with Firefox 45.0.2 and Chrome 50.0.2661.75 (64bit) I can reproduce the bug described by @nathalierun 

If I'm using Snap 4.0.6 from the official website, the picture of the script shows up  in a new tab but I can't save it to my local filesystem like @nathalierun.
(The error seems to be a file not found)

If I'm using the latest Snap source from the github locally on my computer, the picture of the script does not show it up at all.

The script from @bromagosa works well and I can download the picture with no problem at all.

**Comment by habib256** [comment]
More testing on my GNU/Linux Lubuntu 15.10 with Firefox 44.0 and Chrome 48.0.2564.97.
With this configuration, everything works perfect ! Even with Snap stored locally.

Weird ...

**Comment by nathalierun** [comment]
Hello,

We made the test on GNU/Linux Ubuntu 14.04 LTS, Snap! on Chromium, Version 49.0.2623.108 Ubuntu 14.04 (64-bit).

It works ! 

![capture du 2016-04-21 14 36 12](https://cloud.githubusercontent.com/assets/17542520/14706244/967c68a8-07ce-11e6-9507-b4c1b88fd582.png)

![capture du 2016-04-21 14 35 39](https://cloud.githubusercontent.com/assets/17542520/14706248/9d769f48-07ce-11e6-9ca7-8143b075b137.png)


And here is the image of the link of the image on Firefox 44.02 on the same computer with the same OS.

![capture du 2016-04-21 14 40 32](https://cloud.githubusercontent.com/assets/17542520/14706414/6f1b5c32-07cf-11e6-83dc-e10d606b0272.png)

Of course, it still doesn't work on Firefox.

The difference on the links are :

* data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIUAAAAvCAYAAADNXQm0AAAR7ElEQVR4Xu2cd1wU19rHf1tpS5V6URExiCBG7CVGozEaW/SacKMhaiIx9hKJUVM0yptYrhFLcq+JxhJLDIYYNWI39gaiIIiUpe/Sli1sb3M/Z3wx6s7CIjHgJ3v+gplznj3znN8858yZ7zOsj7eKglq7s07Jag0dABbMZgqPFapdgEP1WyP9fB8/Ud//I2ZmTun9vOB7LofFakw7e13rHhCWaSlxpX6nmuey4PeEYNnT8hVra5JYnHxJ6q/RmokmGEuHICeqW0dB3pQxfqG2dIQIAmxquy117XUa7wGKws7krztPaXxL21qw1uwooc7ekKOh+9lWYdgFYZvjm1aLkh3dHOnZNBvWW7O+/L6EunBTbpP9LqEuZldnDru+ynSIq9LbpwybPPpklSqEZ6nUo3PqHYcns3y/Fev/thZTl24pmmLjL2tLUWaYjFrApINaUQZVrRgsowIUiwcWx8nmfjg6CuDqEw4O393mNi2pYnn+SdxMXvDUbrxnRhSU2QiTUQ1JWQo42mxEhfuhQzsvuLrw4OrqCmdnZ5vGjcPhwMXVCw6u7XAtCzh9/amt12zqz5NUsosCAB0hDEqU5STjxef5eGVQZwQFBUEgENA+dXR0BI/Hs8m/LBYLfD6fbkvapOeqEP9dMVQas03t6yqZzUbIxGngOXrAtdVzjWrb1Mp2UQAwGtSQlF5Frw4yjBvZBxEREfDx8bFZCA0NAhHGko2FDVV75DwRhVGeiZO7J+Jqei1WflfcqPZNqdwsoiCDoKjMBIcvILcpPY87OLcCm+MArbIc5FFF4BkCnoMAZpMBalkxDHo5KLDAd/SEs3tbmE1a2gbPyQuuXiEwG3WQVaQ/uLP0GhnUilL6OJvDh7N7a/CdmBfUBp0U8vy9WDx7KHr37g0/Pz+QaeDxcv78eaxduxaHDx+mT926dQsLFiyAk5MTIiMjsXr1aqtjsX53GU5ds5xKKIqCWlECvboGFGWi++riGQy1tBhOfAMtivPXi7FiSxF4Dm50XYNWDtKO7+AGZ88gsNlc1IjSQKIUl+cMo64WHL4LBF4dwGJzGO3ziO+tlGYThbdjGfYkjEVWvhwwG9A20A3HLpSissaA8UNbg8ViY/UOMa6npkPA12LRzJfQPdwLRqMRl25WY8dvSgjYRdi5djjOpcqxYnMq3PgS/LLlDVxKkyJu5SEMfqEzpkZ3QoCPA6qqVdh1tAZX0lUWrlBUZaCzXw6mTRmNzp07M0aI+Ph47Nu3D23atMGxY8doG/3798euXbsQEhKCmJgYxMbGYtCgQYyuzshTY/GGAotzWmUldLXFmDf1RQzpFwgXJy7E1Vp8tVOImdEBCAtp9aDN8k2puJIqxILYF9G7ixe4HAopd2rwzQEpSoWpOLb9DZjBRk6BHJGh7sgurEX8N3dRKc6zsL9xXznuFWoY+9rsoiir0uPgiXyMf6UN/H0EOHNdhpLSEkz+ZySuZtRiwbIkrFk6FC90/we2HSyHI6saMWM749DvEiTsSMO2lT3g4y3AqPeOYPSgQCyM7Yllm9KRn1+AnetG4+fjOTh+Ph9zJvVAWIgPxsfdtXBEhfAMpo4R4NVhL6Fdu3aMjjpw4ADCwsIQFxdHi8JgMKBTp07Iy8uj6+/cuZP+e+XKlYztlRoz4tYJUVKhe+S8TlWNob34+Gh6XySdKEDq3Vp0DQ9Aeo4SNRX38PWK4bgrVGP3bxW4lZaC+e/2QFS4P+I3X4KXhwM+mzsA+49XIeHb4zi2IxpsDgcb95SivZ8SE8ZEYH9yKQqLSizsE5GmZilbpiiSL0qxessVzIsJwbhhHTFnVT5Srl/EhcRJKCjTYsoHiTi7LwalFXrMXpUPmSgVp/ZMgExJ4d3P7mDcAOD9id0wb8VJxIzriojnWuGfs8/itUEemBHTHTq9GRTFApcLcDksjJyTaeEIefk1LJ/RAVHPR6BVqz/uzMcrZmdnY/78+bQoZDIZBg4ciNu3b9PVkpKSQKaXhIQERkcrVCZ89UMZbmTWPnKeooCBURx8NDUMUrkWNzPLkZ6nxcnrehhkdx6sKVZ8WwSZOBVn9saAz+NAb7j/usDRgYUbmUrM/ewgLYpaNRD7eRYM8kyc3vMW0nNUSL5QYmH/TIoJlm8c7net2SNFnShmT2yP118NeyCKc/tjUCw2IHbJcZzYMQpFIg2mfXIRWlU5Tu+JgUxpxnsrcuGMYiRuehXHzwsxuF8wfk+R49/bczBuIA/TJ0YhYVcOUjMl0GtlcPEIQkWNxbsXmPRyfDYtCD27+Na7uHxYFCRSkAVpTk4O7UgyjQiFQixfvpxRFDezldhyoBylj0UKjUJMnn8w8qVg9OvqjvAQN7i7OmDrL+XYn3QWJ3+YgMu3arDy2yJoFMU4sX0UxJVqfLo5GyaDml6TcZ0DkJN1A8nb3wAR31sLT8DdSYcj2/6Fq7ersfSrNAv7JOomnZa07EhhTRRzvszGJ7H+6NfNH5t3pcLb2wMTRobg198l+PbncmiVFdiwJBIRz/nQW+lLNxXido4KbX2M2PxJJEQVSvxwMBOOfCeMGBKKhess53XimZd7e2BBTKC1tRd9/GFR1K0pdu/ejeDgYEyaNAmTJ0/GkCFDGG0knqzGzsOV9ALx4aJT12D8YDfweSzczq5CVEQbvDM+FDsPV+CHpHQc3zoEVTVqbN5XgnyRGTPGt8KLPf3x09G7yMqVonNYGzg5uyA+4Si9pjCZKSTsSMGwAaHo390XX+/NB5tSMtr/6UR1yxEF6UlQgAO+WdoBJFJs3i/CjDcCMOpFLzpSCMu0OLg+HEUiHeatzYenKxfT3whA144uMJmBy7cV2JpUDq3+/rP/6IFemP56AGrkRkz69B65eejSO9IVE4b7oLWfA8xm4F6hGp9+U2R14FfNC0ZkB+ubVI+LIi0tDR9++CEdXch6Y/369VajxC+nJUjNVjK+E+zf1Q2TRvnB14sHjc6Mq+kK/PeAmJ4iJr7qg3GDvcHjsvDF1hJkFagxZYwfekW4wl3AQZXMADK4P/58hp4+eDwuFEoj3ARcnEuR4z+JIvTpYt0+U4ebZfqo93ZsxpMuTmx8Oi2oXmE0tntk2rhwU4HjV6TWXhI31iRjffJIWremeD8+t0k27aJgcB+ZSl7u44n2gY4gQmlsIfN6fokWuSUaZOSorEaIxtptqP6+VWFQKE1o8aJYsaXIfDWj9qm9XGnIUU05H+DDp4XRmEKmKRMFiCt1KK3Uw0yRLbdnq4hzjyHteNxT6zZrxOw7lsv9Z8tHf6/eUoAoNxm3Tnz4FEUx685BsPDa38uzz+bVkgW6yaBCSdbP+XcvrunwtK6CNWh+gYezQbWjtiZvmEpWYBGLWVxHyi9oQKNVWV16zWzUKRo/4T+tK33G7ZrNJoAyQqeuydfyfYcUnImz/pjWxGtl2QLutvblK/efqHa19bdkFXcog0ZeOWr0cF87uGur15q33sNQsM3gbmR758pfzkr8Gup6nSB82vVvsG5Dtuzn/3oPECi4UeAuEcZ/tx3wpSgj43RCUaDYbJ7Sr/0gm6PKX3/Z9l+s3wOUzA7u2jXyiAcIFNyiGU1ljRACr/b2YfsLPUB2S1u0KGrKbmDZ/JexKdG2FAQ77d109TwToriSNAXJ50qw+UD9aQh22rvpgiAWrIqiOUnlhy+NRAoiClLqE0ZLor1V0iLo1JVw8+0MLs/2XJQ/Z0ibbqVeUTQXqWxNFPUJoyXR3kQU896+T6mRF1+ESHuWilVRyCuyLEhlnboKRp0CHgHdwWazUUOScrjOcPcLh0ZZAY28GA7O3jDoleA5uIPNdaCP8Rw96a1ZsiPn5BYIJ0H92xcmgxaaWhEMOgUos+FBpKhz7KmrMqzfU/aIn5+U9k5MTMQHH3xA0+GkrFmzBoMHD2YcQ2u0N6msVVVBoyB9omigOS62+wNRCAsrGal1M2WGWlYEvUYKNocHymQAxWLBKyCK0Z9Orv+wSoobDRqo5cUw6ZQAmwMHFx84uwXSwBATid4QKc640DRoFdi4OPQxUvk6hr8QiD5RgRi/8C5EBddRh+RNW3YZI/s5Y+F7fXD4tBBdwv2RkiFBYVEZfezizWoEBzrCXcDHnmQJDp2rYXQ8uTilJA+hHTth4qg26NbRCa08Hw3BBMMnA/RweVLae/Hixejbty9ee63hVz/WaG+jXgV5ZRbGDQ/H1Oiu4HAo6HQGGnKOXXYHmRmpjNT66Yu5MGnEWDxzIAb2CkSlREVfq4liY/zc8xb+vHZLjG37b1qQ4pt/kqC8KB3t23ljwdSeCGsngFprQPJFCXYk5TKS6LO+ZKbbGlxTtG8l/oNUPlqJOxmZWDK9a4OiILxARY0eJy6VQquU0KJIu6fCpWtCvPN6GPh8LsYuyLIQBRFErSQXXbr2xGfT2uKr3WXISr+Go9vffFCXSRDk5JPQ3qTd0KFD6XRDlUqFHj16gKQJcAlBzFCs0d5qhQhBPhpsXzsGFRI9fjySi6H9fBER6oNJSy7DrKlipNbHzvgNY4cEYvpb3ZB6V4mzl7IRGx0JisV5RBR1/vzt1B1EhHpbkOJ7j4qwZedp7Ns0FuIKNb7bdxOD+wchemQ4Pvp3OrwEKgtSfMehSqszWqPWFLXVOVizqFeDoli9vRTnb8rpEFgXPcix306mYnVcd/Tt1pqR2FZKhQgJbov4uZ1o4JeUhxea1gRB6j0J7V03XURHR9MpiCQnpFu3bpg1axajw6zR3iTR+V+veNODu2ZHKY6eSn+wppi8+DL6dHZgpNbf+/gMpr/ZCd0jAzBhSTaK825hb8IIuLk5PyIK4rtzqTKrpPi1DBm27rmE71aNhNFIwWgC2GwKfB4b3x+sQJVEakGKn7pharwoyFxkkGc8QiqTi1+1MAp9owLx2qzfUSEuxPn9b9NE98PTR32i+HxOV7zUN4hRFFLxLayIG4ETV2XIzFfTnSabV+f2jKYztx6fMh6+qiehvUl7vV5P55WScujQIfz666/Ytm0bo8Os0d4k023CKwK8G/08Pt6QhXOXMrFwahd6TRG7LAM9OhoZqfXS0lKs/uB5REX4YdT0M5BUleLHjWMZRUFuMpU0j5EU5zj6w4lVgi3xQ3Hsogj7jpRCr6sF38EVcqUWilqdBSnOlEZRd9H17lPolKJHSOW8Eh1iRrhj1EvB+ClZCIlEhvcnRkFYqvvTREGQ97mr8yGtNT4YGEJwE0GYTAY6DdEzoCvjoDWW9jaZTHSEIHkhJJdk0aJFdKLRzJkzGe1bo70J4xAZpMbqD3vi6i0xfj0lxORxYfR6jDx9sM1qRmp91bYivNKLi4mjn8OFFBFyhRJMGNMJWgMsIgURBdkmWDLFj5EU35JYgK3LwuHqwsX3iemQKkwY0LsDrt2uhqujxoIUf2JREM88TipXSPX4OLYtTW9fv1OLF6LcUFh2n+gmpDchvusiBWn/+LGlU9uAkNFMnVJKC/HL10Mxd3XBI6KoGyGDthYCvhJbvxiEtz+5xzhwjaW9jxw5gnXr1sHDwwMBAQHYsGEDY14JiRL10d6kM4RWH9LbA1U1BhiMFDq0dXzwSMpErX+xNR8GrRRL349El1B35BbWoH0bT6h1wDvLchj9KXDmMJLiJ65Iafr+3bH+CA1yggOfjRKxDt/8JIK3J8+CRN+4T9T46cNqi6d4gjyKzo72wIV0Nu78//Tx8M9JRbcx4IWeGNLHGxv2Ml/Us0R7G/UauHFFGDYgCJU1arQJbIWYMaE4myLHul2lT9HT9Ztucdvcvh4UvpgbjEkfZ4DDvQ+BmQ1aqKRCuPp0xA9fdMGihAI6ybm+8qzQ3m39HfD5jCB4uXHpHBmSJEVybMgTR3OVFicK4gj/VkD8rGDEb76MYpGC3gh7LqQt4qa0o7PLRFW27xD+XWnvpgiKFkVLRPz9vfl4c5gPune6/42GG1m1+PFYVYMRoinOsLe97wGSPmBH/O1q+MMDFOhPSLFG2BF/uyzo74qRz0ipUJqVlG9H/O2SAGU20fsges399AGb8jka+xVdQnRXF1/Jz7m24a/9bJx9gP8UD9gkCvJLtgrDLog/ZVya1YjNoqgTRkXhme/rQ/xrq3Oq81L+06gv/jerB+w/buGB/wH6M1lwb03/FQAAAABJRU5ErkJggg==

( on Chromium)

 and :


* blob:http://172.18.40.26/9fa813cb-9878-4e67-8b6d-3ef101d8f067 

(on Firefox)


![capture du 2016-04-21 14 52 07](https://cloud.githubusercontent.com/assets/17542520/14706619/da3a761e-07d0-11e6-8922-2fb99c4f130a.png)

A billion of thanks to Olivier Calpetard, the scientist computer of my high school....

**Comment by nathalierun** [comment]
@habib256 : And thanks to my friend habib256 to make the test.

I will now be able to save images of my scripts for my students and to prepare my speech on Snap! at the university of Saint-Denis de la Réunion on june...

I want to thank you very much for this soft because I find it fantastic ;-)

**Comment by jmoenig** [comment]
Hi @nathalierun , we're still working on a solution for this. But I'm very glad you can at least work around the issue for now!

Incidentally the next release that will be upcoming next week will let you assign sprites themselves to variables, not just their names. And then you can use those sprite-variables wherever Snap would otherwise use a name. This is something you've been asking for some weeks ago, and it's basically ready. Hang on!

**Comment by nathalierun** [comment]
Very nice ! I am in a hurry to see this.

You are really working very hard and it's wonderful for us, world's users...
We will not disappoint you because I am sure that what students are able to create with your soft is going to surprise you !

**Comment by jmoenig** [comment]
Okay, so this issue was closed automatically.
@nathalierun could you please check two things:

1) does exporting script pics (and other images) now work again for your in all of your browsers?
2) enjoy being able to use sprites in variables

We've just now updated Snap! with a new release.
Please make sure to either flush your browser caches or reload Snap a couple of times until you see the version number 4.0.7 in the "about" dialog (when you click on the Snap logo), and also advise your students to do the same. Otherwise there might be annoying errors. Those errors are caching related and *will* go away once your browser uses the current version of all source files.

The new release features
* support for first class sprites,
* Indonesian language support
* translation updates to Slovenian, Simplified Chinese and Portuguese
* a number of small bug fixes

You can read about the (cool!) new "First Class Sprites" feature in the release notes:
http://snap.berkeley.edu/snapsource/FirstClassSpritesInSnap.pdf

**Comment by nathalierun** [comment]
Hello Jens,

The last version (4.0.7) exports correctly script pics . It works now on my old powerbook under Mac OSx Snow, I guess that it works on my Ubuntu station.. Thanks a lot.
I'll have a look on your new functions with first class Sprites in few days.

**Comment by jmoenig** [comment]
Thanks for the quick test, I'm glad it appears as though we've fixed the issue, yay!!
