### ISSUE TITLE
Chrome 50: Exporting script pics no longer works when offline

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#1191]
since the last update Chrome no-longer displays null-blob uri's with generated script pics when running Snap locally, i.e. not from a web-server. Calling in @cycomachead to look into this, if you get the chance to.

I'm extremely annoyed at recent browsers' efforts to discourage running JS stuff locally. While this seems to be just Chrome specific for now and only affect script pics I'm heavily inclined to switch back to simple data-urls for exporting script pics, if you can't find a reasonably simple fix.

Could this be the writing on the wall for local project saving to also run into problems?

Hmm... Did I mention I hate browsers?

**Comment by liam4** [comment]
Is there a tl;dr reason somewhere as to why we switched to blobs in the first place?

**Comment by jmoenig** [comment]
huge data-urls generated by projects used to crash Chrome without any warning, causing mayhem for students who lost their work that way (i.e. when trying to save their projects). That's why I'm considering moving back to data-urls *only* for exported pictures (it's not just script pics that are having this issue, also pics of the stage, sprites etc.)

**Comment by cycomachead** [comment]
I think I filed this issue a few months ago. I didn't expect Chrome 50 to creep up that quickly. 

Gah. This is annoying. Let me do some thinking... I first need to update Chrome. 

I can hack around the code that tries converting images to blobs. That will get most images to be exported safely, but that means there are a number of cases that still won't work. I believe I wrote checks in for the rest of Chrome's URL bugs, which should still prevent the crashing issue, but would make it so that there are things that _can't_ be exported. :(

**Comment by jmoenig** [comment]
How about just *not* using blobs for exporting script pics? Do you think that would be an issue?

**Comment by cycomachead** [comment]
The whole problem is that our only other option leads to crashing. Images are part of that.

**Comment by liam4** [comment]
Quickly add something like this, maybe?

```js
if (/* detect Chrome */ && dataUrl.length >= /* number at which Chrome crashes */) {
  // show dialog saying 'This image was too big and couldn't be exported..
  // perhaps try a different browser?' or something along the lines of that
}
```

**Comment by cycomachead** [comment]
So I can't seem to get Chrome 50 yet.... 
I have 49 and 52.

In 52 I can save an image by right clicking on the image, but I must right click on the image.

We can also (I think) force Chrome to download to the image instead of displaying it. This should work OK, but you won't be able to see the image before it's saved. We could present a nice confirmation?

**Comment by cycomachead** [comment]
@liam4 that code is already there.

It's pretty slow to do this for big images. The problem is we still can't save those images.

**Comment by cycomachead** [comment]
We could potentially remove this conditional:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/gui.js#L3816

Note that if you scroll up and read the code, the we run into the case where data URIs are too large, and _only_ option in that case is to go back to using a blob. We could just call this "95% of script pics can be saved" but that's not really a great answer either.

**Comment by cycomachead** [comment]
> We can also (I think) force Chrome to download to the image instead of displaying it. This should work OK, but you won't be able to see the image before it's saved. We could present a nice confirmation?

LOL, I did already write the code to do this. Do `Export summary` on this project:
http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=BIG%20FILES%20MediaComp

I can probably just remove the conditional linked above? It will be slow and imperfect, but I guess that should be OK and easier to save files.

**Comment by cycomachead** [comment]
Update: So I tested, and the code to download images works in old Chrome - if they're too big, chrome just downloads the image.

So, given the issues, I think we ought to perhaps just ignore the conditional linked above. 
PR coming.
