### ISSUE TITLE
Script variable can't be removed from stage in some cases

### ISSUE THREAD

**Issue by seattleacademy** [jmoenig/Snap--Build-Your-Own-Blocks#1202]
My students are having a problem when they show a **script variable** for a short period of time for debugging purposes on a robotics/drone project and then try to hide that script variable to remove it from the stage.

If the script variable is shown more than once, the ability to hide it does not seem to be possible, and the only way to revert to the previous state is to edit the project XML or revert to a previous saved state.

To replicate, click the script several times at http://snap.berkeley.edu/snapsource/snap.html#present:Username=saasmath&ProjectName=hideLocalVariableBug and see if you can remove or hide the displayed script variable from the stage.

**Comment by brianharvey** [comment]
You should just be able to drag it off the stage into the palette, same as deleting a script from the scripting area.  Does that not work?

**Comment by seattleacademy** [comment]
Thanks, that works.  I will close for now, but since this was not obvious to me or my students, it might be best to:

1. not have more than one display of a given script variable, or
2. Have "hide" remove all instances a given script variable, or
3. Not save script variable on the stage with a project as they should, as I see it, only be transitory.

My studens use this for debugging, like console.log in javascrript or node, so the issue coming up.

However the note of @brianharvey solves our problem

**Comment by jmoenig** [comment]
Hi @seattleacademy , it's great that you're letting your students use script var monitors as a way to debug their scripts! That's exactly how I envisioned those watchers to be used. Did you know that you can even monitor script vars (including closurized non-locals) *while* a script is running (e.g. in a ```forever``` loop)? As often access to interesting features is available through the *context menu*: The *context menu* of a running script lets you create watchers for its script variables while it's running, and the *context menu* of a variable watcher lets you delete it from the stage. As Brian mentioned, you can also delete anything (including variable watchers) by picking it up and dropping it onto the blocks palette.

It's actually handy *not* to restrict monitors to a single script var name, because several scripts can have their own script vars with the same name.

There even is an - admittedly also non-obvious but - very nifty way to remove *all* temporary variable watchers programmatically, if you run the ```hide variable``` block and leave the variable name empty. Personally, that's the one I always use myself when working with script vars. I usually insert this block at the beginning of a ```when the green flag is clicked``` hatted script, or just connect it to a ```when space key pressed``` event.
