### ISSUE TITLE
Identifying individual clones

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1230]
Hello,
I well understand this :
![capture du 2016-05-22 09 50 35](https://cloud.githubusercontent.com/assets/17542520/15452568/e0e7dbcc-2004-11e6-9fce-0fe28914cc67.png)

But I wonder whether it is normal that, when you have a Sprite, you create a clone of it, you change the color of the clone and you move it too. Then you press the red stop-sign button. 
And it is the initial Sprite who dies ! 
Ethically speaking, it seems really strange to me. So life prefer the clone to the parent ?

**Comment by jguille2** [comment]
Maybe you are wrong...

-If you create a clone and then, you change manually pen color, you are changing the color of the original sprite (parent).

-You can make a script begining with "When I start as a clone" with the change of the color. Then, create the clone and you'll see that the "new colored" sprite is the clone. If you make new changes (for exemple, moving) this changes will be in the parent. After this, stop will 'kill' the clone.

**Comment by nathalierun** [comment]
Yes, I was wrong :
I tested it with those scripts :
![capture du 2016-05-23 13 14 03](https://cloud.githubusercontent.com/assets/17542520/15466189/4e638cca-20e9-11e6-8fd0-67bf268d90b9.png)

![1](https://cloud.githubusercontent.com/assets/17542520/15466080/d72a71e6-20e8-11e6-9b80-11f9322bc244.png)

![2](https://cloud.githubusercontent.com/assets/17542520/15466220/6e84cdc0-20e9-11e6-9e62-753666321391.png)

![3](https://cloud.githubusercontent.com/assets/17542520/15466223/7141df08-20e9-11e6-939c-b8a8dec43fee.png)

**Comment by nathalierun** [comment]
@jguille2 : I'm sorry but I realize that I steal don't understand how clones work.

When I make a clone, how can I change its color ?
How can I choose the clone I want to delete ? the clone I want to act on it ???

**Comment by jmoenig** [comment]
... Ah, let me again refer you to this documentation: http://snap.berkeley.edu/snapsource/FirstClassSpritesInSnap.pdf

**Comment by jguille2** [comment]
Hi @nathalierun,
Jens docs is great... and I think very clear.

You've seen [this other ticket](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1510#issuecomment-260392560) showing an example of the use of clones.

Just a comment to clarify:

  - Sprites can be used in many ways. You can use this 'powerful' 
![actionofsprite](https://cloud.githubusercontent.com/assets/2926315/20280271/208a95ee-aaac-11e6-9b51-583bcfae5ca5.png) 
but you can script directly in its area. You can send messages to others sprites... and you can change dynamically and easily all about these.

  - Clones are different. You can create and kill them programmally. But you have not an area for these... and then, 'running actions of Clone' is "more needed".

**Comment by liam4** [comment]
There's actually a section in the [*First Class Sprites in Snap*](http://snap.berkeley.edu/snapsource/FirstClassSpritesInSnap.pdf) document on that:

<img width="879" alt="relevant section screenshot" src="https://cloud.githubusercontent.com/assets/9948030/20408804/65e49840-aced-11e6-8836-2d8cc4014283.png">

[Here's a demo of that (and some more).](snap.berkeley.edu/snapsource/snap.html#cloud:Username=liam4 snap&ProjectName=Tree (Clone Manipulation))

**Comment by DyslexicAwe** [comment]
Based on the bolded word in what @nathalierun wrote on November 14, 2016:
> I really don't understand **anything** (bolded by me) about clones

I guess she was interested in the basic stuff, rather than advanced stuff (such as first class stuff). 

There's also a syntactical issue and since being Non-Native English speaker myself (my first language is Slovenian) puts me in a better position (paradoxically) than you native speakers are in, to guess what Natalie (as fellow Non-Native English speaker) actually tries to say struggling with the syntax of English language and its idioms, I guess: 
> When I make a clone, how can I change its color? 
> It would be great if I could "follow"... 

what Natalie in fact tried to say (providing "tell one from the other" idiom, see [http://idioms.thefreedictionary.com/tell+from](http://idioms.thefreedictionary.com/tell+from) second meaning v. "to perceive something as being different") was: 
"It would be great if I could **tell one clone from the other** using their (differently colored) costumes **and/or different pen size/color**".

> How can I choose the clone I want to delete?
> (Or) the clone I want to act on?

You can (not manually, i.e. not interactively), only through multiple "when I start as a clone" scripts that each include "if than" block in order to be able to identify a clone by a variable, "indirectly act on" them by changing the "chosen" clone's size, pen, differently colored costumes ...). Providing that your main script has a loop ("repeat _ times") that creates a clone ("create a clone of myself" block) after a SET block (that sets a different value for the variable) in the same loop. If you do this, then each of the multiple "when I start as a clone" scripts will be able to identify a clone by a variable and act on it (not on all of them, which you don't want, because you want each to be treated differently).  See a project (not finished yet at the moment) which you will see does all the above described - [http://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=Clones_waiting_for_food](http://snap.berkeley.edu/snapsource/snap.html#present:Username=kinestheticlearning&ProjectName=Clones_waiting_for_food) It contains four clones (I need to finish the scripts for 2nd, 3rd and 4th clone, but still it does show all the above).

**Comment by nathalierun** [comment]
Thanks to @DyslexicAwe and @jguille2 .
I come back to try to understand again and again... 
I thought I had understood but...

In this little project http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun&ProjectName=Comprendre.Clones , I don't understand why, when I press the space key, there still remains a clone.
<img width="821" alt="capture d ecran 2017-03-09 a 20 12 56" src="https://cloud.githubusercontent.com/assets/17542520/23759033/f7d23090-0504-11e7-8c33-61b40f95f86a.png">

Even if I click on this block :
![telechargement 1](https://cloud.githubusercontent.com/assets/17542520/23759086/2e4d731e-0505-11e7-8abb-02e78aa52510.png)

**Comment by jguille2** [comment]
Hi @nathalierun ,
I think theproblem here is the difference between the list (a list of things: numbers, text, sprites....) and the "real" things. I can delete an item (pointing to an object)  from a list, but I am not destroying the object. I'm only deleting the item (the pointer, the info into the list).

See this example:
  - I build a list
![list_objects1](https://cloud.githubusercontent.com/assets/2926315/23761742/1e70698a-04f4-11e7-9b3d-32f900307245.png)
  - If I delete an item, this item is erased
![list_objects2](https://cloud.githubusercontent.com/assets/2926315/23761768/3547c8f6-04f4-11e7-924c-9e22607067b9.png)
  - But I've deleted only the item, not the object
![list_objects3](https://cloud.githubusercontent.com/assets/2926315/23761793/472f7ac8-04f4-11e7-96ad-63e2a838fd43.png)

**My clones** is a list, but it's a dynamic list (showing all my current clones). I can't delete items, because it will report always the current clones. I can build a new list with it, and do the same that in the example.

But we have the block "**property/action _of_ object**" that it can do this job. Then
![list_objects4](https://cloud.githubusercontent.com/assets/2926315/23761935/da3e7fe4-04f4-11e7-8f4d-6878e9c35375.png)

That's all,

Joan

**Comment by nathalierun** [comment]
Yes, It's really clear. I totally understand this example with the a variable.
But, I still don't understand why the block 
![2e4d731e-0505-11e7-8abb-02e78aa52510](https://cloud.githubusercontent.com/assets/17542520/23795220/c5cb3016-05ad-11e7-8812-d2c159c87f15.png)
does'nt really delete ALL my clones. Who is the last clone in this list  "my clones " ? Is it me (the sprite) ?

**Comment by jguille2** [comment]
Hi @nathalierun ,

In each case, you must know when you are working with pointers (to objects) and when you're working  with the "real" objects.

I'll try to show this with an example.

![listoflists](https://cloud.githubusercontent.com/assets/2926315/23796373/dbe99576-059a-11e7-8fc4-b4a9c8b3163e.png)
  - Click the first action, building _a_ and _b_ vars.
  - If you delete an item of _b_ , you will only delete the pointer (_a_ remains the same).
  - But if you delete an item of _a_, you will delete its content... and its pointer change too. Both _a_ and _b_ will be changed.

Joan

**Comment by nathalierun** [comment]
Hi @jguille2, 
It is clear with these really simple examples.
I understand that MyClones is a list of sprite's pointers.  I have to practice now... 

Thank you.
