### ISSUE TITLE
Future concept/roadmap of Snap in front of alternatives (namely, Scratch Blocks)

### ISSUE THREAD

**Issue by q2dg** [jmoenig/Snap--Build-Your-Own-Blocks#1264]
Maybe I've been wrong all the time, but I've always considered Snap as a "Javascript version" of Scratch (and consequently, more free, more cross-platform, more tunable, etc, etc). But now, with Scratch Blocks project(https://github.com/LLK/scratch-blocks) I ask: what are the "pros" of using Snap instead of Scratch Blocks? Do both projects overlap? Maybe could both projects merge? Why would you still recommend Snap? In other words: which will be the place Snap will occupy in the ecosystem of languages of blocks in a near future?
Thanks a lot.

**Comment by brianharvey** [comment]
No, for us, being HTML5 Canvas-based has always been a secondary thing.  Snap<i>!</i> adds several advanced computer science capabilities to what Scratch offers, most notably first class functions and first class lists.  (The <i>first</i> advancement was the ability to build your own blocks, but Scratch is slowly catching up about that; Scratch 2.0 allows custom command blocks, and they keep promising custom reporters eventually.)  Coming soon: a prototyping object system so that, for example, instead of <i>copying</i> a sprite, you can create a new one that inherits the characteristics of the parent, so that changes in the parent are reflected in the child, and then selectively give the child independent characteristics.  As for merging, that was our original goal, but the Scratch Team have made it clear that that isn't the direction in which they see Scratch developing. Check out the [Reference Manual](http://snap.berkeley.edu/snapsource/help/SnapManual.pdf) for the main Snap<i>!</i> features.

**Comment by q2dg** [comment]
Ok, Thanks a lot for your explanation.
I only wanted to say that (in my -biased-opinion supported from many people ones), to be HTML5 Canvas-based is a key thing (in addition to the other things you mention) because this "feature" is really important to achieve a bigger community due to its ubiquity and standarization.
Thanks again
