### ISSUE TITLE
ringify What do you mean ？

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1286]
![82z](https://cloud.githubusercontent.com/assets/20208703/16606577/9aee5fb2-436b-11e6-92cf-354630b85d42.png)

ringify What do you mean ？

**Comment by brianharvey** [comment]
The ringify option puts a grey ring around the block or script.  You can also drag a grey ring out of the top of the Operators palette, and some blocks' input slots have grey rings built in.  What a ring means is that the desired value is the block/script itself, rather than the result of calling the block/script.  So if you click on (2+3) you get 5, but if you ringify it and click it, you get (2+3).

Almost always, you don't have to ringify explicitly because you're going to put the block/script in an input slot that already includes the ring.  The ringify menu option is for unusual cases such as wanting a double ring, to make a function whose value when called is a function.

**Comment by jmoenig** [comment]
We need a forum. Desperately.

**Comment by brianharvey** [comment]
We do have a forum thread.  Maybe for starters I should post it on the home page (which is where users are finding this github link).

**Comment by dekrain** [comment]
When you ringfied block, you can evaluate it witch call or run block

**Comment by dekrain** [comment]
with*
