### ISSUE TITLE
Length of Reports 0 (not 1) for numeric 0 input.

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#1322]
![length](https://cloud.githubusercontent.com/assets/2229297/16887005/87a0fc58-4aa5-11e6-9c6e-5d0fa0a1b75a.png)

<img width="664" alt="screen shot 2016-07-15 at 3 28 33 pm" src="https://cloud.githubusercontent.com/assets/2229297/16887008/8b91e0b6-4aa5-11e6-8100-e9bcccc94ff0.png">

<img width="786" alt="screen shot 2016-07-15 at 3 30 15 pm" src="https://cloud.githubusercontent.com/assets/2229297/16887012/8ea14b8e-4aa5-11e6-9dde-f162e17f55e0.png">

**Comment by brianharvey** [comment]
Groan.  Another reason to revisit the idea of blank=0.

**Comment by ddgarcia** [comment]
I'm not sure if I understand why this error occurs. _I_ don't have any blanks in my script within the for...

**Comment by brianharvey** [comment]
The input slot in SET expects text (it's rectangular).  When you SET a variable to 0, therefore, you're setting it to a one-character string, and the fact that the string happens to be a digit is irrelevant unless you later do arithmetic on it.

But a 0 in a numeric slot is a number, not a text string.  It's a bug that the number 0 is thought to have no digits, and I'm sure that bug is related to the fact that an *empty* numeric slot *does* have no digits and has the value 0.

In your example, since the from and to inputs to FOR are numeric slots, a zero is the number zero, which "has no digits" according to this bug.

**Comment by cycomachead** [comment]
Nothing to do with for loops or input slots!

Here's a simplified test case:
![bug](https://cloud.githubusercontent.com/assets/1505907/16944979/e66dd896-4d57-11e6-9546-90d7594e7e2f.png)


The error is here, and if you're looking for the `0` case it becomes pretty clear why this is broken:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/threads.js#L2418
