### ISSUE TITLE
Text as sprite

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#1361]
Is there any trick to create a string and treat it as if it were a sprite?
Currently I use Inkscape and export the text to svg format an then import into Snap, but it is messy when I want to modify the text.

**Comment by dekrain** [comment]
You can use SVG Costume

**Comment by cycomachead** [comment]
As a costume - no, not directly.

I think there are two possibilities:
- There is a LABEL block in the examples folder (JSFunctions project) that will stamp text. That probably won't fully do what you want.
- You could probably hack up a JSFunction custom block in Snap! That will write text on the current costume (non-svg) by borrowing from the LABEL block, or could write / modify an SVG costume.

Otherwise, we want "text box" style objects in Snap!, but they're probably a little ways off.
