### ISSUE TITLE
Stamping Webcam Snapshots on to the Stage

### ISSUE THREAD

**Issue by RatGit** [jmoenig/Snap--Build-Your-Own-Blocks#1362]
Hi All, I am attempting to do the same thing as "**[sharived](https://github.com/sharived)**" (issue #729) for our own **STEM Learning Kit** product, (see [http://www.linksprite.com.au](http://www.linksprite.com.au) for more details). The plan is to implement an image processing library in Snap! with such features as:
- Image Capture
- Grey Scaling
- Colour Mapping
- Colour Sensing
- Optical Flow Sensing
- Motion Detection
- Edge Detection
- Shape Detection
- Optical Character Recognition
- Shape Recognition
- Facial Recognition
- Blob Counting
- etc...

I am using Lighttpd as the local web server running Snap! on our pcDuino boards in the kits. Camera snapshots are stored as a file called "/tmp/images/snapshot.jpg". There is a symbolic link to this folder in the "/var/www" folder so that the web server can access it and I have made sure that the file and folder permissions are set accordingly, (ie. "owned by www-data").
When I use the technique to stamp camera snapshots on to the stage initially described by "**[Gubolin](https://github.com/Gubolin)**" it always works the first time, but fails to update the image on subsequent calls... see below:

![Stamp Snapshot Script](http://learning.linksprite.com.au/files/stamp-snapshot-script.png)

Just in case it was due to a web server caching issue, I've tried accessing it as a URL with a random string argument and setting the following Lighttpd caching options, all to no avail:

_server.stat-cache-engine    = "disable"
server.network-backend      = "writev"_

At this point I am stuck and would appreciate any suggestions...

ps. I'd also like to know how to "clear" the stage, (ie. fill it with a particular colour, eg "White"). This would prevent previous images saved to the stage to be preserved between script loads.

pps. Should
`if (isWarped) {sprite.startWarp();}`
actually be ?
`if (!isWarped) {sprite.startWarp();}`

Thanks in advance...

**Comment by jmoenig** [comment]
The good news is that it's extremely easy to just put a picture up on the stage now, which means that you can focus first on designing the kind of interaction you'd like to enable. Just brainstorming what I think I've understood about your plan I would probably simply take the pentrails library (called "save and restore pictures drawn by pen") and tweak and remix it until it does what you want, maybe you don't even need to tweak it at all. 
You could get this to work with your image-server by just taking the part that gets the picture into Snap and turning that into a simple reporter block that returns a Snap-costume for the picture. This would then be very flexible, because you could then use your picture very freely inside Snap to

* let a sprite "wear" it as costume, which gives you scaling, rotation, collision detection, color collision detection and color-maps (internal feature, let me know if you need help with that) and all our existing graphic effects
* let the stage use it as backdrop for everything else
* use it as the current pen-trails layer of the stage, so other script can add to it

Does that make sense?

**Comment by RatGit** [comment]
Thanks for the reply... I think I will need a little more help though.
Looking at the Pen Trails library I see the following two blocks:

**pen trails**
> var cst = new Costume(
>   this.parentThatIsA(StageMorph).trailsCanvas
> );
> cst.shrinkWrap();
> return cst;

**set pentrails to:**
> var stage = this.parentThatIsA(StageMorph);
> stage.trailsCanvas = cst.contents;
> stage.changed();

My image is available as a file in the "**/var/www/snap/images**" folder, (which is accessible from the web server as either "**images/snapshot.jpg**" or "**http://192.168.100.1/images/snapshot.jpg**").

How do you propose I modify the pentrails functions to load this image as a costume and then assign it to a sprite?

ps. What is a "pen trails" anyway?

**Comment by RatGit** [comment]
Any chance for a code example?  I've tried every combination I can think of... So far with no success :(

I was hoping to demonstrate this at our state Education Resources Expo next week.

**Comment by BookOwl** [comment]
@RatGit, will the "stamp image from url" block [in this project](http://snap.berkeley.edu/snapsource/snap.html#present:Username=BookOwl&ProjectName=stamp%20image) do what you want?

**Comment by RatGit** [comment]
Hi BookOwl... thanks for the link. It should be enough for a demo, so we will be able to have something for the Expo.

I am however still keen to find out how to set a sprite's image with the output from a webcam.

**Comment by RatGit** [comment]
Hmmm... This block suffers from the same issues I've been having with my code, ie. It draws the image on the first call, but won't overwrite it on subsequent calls?

**Comment by BookOwl** [comment]
What do you mean by "won't overwrite it"?
If you won't to get rid of the image, use the clear block.

**Comment by RatGit** [comment]
There's a "Clear" block? :)

**Comment by BookOwl** [comment]
@RatGit, yes, it's under the pen catagory. It removes all pen drawings and stamps from the stage

**Comment by seteahconnoc** [comment]
@RatGit Since this issue is not closed, I am guessing, that your problem (it draws the image on the first call, but won't overwrite it on subsequent calls) still exists. I would be thankful for some advice on this case, too. Any suggestions?

**Comment by brianharvey** [comment]
The code fragment you posted makes a new costume each time.  Do you actually switch the sprite costume to this new one elsewhere in the code?

**Comment by seteahconnoc** [comment]
@brianharvey Thank you for the quick response. But since I am not quite experienced in JavaScript programming, I need some extra information to get things running.

---

To prevent a misunderstanding: I am using this code (mentioned by "bromagosa" in issue #729).

https://github.com/bromagosa/Snapi/blob/5ce48fd29dc9b5f5f38696801b96080b929e7125/snapi/threads.js#L357

Aside from the line `console.log(img);` the same code is used here:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=BookOwl&ProjectName=stamp%20image

---

In my experience, there is a sprite with a "Turtle" costume in the top left corner of the stamp from my camera snapshot. So I guess, I have to say: No, I do not switch the sprite costume. I would be thankful for some advice.

**Comment by brianharvey** [comment]
Oh, sorry, I was looking at @RatGit's code that says
var cst = new Costume(stage.trailsCanvas);

I'm a little confused because sometimes you guys seem to be talking about the stage, and sometimes about sprites.  What exactly do you want to do with this picture?  Make it a background, or make it a sprite costume, or draw it over the background like a temporary tattoo?

**Comment by seteahconnoc** [comment]
Sorry for the confusion. Some **background information**: I am aiming to create an educational project (so: "more visual and less textual programming"). It 's going to be a mobile device that uses a raspberry pi with its camera. My students should "use" the camera pictures in "Snap!" in the most simple way. In order to reach this, I am running a python script that overwrites a camera snapshot in `/var/www/html/` every few seconds.

---

In **detail**: I personally aim to use the block ![stampfromurl](https://cloud.githubusercontent.com/assets/23081344/25302208/4b4d0e24-2739-11e7-97e8-cca1d70894e1.png) from this "Snap!" extension:

http://snapi.citilab.eu/

I guess, the effect is a "stamp" (like the "stamp" from the "Pen" category).

**Comment by bromagosa** [comment]
What effect are you looking for? This block does stamp an image from a URL into the pen trails (so, on the same layer as the pen drawings or anything stamped by the stamp block). That is, as long as you have CORS permissions to access said URL.

Is that code not working for you?

**Comment by seteahconnoc** [comment]
I am able to stamp camera snapshots from files with different names. But if I overwrite a file with a new camera snapshot, the block ![stampfromurl](https://cloud.githubusercontent.com/assets/23081344/25303748/66658770-2759-11e7-90e3-7063dddd001c.png) does not stamp the new image. (I guess, that this is the same issuee "RatGit" mentioned. But I am not sure.) Any suggestions?

**Comment by jguille2** [comment]
Hi,
I think your problem is the image requested is cached. You must check your system... but I can write down some notes:
  - If you use the original "stamp image from http.//" block from the repo, you are using a proxy to bypass Cors (the [block request](https://github.com/edutec/Snapi/blob/gh-pages/snapi/threads.js#L410) and the [proxy definition](https://github.com/edutec/Snapi/blob/gh-pages/snapi/threads.js#L3)).
  - If you don't want to use this proxy, you'll have to modify this and take care about Cors in your system). But you'll have more control over caching.
  - Anyway, browser is your main 'cacher'. You must look for disabling this caching. For testing, you can change the url without changes in the file name. Adding a "?param", cache will update the content.
![http_caching](https://cloud.githubusercontent.com/assets/2926315/25304823/6fd39368-276f-11e7-9059-0d83d0628aa8.png)

**Comment by BookOwl** [comment]
@seteahconnoc, I have updated the stamp image from url block in [this project](http://snap.berkeley.edu/snapsource/snap.html#present:Username=BookOwl&ProjectName=stamp%20image) to include cache busting. This should solve your problem.

**Comment by seteahconnoc** [comment]
Thank you very much for your support.

I think, to get things started, I will use this option:
![6fd39368-276f-11e7-9059-0d83d0628aa8](https://cloud.githubusercontent.com/assets/23081344/25305568/d9f2c166-277d-11e7-8f1d-f7779068601c.png)
I guess, this is the easiest way for my students. I am aiming to reduce the configuration outside of "Snap!" in this educational project.

@BookOwl Sadly, the block in the project that you mentioned does not work on my system in the expected way. I don 't know, why. If you want, you can explain to me, which changes you made. So I would have an easier solution.

I have to learn more about the usage of pictures in "Snap!": dynamical import of costumes, etc. "brianharvey" made me curious. In order to achieve this, I 'll have to get a closer look at the JavaScript code. But I guess, this is not the topic of this issue.

My problem is solved right now. If "RatGit"'s problem is solved, too, this issue could be closed.

**Comment by jguille2** [comment]
Ok,

Then you have an easy workaround to achieve your goals.

I think your problem with Matthew (@BookOwl) proposal is Cors. With the _snapi_ block, you are using _corsproxy.citilab.eu_ to bypass Cors. But if you want to call directly the _url_, the server (where pictures are) will have to include CORS authorization to their header responses.

**Comment by seteahconnoc** [comment]
I dealt with CORS once, so I think, I understand the main concept. I consider it to be a clean solution.

In case of a configuration problem it could be difficult to explain within an educational project for younger students. I would like to encourage my students to take the "Snap!" blocks and just to be happy for it 's working out of the box.

Again, thanks for the help.

**Comment by seteahconnoc** [comment]
Sorry for bothering you again, but I guess, I cheered too soon. This may be a rookie mistake, but I am just not getting it at this moment:

If I click the blocks
![stampfromurl](https://cloud.githubusercontent.com/assets/23081344/25312774/9b90bb7c-2821-11e7-962a-2edd1822f682.png)
and
![changeversion](https://cloud.githubusercontent.com/assets/23081344/25312775/a0d41930-2821-11e7-9905-98acae42b10a.png)
seperately, I get a fresh stamp of the overwritten camera snapshot. But if I snap them together, it just won't work - regardlessly, how often I click the double block.
![stampchange](https://cloud.githubusercontent.com/assets/23081344/25312786/ce786314-2821-11e7-97e5-6dba92c56850.png)

**Comment by brianharvey** [comment]
Sounds like something about timing in the STAMP IMAGE block.  I would try (1) reversing the order of the two blocks; and if that fails, (2) put a WAIT 0.1 SECS between them.

**Comment by seteahconnoc** [comment]
@brianharvey I checked this out in (perhaps not all possible but) several ways, but I wasn't lucky.

---

So, I tested the block
![index](https://cloud.githubusercontent.com/assets/23081344/25314947/664896ac-284d-11e7-95f2-a00343251fd2.png)
on `http://snapi.citilab.eu/`. And I imported the block 
![index](https://cloud.githubusercontent.com/assets/23081344/25314956/84c5dd7e-284d-11e7-89f9-6e553a7415a9.png)
in `http://snap.berkeley.edu/snapsource/snap.html`. I discovered, that
![stampchange](https://cloud.githubusercontent.com/assets/23081344/25314966/a3b6bc8a-284d-11e7-8a27-80e6b3b361e9.png)
works just fine in both environments, when the file is located on a webspace with Apache an `Header set Access-Control-Allow-Origin "*"`. For I am aiming to use a Raspberry Pi with `lighttdp`, I just have to find out the appropriate way to configurate it. For I am not quite experienced in this matter, I have to learn right now (read the manual, etc.). I hope, this results in a success. Any help ist welcome.

**Comment by seteahconnoc** [comment]
Meanwhile, I managed to get the response `Access-Control-Allow-Origin: *` on the `curl` command. Sadly, this does not lead to any further success.

**Comment by jguille2** [comment]
@seteahconnoc 
I'm missing something. How do you import the block to Snap! online (from snapi version)? It is a primitive block. I can't do this.

**Comment by seteahconnoc** [comment]
OK, I described this a little inaccurate: I built my own block with `run ... JavaScript function` and this code:

https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1362

I only changed the first line to: `var sprite = this,`

**Comment by jguille2** [comment]
Ok,

Then, as I pointed in [my first response](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1362#issuecomment-296372956), you can use a proxy to bypass Cors.

Then you can change
```javascript
img.src = 'http://' + url;
```
to
```javascript
img.src = 'http://corsproxy.citilab.eu/' + url;
```
You can use another proxy, or build your own... and then, you can run images into servers without the _Access-Control-Allow-Origin_ policy. Of course, it will be better when you introduce the policy into your servers.

Joan

**Comment by seteahconnoc** [comment]
Thanks.

Now I got the problem, that I cannot reproduce the state, where it was possible to get a fresh stamp while the blocks are snapped together like this:
![a3b6bc8a-284d-11e7-8a27-80e6b3b361e9](https://cloud.githubusercontent.com/assets/23081344/25337404/08553564-28fc-11e7-9c08-f02ebf01eb40.png)
I cannot spot out the difference to my earlier procedure. If the blocks are clicked one by one, it 's working:

1. in an Apache environment (online webspace from the provider `hosteurope.de`) and
2. in an Lighttdp environment (localhost on my Raspberry Pi).

Now I tried to use `corsproxy.citilab.eu`:

1. In the mentioned Apache environment, it 's just showing the same behaviour.
2. In the mentioned Lighttdp environment, I cannot get any result. (Out of the blue, I would guess, that this has something to do with the configuration of my Raspberry Pi.)

Anyway, the usage of a proxy to bypass CORS, which is located online, is not the desired kind of solution. My wish is, to propose my students the tools to build a mobile device which isn 't dependant on an internet connection.

---

**To get a picture**: Imagine a small robot with a Raspberry Pi camera, that is able to do some image processing and other actions autonomously. If the robot has got an internet connection, there would be the option to use virtual network computing (VNC). Via VNC, the student can

- check out, what 's happening,
- watch camera pictures of the mobile device, or
- control the robot remotely.

Right now, my main problem is just to get the newest camera pictures into "Snap!". Perhaps, I need a fresh start, e. g.:

- I could think about controlling the Raspi's camera via "Snap!". I guess, I could find further literature here: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/634

- Or I could use file names with time information (a simpler option).

I just cannot understand, why it 's working, if I click the blocks one by one, and why I cannot reproduce the same behaviour while the blocks are snapped together.

**Comment by BookOwl** [comment]
@seteahconnoc, can you share the project? that might help us in debugging it.

**Comment by seteahconnoc** [comment]
@BookOwl Right now, my task is to collect some pieces and ideas. I just snap together a few blocks and don 't save these tests. I am aiming to motivate some of my students to realize the project.

I got a Raspberry Pi with a powerbank and a camera. There is an Arduino Mega. I use `s2aio` with "Snap!" to get things running: https://github.com/MrYsLab/s2aio I 've got two `HC-SR04` ultrasonic ranging sensor and a `SG90` servo. And there is a `L298N` dual motor driver with two gear motors, wheels and a battery pack.

You may recognize, that each detail is as cheap and simple as possible. In my experience, there are many students that get curious and start working with these parts. I am expecting, that there will be someone, who wants to change some part (e. g. the motors or the software) in order to improve the system. And from my viewpoint as a teacher, this means a good start to get in touch with physical computing.

**Comment by BookOwl** [comment]
You said that

> Sadly, the block in the project that you mentioned does not work on my system in the expected way.

Can you explain what didn't work about it?

**Comment by BookOwl** [comment]
Can you create a simple project with just the two blocks in the picture above and share that? It would help a lot to see what code you are actually running.

**Comment by seteahconnoc** [comment]
OK, here is a sample project:
[stampfromurl.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/952089/stampfromurl.xml.zip)
For testing purposes, I use two different `png` files in `/var/www/html/` (`lighttdp`) and just rename them alternately to `image.png`. If the blocks are clicked one by one, it 's working. If the blocks are snapped together, clicking and re-clicking has no effect.

**Comment by BookOwl** [comment]
It is because the image isn't loaded by the time it gets stamped to the stage. If you change the code in the JS function block to

```
var sprite = this;
var stage = sprite.parentThatIsA(StageMorph)
var context = stage.penTrails().getContext('2d');
var isWarped = sprite.isWarped
var img = new Image();
var left = sprite.center().x - stage.left();
var top = sprite.center().y - stage.top();

if (isWarped) {
    sprite.endWarp();
}

img.src = 'http://' + url;
img.onload = function() {
    context.save();
    context.scale(1 / stage.scale, 1 / stage.scale);
    context.translate(left, top);
    context.rotate((sprite.heading - 90) * Math.PI/180);
    context.drawImage(img, 0, 0);
    context.restore();
    stage.changed();
    if (isWarped) {
        sprite.startWarp();
    }
}
```
it will work

**Comment by seteahconnoc** [comment]
Now, this is a relief. Thank you, @BookOwl. So, basically this all was kind of a JavaScript programming rookie mistake. Anyway, this does not bother right now. Thank you very much for your attention, your help and your patience.

I guess, we 'll meet each other on GitHub in the future. For now, good bye.

**Comment by BookOwl** [comment]
You're welcome. Glad I could be of help. 😄

**Comment by jguille2** [comment]
Ok!
@seteahconnoc , only a last comment about cors...

If your RB is not connected, and your system has Snap and also the cam pictures, you can use img files without any webserver.
Just only `img.src = 'path/filename.ext';

**Comment by seteahconnoc** [comment]
By the way, I think, this issue can be closed.

---

@jguille2 Thank you for the interesting extra information. I just ran some unsuccessfull tests on my notebook (not on the Raspberry Pi).

- Which of the conditions you mentioned are obligatory to use local images? (Only on a Raspi? Only with a standalone version of "Snap!"?) Or is this a standard feature in "Snap!"?

- I used: `img.src = '/home/connochaetes/Tmp/image.png';` Can you point out a syntax error?

**Comment by jguille2** [comment]
Hi @seteahconnoc,

No syntax error. The problem is _path_ and _permissions_
  - If you run Snap! without a webserver (_file:///path_to_snap_files/snap.html_) then you can use `img.src = '/home/connochaetes/Tmp/image.png';` (of course, if file permissions are ok).
  - But if you run Snap! with a webserver (_localhost/path_to_snap_web/snap.html_) then your path is a _web path_ (and permissions are related to webServer user). If you write '/home/....', server will look for a _home_ folder into the _root_ folder (of the server). Your folder must be in the server folders, and you can call them with absolute paths (/path related to root folder) or with relative paths (path related to snap folder.) You can use _../../folder_ to go up (but not upper the root folder!)

That's all,

Joan

**Comment by seteahconnoc** [comment]
@jguille2 Thank you.
