### ISSUE TITLE
Interesting behavior

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1409]
Hmm... all here:
![interesing](https://cloud.githubusercontent.com/assets/19158291/18412756/32fa8ad8-7797-11e6-86d3-d6a26b830dab.png)

**Comment by brianharvey** [comment]
I'm too lazy to look them up, but we've had reports like this before.  We know that if you CALL a command or RUN a reporter it does unexpected things, but since that's a user error in the first place, this isn't high on our priority list.  When things slow down :) we should put a lot of effort into error messages in general.

**Comment by dekrain** [comment]
It's because stack is:
```json
{
"parentContext":{"exp": [
"do domething",
"do next: %s"
],
"...": "..."
},
"exp": "do something"
}
```
