### ISSUE TITLE
problem with answer variable with different questions?

### ISSUE THREAD

**Issue by cyberbu11y** [jmoenig/Snap--Build-Your-Own-Blocks#1462]
In this program:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=cyberbu11y&ProjectName=U1PT1

The code in the repeat until loop (in the guess a number block) will not run if the answer changes from "too high" to "too low" and nowhere else, but the "ask based on answer" block will run. 

No clue what's causing this, but maybe it has something to do with the answer variable (or maybe my code but hopefully not)?

**Comment by jmoenig** [comment]
Hmm... I'm not sure whether I understand this. But I've tried the following: enter 110 (too big), then enter 0. In both cases the ```count``` increases. Is that what's supposed to happen?

**Comment by jmoenig** [comment]
Oh, wait! Now I see the issue. Investigating...

**Comment by jmoenig** [comment]
How strange. I've discovered that if you change the definition script of your ```ask based on answer``` block to use an ```if ... else``` statement instead of two sequential ```if``` blocks it works as expected...

**Comment by jmoenig** [comment]
Oh. *Now* I understand! Duh. It's a bug in your code:
Look, what's happening in your ```ask based on answer``` block definition:

![bug](https://cloud.githubusercontent.com/assets/2596285/19512935/827f10d6-95ee-11e6-8757-c6782fa992a4.png)

Let's assume the user enters a number that's too high. Now this block asks "that number is too high" and waits for the user to enter another one. So what happens if *now* the user enters one that's too low? The *second* condition fires right away!

So, using an ```if / else``` will fix this, it's not a Snap bug.
Whew!

**Comment by cyberbu11y** [comment]
Wow, I completely overlooked that. Thanks! Sorry for using so much of your time on this.

**Comment by jmoenig** [comment]
Hey, no worries, this was actually fun to hunt down :-)
