### ISSUE TITLE
Background randomly zooms way in

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1472]
In project
[http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=bh&ProjectName=snap-scheme-broken]
background Slide13a has huge text:
<img width="725" alt="google chrome001" src="https://cloud.githubusercontent.com/assets/3885074/19626885/f0df49d4-98ef-11e6-9b78-84b4e4454604.png">
It should look like this:
<img width="725" alt="google chrome002" src="https://cloud.githubusercontent.com/assets/3885074/19626892/013b9aa8-98f0-11e6-9bbd-47307ba9ac24.png">
I think this happens when I save/load the project.

It's called "Slide13a" because I made it and imported it later than the others.  It was at first loaded from a jpg, and I thought that was the problem, but it happens even when loaded from a png like the other slides.

I _think_ this happens on saving or loading the project.

Help!

**Comment by jmoenig** [comment]
sounds like a retina issue...

**Comment by jmoenig** [comment]
Okay, here’s a hint on what may be causing this: It appears that you’ve created the image using your Mac’s screen capture utility, right? That’s a huge problem when taking screenshots on retina displays, because those screenshots keep blowing up, not just inside Snap, but also elsewhere. You can see this for yourself if you open that image in a normal browser tab (just drag it into chrome’s tab bar), you’ll see it quadrupling in size, whereas this won’t happen with a picture that you created “regularly”, i.e. not with a screen shot in a retina device.

The whole "retina" concept is a giant kludge.

**Comment by jmoenig** [comment]
I don't even think this is a bug in Snap, it's beyond our control. Bottom line: don't take screen shots on a retina device if you're planning to use them in the web.

**Comment by brianharvey** [comment]
Sorry, I confused you.  The pictures here on this github page are indeed screenshots, but the ones in the project came from the "Save as pictures" feature in PowerPoint.  (Basically I want to be in Snap<i>!</i> during this talk, but be able to show a slide occasionally, so I made a slide deck in ppt and then imported the slides into my project.)

So my original problem is not with screenshots.

**Comment by jmoenig** [comment]
I've patched the dev version with a fix that takes care of this. However, you have to manually delete the one "blown up" costume and replace it with your original file. After that, saving and loading should be fine.
