### ISSUE TITLE
Visual Stepping involuntarily changes sprite and pen color

### ISSUE THREAD

**Issue by davidciolinovolano** [jmoenig/Snap--Build-Your-Own-Blocks#1499]
I've noticed when I turn on "Visual Stepping" the sprite changes its color to a light teal color. And any "Pen Down" line colors are also the same light teal color, regardless of any command to change the pen color.

Please advise.

**Comment by dekrain** [comment]
The blocks' color changes to light cyan

**Comment by davidciolinovolano** [comment]
How do I change the color when in Visual Stepping mode? The light teal/cyan color makes it very difficult for viewing on a projector.

**Comment by dekrain** [comment]
You can't change it without rewriting this in code. (It uses highlight color of block.)

**Comment by cycomachead** [comment]
> How do I change the color when in Visual Stepping mode? The light teal/cyan color makes it very difficult for viewing on a projector.

I completely agree. It's hard to read even not on a projector!

```

**Comment by brianharvey** [comment]
This is imho a bug.  There's nothing wrong with the highlight block color; the problem is that the text on that block should be black, not white, while highlighted.

I cannot, however, reproduce the original poster's problem about the _sprite_ changing color.

**Comment by cycomachead** [comment]
> There's nothing wrong with the highlight block color; the problem is that the text on that block should be black, not white, while highlighted.

The problem that the color is hard to see on a projector _is_ a problem with the highlight color though. Super pale colors do not do well on projectors -- though black text would certainly mitigate the problem.

**Comment by brianharvey** [comment]
OK, I bow to your expertise; find a color that's projectable but shiny (are those compatible), make the text black, and issue a PR.  :-)

**Comment by jguille2** [comment]
Oh! I think we have two different things here...
One is the choosen color for flashing... I will not say anything about this.

The other is the bug reported (Visual Stepping involuntarily changes sprite and pen color) and it is a real bug. You can see, in Visible Stepping mode, clicking 'set pin color'
![set_pen_color](https://cloud.githubusercontent.com/assets/2926315/21409926/93f331f0-c7dd-11e6-90cd-0ebc88ba2023.png)
changes color always to 'flashing color'
![sprite_colored](https://cloud.githubusercontent.com/assets/2926315/21409935/a0585ea2-c7dd-11e6-9f19-562e8ad5ff2e.png)

Why? Because visual stepping flashs ColorSlotMorph, and in the execution (setColor) the slot/input has the "flashing color".

I push a PR to fix this.

Joan

**Comment by cycomachead** [comment]
Ah, yes, we got distracted from the original bug! But I think the PR is good. :)

**Comment by jmoenig** [comment]
good catch, @jguille2 !
