### ISSUE TITLE
Asking about list pointers

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#1500]
Hello!
I'm not sure if this is a bug or an unexpected behaviour for me.

I try to describe it with an example test:

  - I define two vars.
![array_vars](https://cloud.githubusercontent.com/assets/2926315/20042819/e983f81e-a480-11e6-9d80-1761f653b6b1.png)
  - I expected that 'x' was defined with the present values of z. But not! I see 'x' contents are pointers to var 'z'.
  - Then, when I change a value of the 'x' array, snap! updates the value of all 'z's (var 'z' and the other pointers... in this case, values of the same array)!!

This confuses me. What I see: variables setting is different depending on whether content is  a single var (assigning the evaluation of this var) or content is an array(then it assigns a pointer to it).

Thanks,
Joan

**Comment by brianharvey** [comment]
The behavior that confuses you is not really about SET; it's about LIST.

What SET does is straightforward.  It puts into the given variable the value of the expression in its second input slot.

What LIST does is to create a new list whose elements are its input values.  It does not copy anything; after its inputs are evaluated, it puts those values in a list.  In particular, LIST (Z) (Z) does not copy Z; it constructs a list that points to Z twice.

You're right that what's actually in the list element is a pointer, not to the variable Z, but to the particuar list {1, 2} that is the value of Z.  Snap! is a Lisp, which means that in principle _all_ values are actually pointers.

This would not be important except that lists are mutable data structures.  A list maintains its identity even when items are added, removed, or replaced.  By contrast, text strings are also represented as pointers, but since they're not mutable you don't notice that.

**Comment by jguille2** [comment]
Thanks Brian,

Excuse me if this is not the place (I hope the forum will be open soon)

Only one suggestion ... 

I'd like change the block //All but first of list// to a generic //All but %n  first items of list//. Then, with n=0, I can copy (evaluating) lists. I understand that it will not be a full copy (if it is a list of list, internal lists will be pointers) but it can be useful.

Is it right? We only need a param to pass to the [cdr function](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/lists.js#L154) and change the number of items evaluated.

Thanks,
Joan

**Comment by brianharvey** [comment]
That's something you can easily write yourself in Snap<i>!</i>, so we wouldn't add it as a primitive.  In any case, ALL BUT FIRST OF doesn't copy anything.  It just reports the cdr of the existing list.  But you can write
<pre>(define (copy lst)
  (if (null? lst) lst (cons (car lst) (copy (cdr lst)))))</pre>

**Comment by cycomachead** [comment]
> ALL BUT FIRST OF doesn't copy anything

Minor caveat - it will if your input was an array, but I don't think that matters here. :)

**Comment by jguille2** [comment]
@cycomachead Yes, but without recursion. I tested this and my code to do it, was based on 'ALL BUT FIRST OF'. 

With this block I get another list. It copyes all the items of the list... but then, if an item is another list, it copyes a pointer to it. 

But it's useful, and helps you to copy array content into another array. Because this my suggestion, to change 'ALL BUT FIRST OF' to 'ALL BUT n FIRST ITEMS OF'. It will help you to copy a full array (n=0) or only a picece.

In the same way... maybe it could be 'ALL BUT n FIRST/LAST ITEMS OF'. And this implementation is very easy, because I only need to pass this value/values (n or n and first/last) and change the [for](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/lists.js#L154) evaluation.

Thank you for your answers. I'm sorry but I don't know to implement @brianharvey code. Excuse my ignorance...

**Comment by Jonathan50** [comment]
@Brianharvey is using Scheme notation, it could look like this in Snap<em>!</em>:
![copy-list](https://cloud.githubusercontent.com/assets/13597222/20090141/2d065666-a5f0-11e6-8bc1-fd7bf4054c90.png)

**Comment by jguille2** [comment]
Thanks @Jonathan50 ,

Now I understand scheme notation :)

Then, to copy a list, I've made two changes and it runs ok:
![copylist](https://cloud.githubusercontent.com/assets/2926315/20097995/c2152866-a5b1-11e6-85ce-12d21e869ab5.png)

Thank you very much,

Joan
