### ISSUE TITLE
Save Page As inaccessible from Chrome

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1516]
If I want to run Snap! offline in FireFox with the menu bar visible I can click on File, Save Page As. In Chrome since Snap overrides both control-s and right click it is not clear how to do the same.

Yes, one can clone or download from GitHub but Save Page As saves less than 2MB and is easier for novices to do. Also links to download these files could be put on the home page to help people who have poor intermittent network connections.

**Comment by cycomachead** [comment]
Does the save as page include all the JS needed to run offline? There was a time where this wouldn't work.

In general, we don't want users to use the browser save as because usually they want to save their project - and students will then turn in a useless HTML file.

As far as offline usage:
We're working on it. I do agree there could be a link on the website (cc @brianharvey) but it's not a permanent solution because there are security policies that prevent everything from working correctly.

Otherwise if you click the "Snap" icon in Snap! you can download a zip file with all the correct code.

Are you on a Mac? There's a beta app you might be able to try.

**Comment by ToonTalk** [comment]
The Save Page As version seems to run fine on Windows 7 in Chrome and FireFox. You do get errors if, for example, you try to open Examples.

I tried the download from the Snap icon and I couldn't detect a difference with the Save Page As.

Not on a Mac. I wonder if a Chrome App might be a solution since Chrome is on all platforms. Not much needs to change turning a web app into a Chrome App.

**Comment by cycomachead** [comment]
> I tried the download from the Snap icon and I couldn't detect a difference with the Save Page As.

Yeah, if save as is grabbing all the JS along with it you'll get pretty much the same results - though the zip file also includes help images. But neither are great offline applications. If you are comfortable, you can use any sort of local web server to serve Snap! and everything should work ok.

We'll have a windows app soon too, hopefully. I just currently don't have a PC to test things. 
If you wanted, you could try building the windows app yourself -- but I don't know if I could be of much help.
http://github.com/cycomachead/snap-app
(Ideally you would be able to install dependencies and type `npm run build` but I've never tried that...)

**Comment by dekrain** [comment]
> You do get errors if, for example, you try to open Examples

Because it uses XMLHttpRequest which tries to download files from server which doesn't exist

**Comment by ToonTalk** [comment]
I understand that but if a teacher or student encountered that it would not be clear. Can error messages like that be made easier to understand by non-technical users?
