### ISSUE TITLE
Duplicate a block definition

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1531]
Hello,

Why is it not possible to duplicate a block definition, so it would be easier to create a second block definition similar but different from the first one ?

**Comment by brianharvey** [comment]
You can't duplicate the complete definition because you can't have two blocks with the same name/inputs.  But what you can do is start a new block definition with a different name, then open the old block, duplicate the script without the hat block (right-click on the block just below the hat block and choose "duplicate"), and drag the copy into the block editor for the new block.

**Comment by nathalierun** [comment]
Yes, that's what I already do. Thanks. But, it was the arguments of the blocks that I wanted to duplicate (when you have many blocks with the same entries)...

**Comment by brianharvey** [comment]
I see.  When we revisit the question of how to decide two block specifications are "the same" and therefore the second one is ruled out, we'll revisit this too.  But it's not super high on the list.
