### ISSUE TITLE
[serializer] Variable data in libraries

### ISSUE THREAD

**Issue by dekrain** [jmoenig/Snap--Build-Your-Own-Blocks#1557]
For example:
It's block `log %data` that adds value of `data` input to the list.
```
({log (data)}) V
add (data) to (log)
```
If I export this as library and if I load it, I must create variable `data` and set its value to `list>`.
By this issue I mean loader for each **used** variables, ie.
```javascript
// function(name, savedValue)
var newName = name;
var i = 0;
while (exists(newName)) newName = name + (++i);
if (newName !== name) {
replaceAllVars(name, newName);
}
project.addVar(newName, savedValue);
return newName;
```

**Comment by jguille2** [comment]
Hi dekrain!

My thoughts...
  - Variables (global or local) are project objects. Libraries import global blocks (and with them, their temp variables) but nothing else.
  - If I want to use a complex template (with variables, data...) I use a template project (not a library). Yes, I know I must start my work with the template (I can't upload later).
  - If I need to load a template later, or other complex cases... the real problem is that I can't merge projects. Workarounds? For me, two considerations:
    - Some people can edit xml files and build a new one with the things they need. I know this is not a snap feature... but is a powerful tool for "experts".
    - The other way is create a library builded to help me to pass data to the project. That will not be a template (I'll have to create my local variables) but the library will be ready to pass data(I won't have to edit blocks). I will use input slots with the option **"Upvar- make internal variable visible to caller"**.
----
The "log" example (useful thinking 'log action' could be  more complex) will be:
![upvar_project](https://cloud.githubusercontent.com/assets/2926315/21056049/39dc925e-be34-11e6-80c8-1172bca6c487.png)
I must to create local var "projectVar" and load its value (set projectVar = newData) but I have not to create/edit newData (is a library variable that I can use in the project).

Joan
