### ISSUE TITLE
snap_fast.html vs snap.html

### ISSUE THREAD

**Issue by nickedens** [jmoenig/Snap--Build-Your-Own-Blocks#1565]
Trying to have our students do some coding on a raspberry pi. They have a fairly intensive space asteroids program that does not like to run on the pi but it runs well on the computers. Then I happened to see that there is a snap_fast.html and a snap.html. The difference looks to be some sort of polling interval. 

Couldn't find any details on this and I don't have our pi's on me. Can anyone elaborate on the difference in the two entry points into snap?

**Comment by jmoenig** [comment]
Hi @nickedens ,

you're right, ```snap_fast``` is the old version that clocks snap as fast as the computer will go, whereas the newer method uses the official ```animationFrame``` mechanism, that basically sets the framerate to 60 fps (or slower, if your computer doesn't keep up). I really, really liked the ```fast``` version that used ```setInterval()``` instead of , but ```animationFrames```, but at some point Chrome became unbearably buggy with ```setInterval()``` and often skipped cycles altogether.

My guess would be that the newer ```animationFrames``` would support weak hardware such as the Pi *better*, at least that's what some people claimed to have found out some time ago. The ```fast``` version is likely to be even slower on underpowered hardware. However, you cold try reducing the ```interval``` to something much slower. That could actually help and result in better performance on slow processors. You could start by experimenting with, say, an interval of 50 ms.

**Comment by nickedens** [comment]
@jmoenig thank you for the quick response. When I get back to the class I'll change that interval and try it again.
