### ISSUE TITLE
Own server 

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1590]
![b](https://cloud.githubusercontent.com/assets/20208703/21561538/98986348-cea8-11e6-9563-bf791975b208.png)

Own server
Import your own server more
costumes   sounds  backgrounds

**Comment by liam4** [comment]
You might want to take a look at the "Backgrounds", "Costumes", "Sounds", and "Examples" folders to get an idea of how you could do it. Make sure you don't miss the capital-case `COSTUMES`/`SOUNDS`/etc files in those folders!

Don't forget to give credit where due to the creators of the assets you upload, though!

**Comment by aidiken** [comment]
Thanks
