### ISSUE TITLE
Share button ignored if URL has query parameters

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1597]
E.g. load

http://snap.berkeley.edu/snapsource/snap.html?foo=bar

and click on Share button.

URL parameters needed to pass information into a JavaScript defined block.

Workaround is to share without the URL parameters and then add the parameters to the share URL.

**Comment by cycomachead** [comment]
Can you provide a little more detail about the exact steps you're taking?

In this case, if you use that link the Share button won't do anything because you haven't yet saved a project. Otherwise, as long as your query string doesn't contain a "#", things should work fine, though this isn't something we've heavily tested.

When I save the project (called "Empty") and then hit share, this is what I see:
http://snap.berkeley.edu/snapsource/snap.html?foo=bar#present:Username=cycomachead&ProjectName=Empty

**Comment by ToonTalk** [comment]
Hi. Thanks for the speedy response.

I just tried again.

1. Opened http://snap.berkeley.edu/snapsource/snap.html?foo=bar
2. Dragged out a block
3. Clicked Save
4. Entered a name
5. Clicked on Share - nothing happened
6. Clicked Save
7. Clicked Save As
8. Clicked on Share - nothing happened

I see now that the URL parameters were a red herring. The problem is that the Share button is enabled but does nothing even when no project is selected. I thought since I had typed the name of the project it would be shared when I clicked Share without selecting anything.

**Comment by cycomachead** [comment]
> I see now that the URL parameters were a red herring. The problem is that the Share button is enabled but does nothing even when no project is selected. I thought since I had typed the name of the project it would be shared when I clicked Share without selecting anything.

Ah yeah, this is a bug / confusion that's in a couple issues on Github. Share only does anything after you've saved a project and then go back to the Open dialog and click share. 

We should have a button called "Save and Share" in that menu sometime in the future. :)

**Comment by ToonTalk** [comment]
Also the Share button should appear disabled when no project is selected.

**Comment by cycomachead** [comment]
> Also the Share button should appear disabled when no project is selected.

Yep, that one is also on the list of improvements on Github. It's bothered me for quite a while... ;)
