### ISSUE TITLE
Question : use of a headless JS browser

### ISSUE THREAD

**Issue by show0k** [jmoenig/Snap--Build-Your-Own-Blocks#1600]
Hi,
Does anyone ever used a Headless browser to do tests of Snap! libraries ?
[PhantomJs](https://github.com/ariya/phantomjs) and [Selenium](https://github.com/SeleniumHQ/selenium) are two the most popular and are actively used for testing JS libraries.

I would like to use them to test Snap projects which interacts with hardware. To start part of Snap code I could use keyboard input (with the key hat block), but I would prefer use the green flag. 
Can I start the Snap project from the Js interpreter, in the same way than a user click in the green flag ?

**Comment by cycomachead** [comment]
If I forget to respond to this ping me in a week. (Traveling currently)

**Comment by micahcowan** [comment]
I believe you can hit `world.children[0].runScripts()` (where world is a WorldMorph instance). Of course, you'd still have to be certain to run `world.doOneCycle()` in a loop for the script to actually have the chance to do the things in the script. :)

**Comment by micahcowan** [comment]
(This assumes that `world's` first (only) child is an `IDE_Morph`.) Or, since the `IDE_Morph` instance running within the `WorldMorph` is something that `snap.html` sets up anyway, I suppose the test harness would just save a reference to the `IDE_Morph`, and just run `ide.runScripts()` directly (and then, yeah, the `world.doOneCycle()` loop).

**Comment by show0k** [comment]
Thanks @micahcowan `world.children[0].runScripts()` works great !
