### ISSUE TITLE
Atomicity of When Hat and script

### ISSUE THREAD

**Issue by Costor** [jmoenig/Snap--Build-Your-Own-Blocks#1602]
Probably Snap! was never meant to be strong in concurrency, nevertheless there is the WARP-block. 
As today, execution of the condition of a HAT and starting into its script is not atomic. 
Therefore it is possible that the condition of the HAT is true, but when execution of the script actually starts, it has already become false (because some other concurrent code has modified the environment).
I have exercised this already in simple settings with some 5 clones moving around concurrently.

There is a workaround: Use "forever" with a WARP and an IF-condition-Block within.  However, this is less ergonomic.

Is it possible to have a flag (ideally in any HAT) that says "execute condition, and if true, first statement atomically"? First statement of the script would then be a WARP, obviously.

Kind regards, Costor

**Comment by jmoenig** [comment]
Hmm... wow, this is interesting! Let me think about making your suggested behavior the default one. Thanks!

**Comment by jmoenig** [comment]
Okay, I can reproduce this:

![atomicity](https://cloud.githubusercontent.com/assets/2596285/21649340/9be1e086-d2a1-11e6-89ca-f3ca8747ac45.png)

here's the test case:

http://snap.berkeley.edu/run#cloud:Username=jens&ProjectName=atomicity%20bug

This is clearly wrong, and should be considered a bug.
Thank you for reporting it, great catch!

**Comment by jmoenig** [comment]
I just fixed this in the dev version. Check out the same test project in my current development environment:

http://snap.berkeley.edu/snapsource/dev#cloud:Username=jens&ProjectName=atomicity%20bug

The fix runs the script of the generic ```When``` hat block in the same atom as it evaluates the predicate, thus forming a protected step until the next yield. Note, you don't need a ```warp``` block, because by default scripts in Snap (and Scratch) are atomic until the first "timed" block (e.g. ```wait```, etc.) or the first loop.

I'll need to run a few tests to find out whether this fix potentially breaks anything or results in "hanging" projects. The issue with omitting yields in a green threaded environment such as Snap is that  long atomic steps can make the system unresponsive to user interaction. But this should be fine, it's actually the same strategy I'm using when evaluating the ```When I start as a clone``` hat block.

Again thanks!

**Comment by Costor** [comment]
I have run an even harsher test with two competing but exclusive Hats, and it worked fine in the dev version:

Click green flag and press key c:
http://snap.berkeley.edu/snapsource/dev/snap.html#cloud:Username=Costor&ProjectName=atomicity%20bug

I think it is completely ok that the current scheduling algorithm in Snap results in that one block is never executed (instead of randomly choosing the test order), see my comment in the code.

Counter check: in the current Snap version the bug occurs:
http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=Costor&ProjectName=atomicity%20bug

**Comment by jmoenig** [comment]
excellent test case and I agree with your reasoning! So, I think we can safely deploy the fix in next week's release. I've also conducted many more tests with all kinds of existing projects that use the generic WHEN hat block, and I couldn't find any unexpected behavior or regression issues. Looks like we fixed this one!
