### ISSUE TITLE
 Not correctly handling URL encoded strings

### ISSUE THREAD

**Issue by MathWizard49** [jmoenig/Snap--Build-Your-Own-Blocks#1606]
An ampersand is often encoded as %26 but the app rejects it
http://snap.berkeley.edu/snapsource/snap.html#present:Username=_________%26:ProjectName=First%20Alonzo%20game

**Comment by cycomachead** [comment]
Hmmm. What caused the URL to be encoded that way? I ask because I haven't seen this case before, though we can certainly fix the issue in Snap!

**Comment by MathWizard49** [comment]
Thanks for the quick reply!  Students are submitting links to our LMS, Schoology, for grading/accountability with their teachers.  The link is being stored and translated<http://www.w3schools.com/tags/ref_urlencode.asp> (we assume - have a ticket in with them as well), so when clicked the url populates in Snap! with %26 (or &amp;).  Since the app isn’t handling the %26 code as an &, the projects aren’t populating.  As mentioned, we have a ticket in with the LMS as well, but any support you can give from your end would also be greatly appreciated.

Thanks!
Chris

Christopher Bell
Gunn High School

On Jan 6, 2017, at 12:50 PM, Michael Ball <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm. What caused the URL to be encoded that way? I ask because I haven't seen this case before, though we can certainly fix the issue in Snap!

**Comment by cycomachead** [comment]
Cool, that makes sense! 
Generally URLs shouldn't be "re-encoded" but this shouldn't be a terrible case to handle. :)
If Jens is busy or can't get to this I'll try to take a look this weekend. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by micahcowan** [comment]
(Disclaimer: I'm a lurker, not a dev)

Actually, %26 isn't supposed to be treated as equivalent to & in query strings, as otherwise there's no way to represent & within a value (or key).

Hashtag query strings aren't technically standardized anywhere AFAIK, but I'd expect them to be treated the same as real query strings, for the same reasons.

That being said, being gracious and decoding them anyway wouldn't necessarily cause harm, except if usernames and project names, etc, could actually contain ampersands (no idea if that's the case), or if any values that might be given in the future could.

IMO, this should only be fixed by whoever generated such an URL, and probably not by Snap! (just my 2¢)

**Comment by brianharvey** [comment]
I agree, this is not our bug.  Characters such as =, #, and & that have syntactic meaning in URLs are supposed to be %-encoded only when you want to use them as ordinary characters, like \-protecting otherwise syntactic characters in shell commands.  Presumably your software is encoding our entire URL as data to their URL, which is fine, but they should decode it before letting you click on it.  If we treated %26 as syntactic, it would break our own ability to encode arbitrary strings in URLs.  I'm closing this.

**Comment by cycomachead** [comment]
I didn't test this but I thought that all we might need was to do decodeURIComponent on the URL hash.

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Yes, but that would be _introducing a bug!_  It would break ampersands in project names, which we would interpret as syntactic.  See my comment above.  The fact that it would be an easy bug to introduce is beside the point.
