### ISSUE TITLE
broadcast/receive drop-down menu always opens "message name" editor

### ISSUE THREAD

**Issue by micahcowan** [jmoenig/Snap--Build-Your-Own-Blocks#1608]
In the current master (ad9c4fe69c13bf43e1f95a5b68971f5f405c5c43), Clicking on the drop-down menu of a "broadcast _" command or "when I receive _" hat, instantly brings up the "Message name" editor dialog, even though "new..." wasn't selected.

That is, every time you click that pull down to select a message, the interface assumes the user wanted to create a new message type and opens that dialog, even if the user only intended to select an already-existing message type.

**Comment by jmoenig** [comment]
Yep, it's a showstopper glitch. I'll fix it asap (i.e. tomorrow ^^). Thanks a lot!

**Comment by jmoenig** [comment]
(there are also other things wrong this that drop-down, I noticed. I'll also fix those)

**Comment by jmoenig** [comment]
Okay, I now found out why I didn't do this in the first place: Making the hat Block and the attached script run in a single atom has two downsides: (1) You often don't see the script "light up" as it runs, because single-atom scripts terminate before they get a chance to highlight, and (2) error messages also don't get shown, because the system doesn't yield for them, i.e. again the script terminates before the error message gets a chance to be displayed.

A while ago Scratch has also changed to the single-atom scheduling, and users generally love it, but it's mostly for "power-user" features such as continuously drawing wire-frame models and raytracers. I think it's okay for the WHEN hat block to keep this "fix", but I'll have to think about how to better handle errors with this setup.

Hmm....

(it's not a "design" question, but a technical one)

**Comment by micahcowan** [comment]
Oh, I think maybe you meant to post that comment to #1602 instead?

**Comment by jmoenig** [comment]
Haha, yes, indeed! Well, I've also addressed it in a commit earlier today, hope that fixes it for good. Thanks!
