### ISSUE TITLE
Watcher not updated when list sharing memory with it is mutated

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1640]
![mutatebug1](https://cloud.githubusercontent.com/assets/3885074/22387373/1d14d9ba-e490-11e6-8ed7-48416acd2f39.png)
Then
![mutatebug2](https://cloud.githubusercontent.com/assets/3885074/22387382/289d1d24-e490-11e6-8d31-f518228ff7bb.png)

The value of garply is now {a, b, thing, d} but its watcher still says {a, b, c, d}.

Hiding and then showing garply doesn't fix it, but switching to table view does (and it stays fixed when you switch back to list view).

**Comment by jmoenig** [comment]
you can't have everything. You can manually update the watcher by deleting it (dragging it onto the palette) and re-showing it.

**Comment by jmoenig** [comment]
if this discussion starts to go on anywhere further I'm throwing out the linked list feature altogether. The performance issues are, in fact, way worse for linked lists than for arrayed ones, especially for larger linked lists. I think this is more of a nice parlor-trick feature in Snap than something to take for real. Don't get me wrong, I love the hybrid list feature, but the mere nature of hybrid-ness demands that you tolerate some uncertainties.

**Comment by micahcowan** [comment]
> The performance issues are, in fact, way worse for linked lists than for arrayed ones.

Doesn't that assertion depend pretty drastically on how the list is being used? For instance, common functional approaches to scanning-through-a-list would be orders of magnitude slower if linked lists disappeared (because they'd induce massive copying). As would several very useful techniques for constructing a large list and passing around several sublists of it, etc.

Which, in turn, would mean _Snap!_ could no longer realistically be used to teach FP, which would be a sore loss as that's one of the major things I love about _Snap!_.

(As an aside, I'll also point out that constructing a new list of 100 elements, say, from 1 to 100, is **hugely** "faster" for me in FP style than with a loop around "add item to list", primarily because the looped construction invokes the stepper, whereas no loop is involved with the FP version (just recursion). Obviously, a warp block eliminates this... but I doubt new users will understand that (I didn't, until I looked at the JS code).)

**Comment by brianharvey** [comment]
@micahcowan Yes, the issue about slowness of non-warped loops vs recursion came up at EDC when we were working on Unit 5, analysis of algorithms, because they got some counterintuitive timing results.  And the same thing came up on Piazza recently.  I'm hoping we can fix that just through better teacher education.

@jmoenig It's not much fun discussing things with you when you start threatening to remove features.  Maybe we can have a better discussion f2f next week.

**Comment by jmoenig** [comment]
Those example can't have been counterintuitive if you consider that Snap is a time-sharing multitasking system. 

Mutating a linked list turns it into an arrayed one.

**Comment by micahcowan** [comment]
> Those example can't have been counterintuitive if you consider that Snap is a time-sharing multitasking system.

Knowing that Snap is a time-sharing multitasking system doesn't mean one knows the details of how that system works, or where it hooks into. I submit that it would be (and was) very counterintuitive to someone who lacks that information (even though the manual does in fact mention it). At any rate, it's a case where linked list manipulation at least "appears" to be much faster than array. (The other two cases I mentioned, are cases of more legitimate faster-than-array behavior.)

> Mutating a linked list turns it into an arrayed one.

That doesn't seem to be related to anything being discussed in this thread? Certainly, none of the examples I mentioned involve mutation of a linked list.

**Comment by jmoenig** [comment]
The fact that mutating a linked list using the ```replace item``` block turns it into an arrayed one is the cause for the watcher behavior @brianharvey pointed out.

**Comment by brianharvey** [comment]
@jmoenig Can you explain that?  I see how making it arrayed is relevant to its value, but not to the watcher not keeping up.  Sorry.
