### ISSUE TITLE
Small moving problem

### ISSUE THREAD

**Issue by aidiken** [jmoenig/Snap--Build-Your-Own-Blocks#1649]
![09](https://cloud.githubusercontent.com/assets/20208703/22501005/c47f6c6e-e8a1-11e6-97f3-35e3b56d0034.png)
Why only the mouse in the number of places to move quickly？
![1](https://cloud.githubusercontent.com/assets/20208703/22501073/1525bb82-e8a2-11e6-947b-6d9ceb627fec.png)
Remove direction, why move in direction? How to remove memory?
![2208](https://cloud.githubusercontent.com/assets/20208703/22501200/b5337736-e8a2-11e6-9a3a-4096a8f183ac.png)
costumes Open very slowly

**Comment by brianharvey** [comment]
Are you asking three different questions?

**Comment by aidiken** [comment]
@brianharvey  Yes, thank you

**Comment by brianharvey** [comment]
Okay.
(1) I'm not sure I understand the question.  Are you asking why clicking in the input slot selects the full text of the input?  Or are you asking whether you can set the input value using the keyboard editor?  (Answer: yes.)
(2) I'm not sure I understand this one either.  The sprite always is pointing in some direction or other.  You can specify an absolute direction in degrees clockwise from north, or you can use the TURN blocks to change the direction by some amount.  But you can't ask for it to be pointing in no direction at all, because then MOVE wouldn't know which way to move!
(3) We are working on improving the loading of media thumbnails, and also on a hierarchical organization into categories so they don't all load at once.

**Comment by aidiken** [comment]
Thank you so much! Understand your meaning, we also in the test.
