### ISSUE TITLE
It would be nice to have something like Scratch's autostart=false

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1654]
When embedding a shared project on a web page one often doesn't want it to run the green flag after loading. Scratch solves this by adding ?autostart=false to the URL.

Also it would be nice if one can load a shared project and specify that one wants the scripts to be seen without requiring the user to press the double inward arrows icon.

**Comment by jmoenig** [comment]
there are url-switches like that for Snap, also. They are still somewhat undocumented, but they totally work:

* ```&noRun``` prevents the green flag event from being fired
* ```&editMode``` loads the project in edit mode instead of presentation mode
* ```&hideControls``` hides the meta-buttons, useful for presentation mode
* ```&noExitWarning``` lets the user quietly close the tab without having to confirm

Just add any (combination) of these switches to the url to get the desired behavior.
Hope that helps...

**Comment by ToonTalk** [comment]
Great, thanks. Works fine. 

Perhaps should be better documented.
