### ISSUE TITLE
Visibility of shared projects

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#1667]
Hello,
This issue is a request.
Should it be possible to have a list of our own shared project when you run such a url :
http://snap.berkeley.edu/snapsource/snap.html#present:Username=nathalierun ?

**Comment by bromagosa** [comment]
Hi @nathalierun!

As a matter of fact, this is one of the features that the new cloud offered by MioSoft will bring. It'll still be a while before it replaces the old one, but we're working hard on it :)

**Comment by nathalierun** [comment]
Ok, I'll be patient so.

But, I am working hard on a gallery where I want to present all the programs I've done on Snap! with the students, and I need to get a list of all my projects (shared or not) which are on your cloud.
This gallery will be like this but it will be specific to Snap!
https://nathalierun.net/lycee/piwigo/index.php?/category/92
How can I have a list of this projects ? (a text list)

**Comment by bromagosa** [comment]
Maybe you could somehow reuse this experiment: http://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=project%20list%20experiment

Click on the `call` block first, then wait for a couple of seconds and click on the `set [project images]` block next.

Instead of painting the thumbnail, you could get the name of the project and build the URL yourself :)

**Comment by nathalierun** [comment]
Thank you. But the problem is that I don't see how to do it.

**Comment by bromagosa** [comment]
Hi @nathalierun,

here's a block that returns all of your project names in a list: [project names.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/793239/project.names.zip).

Then it's just a matter of mapping each name into a new string, like this:

![image](https://cloud.githubusercontent.com/assets/1016697/23210328/5d8f463e-f8fd-11e6-9dbd-f1fed1a452c5.png)

In my case, it gives me this list:

![image](https://cloud.githubusercontent.com/assets/1016697/23210346/7a834bdc-f8fd-11e6-895c-aac45a22cfaf.png)

Of course, since we can't export lists (yet), you'll need to join these all into a new variable and export them:

![image](https://cloud.githubusercontent.com/assets/1016697/23210580/8a0ef924-f8fe-11e6-8e3a-e14c51f461f1.png)

And, finally, we can right click on the variable watcher and get URLs to all of our projects.

Hope it helped!

**Comment by nathalierun** [comment]
Of course !!!

**Comment by brianharvey** [comment]
Closing because this is definitely happening and we don't need a github issue about it.  :)
