### ISSUE TITLE
TOUCHING-Block does not work in Chrome with 'Downloaded Snap Source'

### ISSUE THREAD

**Issue by ThomasRoch** [jmoenig/Snap--Build-Your-Own-Blocks#1677]
Hello,
I downloaded the SNAP-Source 4.0.10 and opened SNAP.html in Chrome 56.0.2924.87 (64-bit) under Windows10.
I want to use the TOUCHING-Block, but I can NOT select a color (the little window with the colors open, but after clicking to a color of it nothing happens.).
This does not happen with the online-version of SNAP, and does not happen with the Downloaded version and Firefox. Unfortunately, I need the downloaded (offline) version, and with Firefox the application crashes to often.
I would be happy for a solution.
Thx
Thomas

**Comment by DarDoro** [comment]
Javascript applications loaded from local file system have restricted access to files. To overcome this limitations, pages should be served by local http server.
Or, as an ad'hoc solution, browser restrictions can be disabled with command line switch "--allow-file-access-from-files" (http://www.chrome-allow-file-access-from-file.com/windows.html).
For security reasons, separate profile should be used, for downloaded Snap. Chrome can be run with parameters.

 --allow-file-access-from-files   --user-data-dir=/path/to/snap_only_profile

Tested with Chrome 56.0.2924.87 @Windows 10

**Comment by jmoenig** [comment]
Hi @ThomasRoch, some browsers have irritating security considerations when working with canvas and svg elements and only allow certain operations if the page is served from an actual web server as opposed to opening the page locally.

That said, are you sure the ```touching (sprite)``` block doesn't work for you in the downloaded sources? Sprite collision detection does work fine for me in Chrome with the sources opened locally, i.e. not via a web server. What doesn't work is color collision detection (```touching (color)```). For this to work you'll have to serve Snap from a local web server, for example there is simple one included in Python that works fine. Alternatively, if online isn't an option for you, you can also download Snap4Arduino from http://snap4arduino.org/ which works offline.

I'm interested in your reasons for wanting to use Snap offline. Snap works much better online, because then you can save your projects to the cloud and share them across devices. Are you using Snap in school?

**Comment by ThomasRoch** [comment]
Dear DarDoro, thanks your solution workes fine. Now, I can use "Touching (color)" offline. I use:
`"C:\Program Files (x86)\Google\Chrome\Application\Chrome.exe" "M:\Snap\snap.html" --allow-file-access-from-files`

Dear Jens, your question about using Snap offline: If my students in school have an exam, they are offline and with no sharing folders.
As a proposal: For my normal classes (not in exam), all students work with my account. So its easy and fast to present a solution at the teachers computer to the whiteboard/beamer. The disadvantage: Some students copy the solution of the others.
I would be happy to have a teacher account: One administrator, lots of students accounts (it can be a fixed number of students, e.g. 30, with fixed random passwords) . Teacher can access all, students only there own files. And if in this mode export and import are disabled, everything is perfect even in exams. 
So if somebody has time to implement this ...

Just want to say in general the Snap is a great thing. 
Sincerely, Thomas
