### ISSUE TITLE
Built-in Costumes Not Editable?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#1681]
Some of the built-in costumes are no longer editable. You can't even flip them right to left.

This is a real problem because almost every single costume faces right, and if you can't flip them, then you can't make them have a conversation.

**Comment by jguille2** [comment]
Hi Mary,
Some costumes are svg files. These images have a better behaviour resizing them... but we can not edit with the bitmap editor.

You can check the "Rasterize SVGs" option (click _settings_ menu with _control key_ pressed to see this option) and then, all your costumes (the next importations) will be bitmaps and they'll be editable.
![rasterizeoption](https://cloud.githubusercontent.com/assets/2926315/23880268/e5d0f768-0852-11e7-9abc-103f8b9bd8b0.png)

Joan

**Comment by jmoenig** [comment]
in the dev version I've already added an indication to the costumes browser whether a particular costume is a vector costume or not. This will be in the next release, which - alas! - will take some time.

**Comment by maryfries** [comment]
Thanks. Whatever the solution is, it needs to be simple and intuitive for classrooms. No one is going to guess that you need to rasterize SVGs to get the images to work as expected. I suggest that all built-in images be of the same type and all be editable. The "indication" solution requires the user to understand what vector graphics are. As a quick fix, can we remove the vector-based images, or better yet, replace them all with rasterized versions (now, before the next big release)?

**Comment by jmoenig** [comment]
Aw, come on! Y'all wanted more costumes and *everybody* wants and loves vector costumes. I use them all the time and so do many of the people I met at SIGCSE. I've asked Brian to indicate in the filename whether a costume is SVG or not, especially for the Alonzo version. As I've said above, the next version will indicate whether a costume is a vector costume or not, and sometime we'll find the time to prioritize the already almost-done vector costume editor, but let's not roll back here. Vector costumes are important!

**Comment by jmoenig** [comment]
And, btw. *of course* you can flip any sprite, simply by making it only face left-right and then by turning it 180 degrees. Every Scratch kid knows that.

**Comment by EPaulG** [comment]
Are you saying we’re not up to “every Scratch kid”?

Jens, there may be reasons to resist, but this gets a bit insulting.  MANY of our teachers have never touched any computing language at all. The idea is to broaden participation. I cut you a great deal of slack about knowing about computer science.  Cut us a bit of slack about understanding kids, teachers, and schools.

**Comment by jmoenig** [comment]
naw, Paul, I'm sorry, that's not what I meant at all.

I'm encouraging you to let kids figure this out, as a challenge! In my - granted somewhat limited - experience this is almost a classic example of something that kids will "get" but that adults struggle with. And - just to be sure - I *want* some sort of indication of whether a costume is a "normal" (and thus, editable) one, or not. IMHO the many, many vector costumes were rushed into Snap in a hurry (I didn't even expect that since we hadn't talked about this before the sudden fact), and it took a great deal of effort to make *that* work at all. But now that I've gone to all the effort to make importing SVG costumes work I'd hate to take them out again, especially since many projects and project ideas now rely on them for smooth scaling.

Again - my with to Brian has been very explicit: Please indicate in the name of the Costume, whether it is a special one. This might not have to be the case in *every* SVG costume, but for the most common ones, especially the ones that are somewhere in the curriculum and in the examples, this should be quick and easy, since we only had a few.

**Comment by jmoenig** [comment]
I've also called for a prioritization of the vector costume editor, but - alas! - other urgent feature get in the way :-)

**Comment by jguille2** [comment]
Hi everybody,
Of course, svg support is an important feature for Snap!

@maryfries and @EPaulG , I understand your situation... but you are focused on a particular type of practice. I do not want to disparage this, but we have other Snap! users that are in the opposite side (they centered in resizing practices).

I think we have a simple solution! 
Assuming that most users need the editor for every sprite, until we have the vector costume editor, **we can change the default "Rasterize SVGs" option**. Then, the default behavior will be the requested (all bitmaps and all with editor) and users that need svg support (Supposedly more advanced) will change this option. Maybe we can change this "dev" option to a "normal" one. 

Joan

**Comment by EPaulG** [comment]
I’m not sure what you mean by “focused on a particular type of practice” and I assume the spell-checker mangled “they centered in resizing practices” so I don’t know what that means, either.

Our users are not stupid. They’re just new.  And presumably we want to be inviting to and usable by new users.  Snap makes “hard” things easy; it shouldn’t make easy things hard.

Your solution sounds good.  Frankly, I, too, have wanted vector graphics for stuff I’ve been trying to create for our new users.  SVG support is important to me, too.  And we also understand that Snap remains in development and we can hope that it continues that way for years!  But each step needs to let Snap remain the super-accessible super-high-ceiling language it aims to be.

**Comment by jguille2** [comment]
Hi @EPaulG,

Excuse my poor English (I will not blame the spell-checker).

I think we have ways to fix this easily, so we don't need a big discussion.

What I meant is that considerations such as "basic", "simple", "essential" ... depend on your itinerary (the practices presented to students). I know Snap practical implementations with children who do not use the editor in no time. And maybe, your "extra feature" consideration is "basic" for others. Therefore, the development must have a global perspective.

I share with you an [initial simple example](http://snap.berkeley.edu/snapsource/snap.html#present:Username=jguille2&ProjectName=travelling0) that shows those "practices based in resizing". It's only a first practice... and students build this and then adding more features. It's "the other side". If Snap! rasterizes the svg map, the result it's a disaster. Then, they need "the magic step" to perform their practice.

**Again I admit that the use of the editor is more massive and therefore I continue proposing changing the default option (until we have the vector costume editor).**

Joan

**Comment by cycomachead** [comment]
I second the suggestion to change the importing default, but at least in this case there is another option, that's easy and also worth considering.

We could simply rasterize (convert of GIF/JPG) the files in the `costumes/` directory. This would mean, that everything that "comes with" Snap<em>!</em> would be editable, but stuff from the web would still be saved as an SVG. This would at least keep some people happy who want to supply their own SVGs, but the default case would be pretty straightforward. This way we could provide smooth scaling as needed still (since the global setting is all or nothing).

**Comment by bromagosa** [comment]
What about we bump up the vector editor as a top priority? :confused: 

I also think it's one of the most important features we're missing. And, as it happens, we already have it! It's sitting in my HD waiting for me to have time to polish it up :)

Not having a vector editor is the issue here. Rasterizing all SVGs because we can't edit them would be like your record player scratching your records on purpose because it only has lo-fi speakers anyway.

**Comment by jmoenig** [comment]
Yes, I think bumping up the vector editor is the right thing. However, this only increases the pressure for an immediate solution, and that won't happen, because we won't be ready for a new release anytime soon (BTW, this also applies to the idea of making the "rasterize" dev option the default). What we need is a solution for the costumes we already have out there *now*, as this problem appears to be really pressing.

Therefore, again, my suggestion to @brianharvey : Can you make it so that those costumes that are used in the BJC curriculum (basically only a small subset of the "old" ones, right?) indicate in their names, which ones are the SVG versions and which ones are rasterized? I think what you did for the Alonzo costume makes that perfectly clear, and that should work for students as well as for teachers. @EPaulG , would that be a solution you could endorse while we'd be working on the Vector Editor and on tagging SVG costumes on the Snap! side?

**Comment by maryfries** [comment]
Is this related to #1682 ?

**Comment by maryfries** [comment]
Any thoughts on how to respond to teachers about this? We've just gotten a question: "With costume that already in snap you use to be able to edit the costume so that you are able to flip the image but now you can only set the center point. Does anyone know why this is or how we can flip a costume?"

What should we say? Thanks!

**Comment by jmoenig** [comment]
Well, as I've pointed out already, let's indicate in the costume names which ones special for now. And while we're at it, let's fix those horribly inflated ones to be normal size again. @brianharvey to the rescue!

**Comment by cycomachead** [comment]
The best first for names is implemented in the PR that fixes the costume importer to actually be usable. I'm at a loss as to how anyone currently has the patient to use the current version. :( 

The new version has a graphical indicator for SVG files which seems much more clear than just trying to read an extension. File extensions are unfriendly. 

I think we could get that released soon. 

Otherwise, can we just (for the time being) turn all the SVGs into JPGs for the built in costumes? 

We can also add a message / warning to the costume editor until this is fixed. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
I'm sorry I've been so slow to respond to this.  I'm currently at 355 unread emails.

I'm not _against_ changing the costume names, but imho that that won't help at all.  Those users who understand why "vector" means "unflippable" already know how to solve the problem.  We could change the name "Alonzo (vector)" to "vector Alonzo" so that nobody will see it, if that would be useful.

Bernat, how much work are we talking about for the vector editor?  I'm really nervous about the way we (all of us, I'm not pointing at anyone in particular) keep promoting features from "important" to "most important," bumping the previous one.  This summer in Bordeaux we really need a summit meeting on this issue, but summer is still a long way off.

Jens, could you expand on why interim releases aren't possible?  I know OOP is coming soon, but I think the rest of us need it spelled out why one implies the other.  I'm not disagreeing; I just don't know how to think about this, how long we have to wait for non-OOP changes, etc.

IIRC, Postscript lets you specify a transformation matrix for the coordinate system.  Can you do that for an SVG?  In other words, is there a trivial way to flip a costume that we could put in its context menu without waiting for a full editor?

**Comment by cycomachead** [comment]
> IIRC, Postscript lets you specify a transformation matrix for the coordinate system. Can you do that for an SVG? In other words, is there a trivial way to flip a costume that we could put in its context menu without waiting for a full editor?

We could probably apply the same transforms we already do apply to SVGs but I think saving them might be tricky. I don't know for sure.

> Jens, could you expand on why interim releases aren't possible?

I'm not Jens, but from a technical perspective they are entirely possible. This is why version control exists...

**Comment by bromagosa** [comment]
> Bernat, how much work are we talking about for the vector editor?

We're probably talking about 10 to 20 hours work. The code is quite terrible, but all functionalities are there. It's just a matter of rolling up my sleeves and trying no to despair at things like `if (aBoolean == true) return true; else return false`. Yep, I didn't even make up this example!

> I'm really nervous about the way we (all of us, I'm not pointing at anyone in particular) keep promoting features from "important" to "most important," bumping the previous one. This summer in Bordeaux we really need a summit meeting on this issue, but summer is still a long way off.

Agreed. Why don't we set up a pre-conf Snap<i>!</i> summit?
