### ISSUE TITLE
Custom reporter block does not report

### ISSUE THREAD

**Issue by zeroturn** [jmoenig/Snap--Build-Your-Own-Blocks#1686]
I discovered what I consider to be a bug.  

**I realize that my trouble arose from "abusing the block editor as a clipboard for sprite-local blocks when switching to another one" (see issue # [795](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/795)), but I consider it a bug nonetheless**.

I still consider it a bug because copying and pasting from one similar block to another will be a common practice among users (I am sure) UNLESS the designers of SNAP! absolutely forbid it (Please don't.)

As can be seen in the screenshot below, when clicking on the "set area to HF2 ..." block, it reports an error (even though the area is correctly calculated, as is shown by the variable watcher for "area").

![no_report_error](https://cloud.githubusercontent.com/assets/13770851/24083859/30f9b096-0cad-11e7-85bb-e70e9d8aa45c.jpeg)

Searching through the posted issues on this site, I ran across #795 which indicated that I should not be copy-pasting code from one custom block to another.  I created this custom block by copy-pasting a similar custom block.  Therefore, I thought that the final reporter block of my custom block was not functioning _because_ I had copied it from another block.  I removed it and replaced it with a report block doing the same thing - and my script now runs without error.  See below:

![no_report_error2](https://cloud.githubusercontent.com/assets/13770851/24083881/ac0e87ac-0cad-11e7-9501-8fb983a33461.jpeg)

I have run into this problem before, and now I know how to fix it.  But, I do consider it a bug because it is "clutsy" to have to completely recreate a custom block that is very similar to one that already exists.  It just makes sense to take the similar block, copy and paste it and make the necessary changes.

I'll mention one other thing.  You might notice the "missing blocks" custom block on my screen shots.  This was necessary because the "mathematical operators" operator block (which includes square root function) was not loaded when I loaded this project (which was **copied** from the Codification Examples project).  I had to go to another project, export the math operators operator (along with a couple other missing operators) and then import them into this project as a custom block.  When I need a missing operator, I open that custom block for editing, copy the operator that I need and paste it into the script I am working on.  That is also "clutsy" and should not be necessary.

**Comment by brianharvey** [comment]
Wait, slow down.

Jens didn't say you can't copy code from one custom block to another.  We all do that all the time.  He said you can't copy code from a **sprite-local** custom block to **another sprite.**  When you created the custom block, did you click the little "for this sprite only" radio button?

Also, what do you mean the math operators block wasn't there?  It's a primitive!  Maybe you hid it?  You can hide it, but you can't delete it.

If you still have the original non-working version around, could you SET AREA TO 0 in that script before you SET AREA TO (HF2...) ?  Just to be sure the value in the variable isn't left over from a previous run.  Because you're right, it doesn't make sense to get the "reporter didn't report" error and also have AREA set.

Oh, is AREA a global variable, or a sprite-local variable?  (Same question as for HF2 above.)  Not that it should matter; if you can set it, you can read it.

Honestly, my best guess is that you didn't click APPLY in the block editor before calling HF2.

**Comment by zeroturn** [comment]
OK, I'm new to snap! (can you tell?)  The distinction between "sprite-local" and any other type of block escaped me (I believe I do know what that means, I just did not notice the distinction when I read the issue.)

> When you created the custom block, did you click the little "for this sprite only" radio button?

No.  I'm just experimenting with "codification" and writing "sprite-less" code.

> Also, what do you mean the math operators block wasn't there? It's a primitive! Maybe you hid it? You can hide it, but you can't delete it.

I have not hidden any blocks.  Please, load the _Codification Examples_ project from the cloud.  The advanced math operator is not there.  (Many blocks are not there - I assume they were not loaded because not considered necessary for "codification experiments.")

> If you still have the original non-working version around ...

I do not have the original non-working version but I have another version that was (and is) doing the same thing.  This one is named hf-1:

![no_report_error-hf-1a](https://cloud.githubusercontent.com/assets/13770851/24085343/56e8fbf2-0cc8-11e7-9055-72cde1e235c8.jpeg)

>could you SET AREA TO 0 in that script before you SET AREA TO (HF2...) ? Just to be sure the value in the variable isn't left over from a previous run.

Yes, as shown in the screenshot below, I can set area = 0, and I get the same error:

![no_report_error-hf-1b](https://cloud.githubusercontent.com/assets/13770851/24085371/e549dd4e-0cc8-11e7-94da-28460414b9a9.jpeg)

> Oh, is AREA a global variable, or a sprite-local variable?

Global.

> Honestly, my best guess is that you didn't click APPLY in the block editor before calling HF2

See below.  Same result after pressing "apply":

![no_report_error-hf-1c](https://cloud.githubusercontent.com/assets/13770851/24085372/f111914e-0cc8-11e7-81c7-d981e3f45d55.jpeg)

By the way, the calculation in this version is wrong.  The snap basic arithmetic operators put parentheses where I do not want them.  Please ignore the calculation errors in the above discussion.

Thanks.

**Comment by brianharvey** [comment]
>  The snap basic arithmetic operators put parentheses where I do not want them.

Let's start by clearing up the easy problems.  :-)  The grouping of operators depends on which operator you use as input to which other operator.  So, presumably we're talking about the computation of S, which should be (...+...)/2.  So first you construct the expression a+b+c (and since addition is commutative it doesn't matter which + block is inside which), and then you take that entire expression and put it in the left input slot of a / block.  Snap<i>!</i> doesn't determine the order of operations; you do!  We even alternate the coloring of nested same-category blocks so that you can see how they're grouped.

Next, about the math operators.  Primitives are always there; in that example project, the ones that don't have translations are hidden.  Go to the Operators palette, right-click on its grey background (not the scripting area next to it), and select "show primitives."

Finally, back to your original problem, if you defined your own transcendental operator block, _that_ must be the reporter that's not reporting!

Despite all this, I hope you're enjoying Snap<i>!</i>!

**Comment by zeroturn** [comment]
Sorry, I don't know what "if you defined your own transcendental operator block," means, so I don't think I did that.  So, the problem remains.  There is a bug in there somewhere because, as I demonstrated above, the problem persists.

I do enjoy Snap!

**Comment by brianharvey** [comment]
You said

> You might notice the "missing blocks" custom block on my screen shots. This was necessary because the "mathematical operators" operator block (which includes square root function) was not loaded when I loaded this project (which was copied from the Codification Examples project). I had to go to another project, export the math operators operator (along with a couple other missing operators) and then import them into this project as a custom block.

That's what I meant.  (_Transcendental functions_ are ones that aren't polynomials, such as square root.)  So if you are using a square root block that you imported from somewhere else -- Wait, actually, you _can't_ really import primitives from another project; I'm guessing what you did was import a block that calls the primitive ones from another project and then drag the sqrt block out of that import instead of out of the block palette.  But anyway, whatever you did, that's the source of the problem.  Maybe if I saw the actual project I could figure it out.

**Comment by zeroturn** [comment]
Ok. Thanks for the explanation. You are correct. I simply dragged the operators into a new custom block to facilitate their transfer to a different project. 

Since I now know that I can "unhide" the operators, I won't have to do that any more. 

Thanks for the guidance. 

RAB
