### ISSUE TITLE
Error in trying to save the project?

### ISSUE THREAD

**Issue by shiv248** [jmoenig/Snap--Build-Your-Own-Blocks#1698]
![image](https://cloud.githubusercontent.com/assets/15200155/24335723/cd617704-1237-11e7-9cfd-c11fcb5b381a.png)

Anyone know a fix, or a reason for this error? 
or like a workaround. This is my 4th time restarting and I don't want to restart again.

**Comment by micahcowan** [comment]
This message means there's a communication problem between your computer, and the server that hosts the save files (miosoft). It is sometimes down, even while the snap interface website itself is up. If it's happening a lot, then it might not be a problem with the saves server, but something else - perhaps local firewalls are preventing communication to that server.

However, this should _not_ mean that there's no hope except to restart. There are two other ways to save, besides saving to the cloud!

The most reliable way to save is actually to use the _Export project..._ menu selection, which will download the file into your default downloads directory. You can then use the _Import..._ menu selection in the future to load it back in.

Another means of saving, is to use the _Save as..._ menu selection, and then choose the browser icon instead of the cloud icon. This will save the project into your browser's local storage, and you can open the project again as long as you use the same browser on the same computer (and haven't erased all your private data in the meantime). I recommend using the export feature over this, as it really shouldn't be considered a permanent method of saving.

If you're using _Snap!_ from a computer that isn't yours, and you can't guarantee you'll be using the same computer or browser again, then perhaps you could use the export feature, and then copy the resulting `.xml` file onto a USB stick, or email it as an attachment to yourself (do **not** copy/paste the contents of the `.xml` file into an email, just attach it).
