### ISSUE TITLE
right click detection

### ISSUE THREAD

**Issue by UnnamedMinecrafter** [jmoenig/Snap--Build-Your-Own-Blocks#1725]
why not add right click detection to Snap! since the right click event of the stage is also triggered by ctrl + left click ?

**Comment by brianharvey** [comment]
"Right click event" is kind of a misnomer; the event is actually triggered by a "secondary click," an abstraction that is implemented in different ways in different contexts.  In the early days of the Mac, Apple didn't think people were smart enough to handle a two-button mouse, so they only had one way to click -- and so naturally software writers started inventing shift-click and control-click and shift-option-click and command-control-click, etc. :)  Also, since I'm left-handed, my secondary click is actually the left button!

So we just support the simplified view that primary click is for the project to use, and secondary click is for Snap<i>!</i> itself to use.

Having said that, there have been times in projects when I wanted the ability to send two different kinds of clicks to the project.  Maybe someday when things slow down we could have a tertiary-click event (middle button on three-button mice, left and right together on two-button mice, and we'd have to invent something on the Mac, maybe shift-click?).

**Comment by micahcowan** [comment]
FWIW, control-click is the canonical equivalent on Mac (and may even already trigger "secondary click" automatically).

I right-click/"secondary click" on my MacBook Pro all the time: on the track pad it's triggered by tapping with two fingers simultaneously. You can also trigger it by holding control and doing a normal tap or a true click.

**Comment by brianharvey** [comment]
... or you can set your preferences so that an actual right click on the trackpad does it, as I do.  :)
