### ISSUE TITLE
C-shaped Command

### ISSUE THREAD

**Issue by UnnamedMinecrafter** [jmoenig/Snap--Build-Your-Own-Blocks#1726]
this should act the same but it doesn't
![bug warp](https://cloud.githubusercontent.com/assets/27627336/25072224/74df6666-22c9-11e7-8840-b386bdc2e12e.png)
![bug custom](https://cloud.githubusercontent.com/assets/27627336/25072225/78a8ccb0-22c9-11e7-9550-6db2cba36f17.png)

**Comment by jmoenig** [comment]
C-shaped slots in *primitives* behave the same as in Scratch, i.e. they don't accept reporters.

**Comment by UnnamedMinecrafter** [comment]
but C-shaped does accept reporters when it is a custom block which it shouldn't

**Comment by jmoenig** [comment]
sure custom block C-slots should accept reporter drops. That how we define recursive command control structures.

**Comment by liam4** [comment]
Ah, but it's an inconsistency between user-defined blocks and primitives, which I'd think we'd like to avoid as much as possible, especially since it doesn't seem to rare the user would want to define non-recursive "primitives"..?

Ex., if I want to define a block like "while (foo) ..", it doesn't make much sense to accept a variable into "while (foo)" when you *don't* accept variables

**Comment by brianharvey** [comment]
I think this is partly a historical artifact.  Since Scratch doesn't have first class procedures, its C-shaped blocks are all implemented as special case kludges, and BYOB inherited that.  I'm not sure, though, why Jens chose to preserve that design in Snap<i>!</i>.
