### ISSUE TITLE
More clones created than expected

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap--Build-Your-Own-Blocks#1756]
Hi, it's probably something I don't understand, but I would expect this program to create 3 clones, but as you can see it creates 7, as if the clones continue the for loop in the same interation they were created. Is this intentional?
[http://snap.berkeley.edu/snapsource/snap.html#present:Username=davidgasku&ProjectName=cloned%20circles%20bug](url)

**Comment by nate-norgaard** [comment]
Ah, I think I figured it out. After the first clone, your anchor sprite has a part. When you clone the anchor sprite a second time, both the anchor and the part are cloned. I imagine this behavior is by design.
Check out my demo (create a clone of the Anchor sprite): http://snap.berkeley.edu/snapsource/snap.html#present:Username=nnorgaard&ProjectName=Cloning%20Anchor

**Comment by DavidGasku** [comment]
Thanks, that was it.
