### ISSUE TITLE
Constant Broadcast Locks Receivers

### ISSUE THREAD

**Issue by nate-norgaard** [jmoenig/Snap--Build-Your-Own-Blocks#1767]
Hi!

This might be by-design behavior but it's a little odd, so I thought I'd check.
Here's an example:
In a forever loop, we broadcast a message.
![image](https://user-images.githubusercontent.com/5818959/27247040-5850eba8-52aa-11e7-9ee1-25b720cfcaf4.png)
The receiver lights up but doesn't run until the broadcast loop stops.
![image](https://user-images.githubusercontent.com/5818959/27247069-8e5d50a6-52aa-11e7-89f0-3f9d69e57874.png)

My students got especially stuck when using the "when" block in similar cases, like this:
![image](https://user-images.githubusercontent.com/5818959/27247114-e6c38d28-52aa-11e7-8f07-a2c56935702b.png)
![image](https://user-images.githubusercontent.com/5818959/27247123-eee62bbe-52aa-11e7-8214-7310d450d9f8.png)
(Note how the "when" block doesn't light up even though "touching Enemy?" is true.)
In the above example, the receiver block doesn't get the chance to run until the "when" condition is false.

Is this behavior by-design? My first impression is that you ought to let the receiver block run at least up until its first yield between iterations of a single loop (the one that is broadcasting).

Thanks!

**Comment by jmoenig** [comment]
Good catch! Both examples should work as you expect if you turn the "thread safe scripts" setting on (in the gears menu). Yes, this is - sorta - intentional, but looking at your two examples it doesn't feel right at all. I'll investigate...

**Comment by jmoenig** [comment]
I think I've come with a solution that will make everyone happy. Hang on, while I'm testing it...

**Comment by jmoenig** [comment]
I've fixed this in the dev version:

0df5a7a7222966899a3b7afaddefe486f05d7c78

it will be part of the next official release. You can try it out here:

http://snap.berkeley.edu/snapsource/dev/snap.html

Basically what happened is this:

When Snap runs a script it first adds a "glowing" highlight to it, and *then* it executes the first block/step. In between adding the "glow" and starting to actually run the script Snap used to wait for the next frame, so the "glow" got a chance to show up on the display. This meant that there used to be a lapse of one display frame in between broadcasting a message and running the first step of the receiving scripts in the interest of letting the user see what's going on.

Inherited from (former versions of) Scratch is a somewhat funky reentrancy behavior when the same script is fired to run while it is already running. In this case Scratch and Snap *abort* the running script and restart it. This can be overridden by opting for "thread-safe scripts" in Snap. In normal execution mode constantly firing the same event within a ```forever``` loop always aborts and restarts the accordingly hatted scripts, but - since it took *two frames* to *start* the thread it aborted (and restarted) before ever getting a chance to actually execute the first step.

I've now changed the behavior to be more what Scratch 2.0 does: Now launching a thread - and highlighting it with a "glow" - happens all in a single frame. The downside of this is that the user does not get to *see* the "glow" highlight until *after* the first section of the receiving script has already completed. Oh well, there's a fine, very subtle, line between making program execution visible and semantic consistency.

**Comment by TopNiz** [comment]
What about broadcast and wait ?

**Comment by jmoenig** [comment]
@TopNiz yes, that certainly is a good workaround. Thanks!
