### ISSUE TITLE
How can a JavaScript-defined block call a user-defined reporter?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap--Build-Your-Own-Blocks#1791]
In my case there are no inputs so I just need to call the reporter within my JavaScript with no arguments.

**Comment by jmoenig** [comment]
I think ```invoke()``` should do that for you, but I'm assuming you've already tried that and it didn't work?

**Comment by cycomachead** [comment]
I think he's asking for what's the best was to access the actual block definition. I can look it up later, but you probably know off the top of your head. :) I've done this a couple different ways I'm not sure what's the best, to be honest.

**Comment by brianharvey** [comment]
INVOKE takes care of all that.  Declare the input in the Snap! wrapper to be type Reporter, pass it into the actual JS function, and do  "invoke(fun, new List([]));"  Or I guess if you're going to do it once, stash an empty list somewhere so you don't need a new one each time.

**Comment by cycomachead** [comment]
I understood the question to be how do you get to actual function object without passing it in as a parameter. 

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment]
Oh.  I guess I would put a ring around the block and call a helper function that calls the JS Function with it.  :-)

**Comment by cycomachead** [comment]
Ok, so here's what I have, and this is what we've done for the autograder.... Well mostly similar. I'm going to write this all out as best I can to make sure I understand it. Jens, please correct me if something is wrong, or there's an easier way...

Few things to know / assume.
1. You have the full block spec, like `label %text of size %n`
2. You have a variable `ide` which is the current IDE instance
3. `stage` is the stage. 😮 

I'm giving a generic solution that handles sprite local blocks, because we needed to support this for the autograder. Well, I don't know if we needed to, but we thought it'd be good to do....

We need to find a block by the spec, and then we need to create a "template Instance" which is passed to invoke. The Stage in Snap<em>!</em> keeps track of the global blocks, convenient in `stage.globalBlocks`. Each Sprite keeps track of it's own blocks in `sprite.customBlocks`. Oh, and there are stage local blocks, too! Can't forget those. 

Let's just look at the tools library, and if we do `stage.globalBlocks[0]` we'll get the label block, at least right now--that's because it's the first block in tools.xml. Except, we don't get the "real" label block, we get its definition. (A block can have a definition, and various instances of that block which can have different arguments and such.) 

Let's say we do this:
```
> label = stage.globalBlocks[0]
CustomBlockDefinition {body: Context, scripts: [], category: "pen", isGlobal: true, type: "command", …}
```
That definition has a property `spec`, but `label.spec` isn't what we want: `spec: "label %'text' of size %'size'"`. That includes the actual variable names. What we want is: `label.blockSpec()`, which is the right format.

Now that we have a spec, we can find the block we want. First, we'll get all blocks, and then get the specs. Lastly, we will need to call `templateInstance()` to get something we can pass into invoke.

```js
labelSpec = 'label %text of size %n'
allBlocks = ide.sprites.asArray().concat([stage]).map(item => item.customBlocks).reduce((a, b) => a.concat(b)).concat(stage.globalBlocks)
blockSpecs = allBlocks.map(block => block.blockSpec())
location = blockSpecs.indexOf(labelSpec)
blockTemplate = allBlocks[location].templateInstance()
invoke(blockTemplate, new List(['Hello', 12]), sprite)
```

And that should do it!

**Comment by brianharvey** [comment]
I'm so confused.  Why not just let Snap<i>!</i> find it for you?

**Comment by jmoenig** [comment]
Hmm... I gotta confess that I'm not quite getting it either... Maybe I don't understand the context of what you need to do, why you need to look up anything in the first place. Don't we already have all the block instances we need so we just invoke them? I must be missing something obvious here...

**Comment by cycomachead** [comment]
Well, if you can do that, sure, but I'm just assuming you're starting from having a block spec. There are cases where you can't just drag the block in as parameter. Maybe you're doing something dynamic, or just have a long list of names. Also based on #1402, I assumed he already knew about dragging a block and was trying to do something a different way.

In my case, that's the autograder, but if all you have is the name of a block, then how else do you find the block instance?

How do I go from "i know there's a block called XYZ" to actually invoking that block without searching through all the block specs?

**Comment by jmoenig** [comment]
Ah, I guess that's true. I would let students assign a ringified block instance to a specially named variable for the autograder, and just call that...

**Comment by cycomachead** [comment]
Well, if I were going to do that I'd just build a `GRADE` block that has a ring parameter, which I might do anyway - or add a button where they can do a block, but we've been trying to minimize any extra work students need to do. :)

**Comment by jmoenig** [comment]
Okay, I see. So, in the next release - which, different issue, is either 4.1 or perhaps better 5.0 - looking up a method by its blockspec is built-in, which will make it a lot easier for you. Can't wait to demo this :-)

**Comment by cycomachead** [comment]
Oh that will be cool! 👍 😀 I'm really excited for the conference!

P.S. Isn't this what dev branch is for. :P

**Comment by jmoenig** [comment]
oh yes, that's *in* the dev branch, but not yet documented in any way :)

**Comment by cycomachead** [comment]
oh cool, I haven't checked closely, but I'll go looking soon.

**Comment by ToonTalk** [comment]
Sorry I wasn't clearer but Michael understood my question. 

Let me explain my use case. My JavaScript blocks require API keys to work. Each block could require users to pass the keys in but that is really awkward. So there are several global variables that contain keys and when a block needs a key it reads the value of the appropriate global variable.

This works fine until I export blocks and then encounter #1133 that global variables aren't exported.

So I thought a workaround would be that the keys are inside a user-defined reporter. The JavaScript blocks would then call that reporter to get the keys much as Michael suggests. (I got Michael's code working after replacing stage with ide.stage. Thanks Michael.)

While this is slightly clumsier for the user (editing reporters instead of setting a global variable) it is cleaner in that it relies upon the global name space of blocks instead of cluttering up the user's program with global variables.

**Comment by brianharvey** [comment]
I am only an egg, but why not this:
![key1](https://user-images.githubusercontent.com/3885074/27974039-0feaaad0-6311-11e7-9596-650a7e875873.png)
or, for that matter, just this:
![key2](https://user-images.githubusercontent.com/3885074/27974049-19e61948-6311-11e7-8172-443ff7f28a05.png)

**Comment by ToonTalk** [comment]
Yes, that would work. But that would mean that children would need to pass the key in for every time they use an instance of the block. Consider

![image](https://user-images.githubusercontent.com/2138696/27983751-ab723342-63bb-11e7-8880-a1e177bf65f6.png)

Speech recognition is built into Chrome so no key is needed. But for other browsers it is needed. But the main problem is that passing a key to Listen just clutters up one's program. It is an implementation detail that keys are needed (sometimes).

**Comment by brianharvey** [comment]
No, no!  The _user_ doesn't pass in the key.  The user calls my grey do-something-with-api-key block, which of course you give a name like LISTEN that doesn't say anything about keys.  The key is _built into the block,_ which is part of your library.

**Comment by ToonTalk** [comment]
That would be nice (and a good solution) but these keys (from Google, Microsoft, IBM, (and soon Amazon)) have a limited free quota (e.g. a few hundred queries a day or a few thousand a month). So my plan was to share projects without keys. When run without keys an alert pops up offering to take users to a page explaining how to get API keys and to paste them into the appropriate reporter.

But I guess LISTEN doesn't need to have the key but instead similar to your suggestion it could call a reporter that either pops up this dialog or after editing by the user returns a key. This is better than having the JavaScript behind LISTEN calling the user's key reporter.

I do worry about the user sharing his/her project and finding his key exhausted. At least they can be warned. It just occurred to me that a warning could be generated if a key is provided and the current logged in user is different from the user name in the URL. It could say something like "It is impolite to use someone else's key without permission. If you don't have permission here's how to get a key of our own..."

**Comment by brianharvey** [comment]
If you stored the key in a global variable, you could mark that variable as "transient" which means that its value isn't saved when the project is saved.  Maybe that works only if the value is a list, but it could be a one-item list containing the key.

@jmoenig Being able to use key-controlled semi-public APIs is probably important enough so that we should consider a mechanism to store keys with the user's settings preferences.

**Comment by ToonTalk** [comment]
What's the interface for marking variables as transient? Problem is that one wants the values saved if the project isn't shared.

Storing them in user's settings would be great.

**Comment by brianharvey** [comment]
You right-click the variable's orange block in the palette and there's a checkbox.
