### ISSUE TITLE
Dot painting

### ISSUE THREAD

**Issue by LeadToGold** [jmoenig/Snap--Build-Your-Own-Blocks#1908]
In Scratch you can paint a single dot on the screen with a pen down followed by pen up.
It looks like Snap 'pen down'  just sets the 'isDown' property. 

Sean Mitchell

**Comment by jguille2** [comment]
Yes, this is commented (and still open) in #209 and #605.

We must fix this behavior (changing to Scratch behavior or closing these issues).

For me, current behavior is fine.
  - To paint is to move the pen from A to B
  - We can consider that the pen is not marking without  movement. For example, with _pen down_, if I drag and drop the sprite to another place (movement in the air without painting), the destination place will not be market (neither in Scratch). Then it seems a consistent behavior.
  - Anyway, the other alternatives are not bad either.
    - We can consider _pen down_ stamps the pen.

        or
    - Initially, the proposal of _move 0 steps_ to mark a point did not seem very natural for me... but I think it's not bad either.
 
        And I insist that current behavior is fine!

Joan

**Comment by LeadToGold** [comment]
OK.  I have read the comments in the other issues.
I still believe the functionality, while not 'pure', is convenient and accessible to new programmers. I have used it frequently in my Scratch curriculum.
Is there a place for discussion of the high level goals of Snap w.r.t. expected level of students, convenience vs. integrity?

Sean

**Comment by brianharvey** [comment]
One place for that kind of discussion would be here:
https://scratch.mit.edu/discuss/topic/219464

About dropping dots:  I have to be an old curmudgeon about this.  The issue was discussed and _settled_ decades ago in the design of Logo.  If the pen is not in XOR mode (not currently available in Scratch or in Snap<i>!</i>), then moving N steps horizontally or vertically should draw N+1 pixels, so as to include both endpoints of the motion path.  (Iirc, in XOR mode you omit the starting point, because in the usual case of several MOVEs with the pen down, maybe with turns in between, you end up seeing the vertices twice, once as a starting point and once as an ending point.  And you don't want to end up not drawing the vertices at all!)  Drawing N+1 pixels will sometimes be redundant, but it's safe about always doing the right thing.

I mean, think about an actual pen on paper!  When you put the pen down and then move it, both endpoints get ink.

Again, both Scratch and Snap<i>!</i> behave wrongly about this.  But once you have the correct N+1 behavior, just set N to zero and you'll see that MOVE 0 STEPS is the right way to place a dot at the pen position.

Just doing it on PENDOWN is wrong once you have procedures in your language, which Scratch didn't when they decided on that behavior.  So, suppose you want to draw a complicated picture and you do it using three helper procedures, so your script is
PEN DOWN
FOO
BAR
GARPLY
PEN UP

Now it so happens that FOO starts with a PEN UP because it wants to move before the first line it draws.  It's clear, I think, that the user doesn't want to leave a dot at a point FOO _isn't_ going to draw on.

The pre-2.0 Scratch didn't have to worry about this, because it didn't have custom blocks, so the only way for a PEN DOWN to be temporally followed by a PEN UP was for the PEN DOWN to be _lexically_ followed by the PEN UP, i.e., the two pen blocks are physically adjacent in the script, and in that case it's reasonable to suppose that the user meant to draw a dot.  But once the PEN UP can be buried inside a custom block, that supposition no longer applies.

Someday I'll convince Jens about this.  :-)

**Comment by SanderTacker** [comment]
I faced this annoying problem with my students today and found this thread afterwards.

Above, Brian is referring to an actual pen to explain the behavior of "move ... steps". 
> I mean, think about an actual pen on paper! When you put the pen down and then move it, both endpoints get ink.
Consequently, you should add: With an actual pen, you also get a dot on the paper, if you do "pen down, pen up".

Thoug I understand your explanation, it is really not intuitive to use a "move 0 steps" block to get a dot.
Couldn't Brians FOO example simply be solved by not setting the pen down before calling FOO since FOO drops the pen up and down itself anyway? 

I don't get the point in doing literally nothing when setting the pen down since an actual pen does something. I really want to open the case again to avoid contra-intuitive bevaviour.

Reading Brains last line, I suppose Jens agrees with me on that? :)

**Comment by jmoenig** [comment]
I did implement the "move 0 steps" mechanism to get a dot the size of the pen size in the meantime. I'm really pleased with its behavior, what do you think?

**Comment by brianharvey** [comment]
Beautiful!

By the way, I forgot to put penerase and penreverse on the list of things-Brian-wants that I gave you...
