### ISSUE TITLE
Help text for "set pen color" is wrong.

### ISSUE THREAD

**Issue by YPIMG** [jmoenig/Snap--Build-Your-Own-Blocks#1921]
The "Set pen color to ###" block takes a number between 0 and 100, but the help popup says it takes a number between 0 and at least 170.

**Comment by jguille2** [comment]
Yes @YPIMG ,
current color range is 0-100 without wraping (red is also for values<0 and values>100)

We know help info is not right (is reflecting Scratch behavior). I'm sorry... but it has not been modified quickly because we have some open discussion about color changes.

You can see other open issues (like [this](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/1659))... and I think you can close this one, because this is already documented (and pending) it these others.
