### ISSUE TITLE
WHEN I RECEIVE [ANY MESSAGE] crashes

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap--Build-Your-Own-Blocks#1925]
Load this:

http://snap.berkeley.edu/snapsource/snap.html#open:http://bjc.edc.org/bjc-r/prog/4-internet/U4L3-TCP.xml#present

Click the green flag, click a sprite, type any text.  Snap! 4.1 freezes.  It works in 4.0 (.../stable/...).

The problem seems to be in the WHEN I RECEIVE block, not in the script under it.

**Comment by jmoenig** [comment]
The culprit is the "SEND" block that uses the JS-code we kludged up in order to send a message to a particular sprite rather than broadcast it to all. We have since introduced and "official" kludge for this that doesn't require a JS-function :-) (broadcast a 2-item list whose first item is the message and the second one the receiver). When I change the SEND block to that and adjust the READ INTERNET DATA block to check whether it receives a list everthing seems to work fine again.

Here's the project with these two changes:

http://snap.berkeley.edu/run#present:Username=jens&ProjectName=Y3U4L3-TCP&editMode
