### ISSUE TITLE
Passing empty strings to new blocks

### ISSUE THREAD

**Issue by divnak** [jmoenig/Snap--Build-Your-Own-Blocks#1972]
Hi! I was playing a little with Snap! and must say it is amazing, and I only have compliments for the code (excelent naming of variables and functions and everything).

However, I have encountered some weird bug that I don't know how to solve... 

I made a block, lets call it "myTestBlock" that receives a string (programmaticaly in my version of objects.js). The idea was to display a warning when user inputs wrong value. It works perfectly except when user enters **empty string**, and:
1) "myTestBlock" is in block "run"
2) stepping is on

Stepping is supposed to stop when wrong value is detected, but when user enters empty string, that empty string seems to remain forever...

Here is the code:

`// Motion
myTestBlock: {
    only: SpriteMorph,
    type: 'command',
    category: 'motion',
    spec: 'get some string: %s',
    defaults: ["something"]
},
//.....

if (cat === 'motion') {
    blocks.push(block('myTestBlock'));
//.....

SpriteMorph.prototype.myTestBlock = function (text) {
  console.log(text);
  if (text == '')
    throw new Error('Empty string not allowed!');
}
`
This is ok:
![bug-01-ok](https://user-images.githubusercontent.com/32951113/34341747-60dc0b64-e99e-11e7-8048-ec096d6f821c.PNG)

And then you try to enter something, and it is stuck on empty:
![bug-02-notok](https://user-images.githubusercontent.com/32951113/34341748-64be0386-e99e-11e7-9657-eef1e5d871f7.PNG)

The only way to change it is to delete the block and put it back again or programmaticaly call resetIde. I can't figure it out... Other strings don't get "stuck", just empty and just in stepping mode.

**Comment by divnak** [comment]
I forgot to mention, I downloaded latest version from this site on 24. december.2017

**Comment by jguille2** [comment]
Oh Yes! We have a bug here.
### To reproduce it easier
In _Visible Stepping_ mode, do
![runmove](https://user-images.githubusercontent.com/2926315/34356084-ece53472-ea3a-11e7-9339-bb1c36303d7f.png)
Then, the _move_ block (this instance) will only use the inputs passed from a parent (for example, a _run_) block. So, `move [20] steps`  will not run, but `run [move [ ] steps] with inputs [20]` will be still ok.

### Origin
The problem is we have set the property _input.bindingID_ to this slot, and then, [it does not evaluate](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/5785e0016683f808e61a325ad879be02fb2f7a9d/threads.js#L848) its own value.

And this is caused because in _VisualStepping_ mode [we use](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/5785e0016683f808e61a325ad879be02fb2f7a9d/threads.js#L992) the real dynamic expression, and not a _fullCopy_ of it.

### Solution?

Deleting _input.bindingID_ after its evaluation fixes this.
We can add a line to the [evaluateInput function](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/5785e0016683f808e61a325ad879be02fb2f7a9d/threads.js#L844)
``` javascript
    if (input.bindingID) {
        if (this.isCatchingErrors) {
            try {
                ans = this.context.variables.getVar(input.bindingID);
            } catch (error) {
                this.handleError(error, input);
            }
        } else {
            ans = this.context.variables.getVar(input.bindingID);
        }
        delete input.bindingID;
    } else {
```

### Notes
  - We have also [evaluateMultiSlot function](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/5785e0016683f808e61a325ad879be02fb2f7a9d/threads.js#L807) with this _input.bindingID_ reference but I have not needed to change it. I've tested with a _multiArgMorph_ but the evaluation is into each single input. But maybe is causing problems in other points... 

  - I think this fix is not affecting to _continuations_ or others processes. But I do not control all!! 

### Off Topic

Oh yes, we have not a forum (yet)  :smile:  :smile:  :smile:

So I want to wish a Merry Christmas and a happy 2018 year to the whole Snap! team  :santa: :christmas_tree: :gift:

Joan

**Comment by divnak** [comment]
Thank you very much for quick reply, although I am slow... :)
However, I am still interested in this issue and will try this.
Best wishes to the whole Snap! team, you are doing a great job...

**Comment by jmoenig** [comment]
Thank you, @jguille2 , for this brilliant analysis-cum-bugfix! It's so great to have you cover our backs!
