### ISSUE TITLE
Strange behaviour of "tell * to".

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap--Build-Your-Own-Blocks#1990]
According to my understanding, in the following project, both "tell to" blocks should do the same:

http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=davidgasku&ProjectName=bug

Is this a bug?

**Comment by jguille2** [comment]
Hi @DavidGasku,

There two differents things to comment:

- The first is that the TELL block expects actions (blocks) as second input. If you avoid the RUN blocks you'll get what you expected.
  Do
![tell2](https://user-images.githubusercontent.com/2926315/35147752-ff1d6726-fd0f-11e7-9e99-b2577e58a601.png)
  instead of
![tell1](https://user-images.githubusercontent.com/2926315/35147756-05fc24d8-fd10-11e7-9751-156d49e8ff91.png)

- The other thing is about what we are discussing into #1888. And it is about the difference between TELL and RUN [OF] blocks.
As your example shows, RUN block respect the "context" of the block. Here, the firs-class blocks feature is perfect. If you store the variable _p_ inside the other sprite, the result will be different. So, when you do [RUN p] you are running the action _p_ in its context.

Maybe you can close this issue and continue, if it's wanted, the discussion into #1888.

Joan

**Comment by DavidGasku** [comment]
Thanks for the great explanation. There are things that are not so intuitive, but I start to grasp the awesome potential of snap!
I would love a forum to discuss these things, snap deserves more than a thread in another software's forum.

**Comment by brianharvey** [comment]
@DavidGasku Yes, we're working on a better web site for Snap<i>!</i>.  This spring.
