### ISSUE TITLE
Please add "<=", ">=", and "!=" blocks to complement the current "<", ">", and "="

### ISSUE THREAD

**Issue by bjr1822** [jmoenig/Snap--Build-Your-Own-Blocks#2005]
Yes, these can be constructed with unnecessarily verbose combinations of the existing ones, but that takes up unnecessary space and creates unnecessary complexity for such basic concepts. I find myself in my projects just creating them as my own custom blocks over and over again because it's so annoying to do otherwise. It seems such a simple thing to make these native.

**Comment by bjr1822** [comment]
How did you type in the mathematical "<=" sign? Are you using html mark-up for that? That's a neat trick. That being said, C and every other language syntactically derived from it (and many that don't even) use <=, and >=, so I'm not sure using it is a bad idea to use those in a coding environment that is supposed to be teaching students how to code... Now to go and figure out how to export my own custom block library...

**Comment by towerofnix** [comment]
@bjr1822 C and most other languages also use "pop", while Snap<i>!</i> uses "delete last of list"; likewise, C uses "*" instead of "×". Snap<i>!</i> uses nicer (Unicode) symbols wherever it can, since the user never needs to type them - they're just draggable blocks!

**Comment by bjr1822** [comment]
I think I figured it out, but it is unfortunate that I only get a local XML file downloaded to store my library and that I can't save the library to my cloud storage and re-import it from the cloud. I guess I could import it to an empty project and then save that project, and for each new project, load that project up as the initial template, but that isn't in the spirit of having a custom block "library".

**Comment by bjr1822** [comment]
Not to be pedantic, but lists don't define pop. Only stacks define push/pop semantics. Most list implementations do use prepend, append, deleteBeginning, deleteEnd or similar concepts. But I don't really care what <= turns into when defined as a block, I was only was trying to express that the concept seemed useful to have and didn't know of an easier way to type the concept without jumping through hoops.

**Comment by brianharvey** [comment]
About Unicode symbols, I just go 
<img width="244" alt="firefox001" src="https://user-images.githubusercontent.com/3885074/35774170-c47da892-091c-11e8-9b59-c97ebea9ed69.png">
and that takes me to
<img width="590" alt="firefox002" src="https://user-images.githubusercontent.com/3885074/35774179-e8880052-091c-11e8-8c81-5a723df3fec9.png">
... but I don't know how if you're not using a Mac.  But I'm sure there's a way.

While we're being pedantic, doesn't "pop" return a value?  So it's different from "delete first" anyway.  (With linked lists, you want the most recent in front.)

But in any case, C is a _**horrible**_ starting point for defining the notation of a language, because, among other things, it totally misuses the equal sign to mean something that isn't the equality predicate.  This ensures that anyone who was actually paying attention in algebra class will be driven crazy.  If you have to have a punctuation character for assignment, it should be "←".  But a well-designed language will make the assignment statement as long and hard to type as possible, to encourage functional programming!

**Comment by bjr1822** [comment]
Returned values can be ignored, and most implementations of "remove" from a collection that I've encountered also return the value removed in case it is interesting to the caller. But lists actually have no implied semantics regarding where adding or removing happen. The traditional semantic overrides over the general collections are stack and queue. Stack is Last In, First Out. Queue is FIFO. Since lists have no implied semantics, it's up the developer to specify all insertion points and removal points explicitly.
I actually have no idea how to access a generalized Unicode map on Windows to be honest. Haven't really tried, and 2 minutes of poking around just now didn't turn up anything obvious. Now it's going to bug me until I figure it out :)

**Comment by brianharvey** [comment]
In Snap<i>!</i>, there are procedures that return values and other procedures that don't.  (If I were starting over, they'd all return values, but we inherited this structure from Scratch, and there are some pedagogic benefits to it.)  Procedures whose names are (or start with) imperative verbs generally are the kind that don't return values.

What you say about the semantics of lists sounds like it came from a CS 2 textbook, probably in Java.  :-)  There's actually no law saying what is or isn't the meaning of the word "list"; for those of us who grew up in Lisp, lists are singly linked structures, so it's faster to push and pop at the front -- O(1) time instead of O(n).  But I agree that a stack implementation should hide all that from its users.

Snap<i>!</i>'s list implementation is actually pretty complicated under the hood.  If you're doing imperative programming, using the list command blocks (add, delete, insert, replace), then what you get is actually a dynamic array.  If you're doing functional programming, with the list reporters (in front of, item 1 of, all but first of), then you get a linked list.  It means everything is as efficient as possible, as long as you don't switch back and forth for the same list.
