### ISSUE TITLE
Snap! site's title element says current version is 4.1, not 4.1.2

### ISSUE THREAD

**Issue by towerofnix** [jmoenig/Snap--Build-Your-Own-Blocks#2025]
Currently the title of s.b.e/index.html is `<title>Snap! (Build Your Own Blocks) 4.1</title>`. Do you intentionally omit the minor version? If not, it should be `... 4.1.2</title>`.

**Comment by brianharvey** [comment]
Yeah, that third number is even less-than-minor.  (Because BYOB 3 was so very different from BYOB 2, we got in the habit of calling even something huge like sprite inheritance a minor release, which was maybe wrong in principle.  At one point Jens wanted to call the new inheritance release 5.0, and I was against that only because I saw it as sort of fixing negative progress, getting us just back to where 3.1 was.) The third number isn't even a "minor version"; it's a maintenance release, in theory.

My current rule of thumb is that a minor release (e.g., 4.2) means "Brian has to redo the Reference Manual, and you users have to download the new one."  :)
