### ISSUE TITLE
Urgent: All the starter projects in BJC are failing to open.

### ISSUE THREAD

**Issue by selimtezel** [jmoenig/Snap--Build-Your-Own-Blocks#2029]
All the starter projects in BJC are failing to open.
The teachers and students are finding out this issue and it will affect many more classrooms in the coming days

For example:
On U5L2
http://bjc.edc.org/bjc-r/cur/programming/5-algorithms/2-simulation/2-flipping-a-coin.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc.html&novideo&noassignment

The starter project won’t open

https://snap.berkeley.edu/snapsource/snap.html#open:http://bjc.edc.org/bjc-r/prog/5-algorithms/U5L6-coinflip-student.xml

Please help!

**Comment by towerofnix** [comment]
It would appear to be that the Snap! site now forces HTTPS - so if you open http://snap.berkeley.edu, it automatically redirects you to https://snap.berkeley.edu. This is relevant because of the error that appears in the browser log:

> Blocked loading mixed active content “http://bjc.edc.org/bjc-r/prog/5-algorithms/U5L6-coinflip-student.xml”

So the problem is, it's trying to load a URL that starts with HTTP (bjc.edc.org) from an HTTPS site (s.b.e).

The problem does seem to be fixed if you replace `http` with `https`: https://snap.berkeley.edu/snapsource/snap.html#open:https://bjc.edc.org/bjc-r/prog/5-algorithms/U5L6-coinflip-student.xml

...However, it might be a pain to change every link in the course to use `https` instead of `http`.

Perhaps a useful change would be to make Snap<i>!</i> automatically try to load from `https` instead of `http`, if it's running on an `https` site?

**Comment by cycomachead** [comment]
This has been fixed.



> ...However, it might be a pain to change every link in the course to use https instead of http.

In this case not really, since it involves just upgrading the labs to be served over https by default. 
(And manually fixing the protocol would be 1 location, all those URLs are built by JS. :))



> Perhaps a useful change would be to make Snap! automatically try to load from https instead of http, if it's running on an https site?

We should consider doing this anyway...I'll make a PR.
