### ISSUE TITLE
Sprite-only blocks become obsolete blocks when opening project

### ISSUE THREAD

**Issue by DavidGasku** [jmoenig/Snap--Build-Your-Own-Blocks#2043]
https://snap.berkeley.edu/snapsource/snap.html#present:Username=davidgasku&ProjectName=bugObsoleteBlocks

In this project, two custom blocks use a local and a global predicate blocks.
The local one, always work fine, but the global one lose the local predicate when saving the project and reloading, showing obsolete block inside.

**Comment by dlnelson** [comment]
I tripped over this as well.  Here's a simplified scenario:
- I have a sprite, the artist, that's responsible for drawing things.  It has a sprite-local block that draws a square at the current location, "draw square internal".
- I want other sprites to be able to have the artist draw a square at some specified coordinates, so I create a global block "draw square at x; _ y: _" to act as an interface.  

I start with the following code for the global block:
![draw square at first try](https://user-images.githubusercontent.com/406791/38462897-cd2895bc-3aa2-11e8-89c8-6536cb9071e9.png)

That works fine, and I build up a large project around it (with lots of other internal blocks and global interface blocks).  Then I re-open the project:
![draw square sad](https://user-images.githubusercontent.com/406791/38462913-11e0bc3e-3aa3-11e8-905d-41323322129e.png)

Ah, but there's this thing:
![internal of sprite](https://user-images.githubusercontent.com/406791/38462932-5616b6ec-3aa3-11e8-9fc8-e032269d07b2.png)

So I can do:
![draw square split](https://user-images.githubusercontent.com/406791/38462940-6cee4cfe-3aa3-11e8-81b9-f7bb9644adef.png)

That works, but it requires switching into and out of the tell block.  Also, honestly, the real application is more complex, with more calls and internal reporters and various worker sprites, so having everything wrapped in run/ask is kind of a non-starter.

But there's this:
![draw square third try](https://user-images.githubusercontent.com/406791/38462973-d0ea811e-3aa3-11e8-8f3d-1067afa07685.png)

. . . and it doesn't work:
![draw square fail](https://user-images.githubusercontent.com/406791/38463020-1d626a6a-3aa5-11e8-9bce-d8366bdc9afe.png)

Is that a bug?

Here's another (minimal) example from when I was trying to construct a ring that would do what I wanted.  This works (when called from the local sprite):
![call works](https://user-images.githubusercontent.com/406791/38463005-ad0d1210-3aa4-11e8-8966-2ea00545644f.png)

But this doesn't:
![call fails](https://user-images.githubusercontent.com/406791/38463008-be1a54fa-3aa4-11e8-858a-e75e8a4a79b8.png)

I expected them to have the same behavior.

**Comment by jmoenig** [comment]
Thanks for these great explanations. There's (at least) one bug here that you've discovered, which is that Snap! should now allow you to put local blocks into the definition of global blocks. This was probably introduced recently with OOP. Fixing this will also fix the "obsolete" issue, but it won't address your issue of how to send OOP-like messages among sprites.

There are several ways in which you can have one sprite request another one to run a local function:
* Use the OF-reporter with the drop-down, that lets you discover local blocks af the receiver
* Use polymorphism: Make a local block for the sender and then use TELL or OF to "send" it to another one
* assign a local method to a sprite-local variable, then use the OF block to RUN/CALL that variable

Does that help?

**Comment by dlnelson** [comment]
Thanks Jens.  I assume you meant "_not_ allow".  I'd prefer not to notice my error several days later when I'm showing it to a class of students . . .

I've been using the sprite-local variable method you mentioned and just passing lots of context variables as arguments (that I otherwise would have taken from the enclosing environment).

I suppose the tricky part is binding the call-sites to their implementations.  It looks like that's done statically (whereas the OF blocks binds by name at run-time?).  I've noticed that, if I have a few hundred temporary clones around, hitting "Apply" after modifying a custom block sometimes hangs Snap for several (tens of) seconds.  I assume it's updating all the clones.

I think my takeaway is that ask/tell behave unexpectedly in the presence of local blocks and captured variables.  (And by unexpectedly, I mean that it's all quite reasonable, once I remember that's how they work.)

For concreteness (since I was posting simple examples for repro-steps), and so people can get a sense of what I'm doing (and laugh at my naivete), here's a more complete example of what I settled on:

I have a game loop that periodically runs this block:
![firenice2 script pic](https://user-images.githubusercontent.com/406791/38464705-0aa6ffcc-3ac7-11e8-9d7e-157a3ee7d885.png)

So, _animations_ are callables that advance the animation one frame and report <true> when they're "done," at which point they're removed from the list.

I'm using a sprite-local variable to hold the actual animation routine (although I have other animations that aren't tied to a particular sprite in this way):
![firenice2 script pic 1](https://user-images.githubusercontent.com/406791/38464726-4f5d1818-3ac7-11e8-9ade-23b1814a6c96.png)
![firenice2 script pic 5](https://user-images.githubusercontent.com/406791/38464848-34c90852-3ac9-11e8-80b0-11b4dd9d461c.png)

The sprite, itself, uses this declarative construct to define the animation (the "step" variable is sprite-local):
![firenice2 script pic 2](https://user-images.githubusercontent.com/406791/38464744-a14bf72a-3ac7-11e8-980a-4710bd218547.png)

And the "to animate" block is:
![firenice2 script pic 3](https://user-images.githubusercontent.com/406791/38464748-bb095d74-3ac7-11e8-9423-de2b159c96a7.png)

This is the simplest such animation, and I'll probably refactor some of the others as well.  For comparison, here's an old style animation:
![firenice2 script pic 4](https://user-images.githubusercontent.com/406791/38464817-7b87edcc-3ac8-11e8-9052-70accf656d29.png)

I had to pass the "evaporate OF block" like that, because if I move the OF block into the ring, I get the error above (a variable of name "" does not exist in this context).

**Comment by jmoenig** [comment]
Oh yes, you're right, of course, I did mean "not allow", duh! This is a regression bug, Snap! is supposed to scan the definition of a global block for instances of local blocks when you hit "OK" or "Apply" and pop up a message informing you that it won't accept the edit.

All custom block definitions are, in fact, late-bound in Snap, the tricky part is updating the block *appearances* when you edit a block, which includes identifying all the instances anywhere. That part can take up more time the more scripts a project has. 

Wow, you've done some sophisticated game-loop animation gimmicks. Lemme digest those...
