### ISSUE TITLE
Saved Snap! projects dissappearing

### ISSUE THREAD

**Issue by selimtezel** [jmoenig/Snap--Build-Your-Own-Blocks#2059]
At Piazza several teachers are indicating that their students' saved projects are opening empty.  Given the proximity of the Create Task due date for AP CSP, this is very alarming.  Please kindly help.
https://piazza.com/class/h8yx482idav52y?cid=1990

In case you cannot access Piazza here are the comments:
TaMarion Kelly
I have a student that has been working on his create project in snap but when he went to open it today the file is empty. Is there any reason that his file would be missing? He has been working on it for two weeks.  Any suggestions would be greatly appreciated.
Dane Hartman:
I have TWO students whose work has also vanished. Their project files still exist, but when the go to load them, they are empty. I have begun asking students to export all projects to .XML format at the end of each class period just in case this happens again. They are working on MacOS using Google Chrome.

**Comment by jguille2** [comment]
Hi @selimtezel,
I realize that the cloud change make us doubt and look if there is any problem. Let's see...

But also, I want to note (as a teacher for several years) that this problem is quite common. So the main hypothesis would be confusion of the student (and also other teachers): If I open Snap and I want to Open a project, but I'm wrong and I click to _Save_ option... Then, trying to open "projectName", I'm deleting (really replacing with an empty project) it.
Yes, I know there is a warning message that inform about this...  But I also know that it continues to happen anyway (of course, not only in Snap!)

**Comment by bromagosa** [comment]
@selimtezel There haven't been any substantial changes to the cloud server in the last two weeks. Can we get usernames and project names? This way we can check the latest modification dates and whether it's either a backend issue or user error.

**Comment by selimtezel** [comment]
I have just asked the teachers to share with us this information.  Thank you Bernat.

**Comment by cycomachead** [comment]
Closing as a result of other discussions.
