### ISSUE TITLE
Calling a Javascript function when Stop button clicked

### ISSUE THREAD

**Issue by Agnetha** [jmoenig/Snap--Build-Your-Own-Blocks#2090]
Hi,
  some idea in order to call a Javascript function when the Stop button was clicked. My desire is to send a "close()" for a remote websocket connection. Or, in other words: How I know when the script is terminated?

Thanks.

**Comment by brianharvey** [comment]
I can see why you want that, but it's a little scary because kids will use it to write unstoppable programs -- what they call an "attractive nuisance" like a swimming pool without a fence around it.

**Comment by Agnetha** [comment]
Hi brianharvey,
   Thank you very for the reply. I did not mean "unstoppable programs." I just want to detect when the script stops running so I also close my websocket connection. When the program stops, my global object stays alive in the global browser space, only being destroyed when the browser is closed.

**Comment by brianharvey** [comment]
I understand that that's what **you** want, but the feature you're suggesting would be used by other people for other purposes.

How did you create the websocket?  Sounds like it should be the job of the library you're using to clean up after itself.

Also, Snap<i>!</i> is an always-live programming environment.  Just because one script, or even all the scripts, have stopped doesn't mean that the user won't click on a sprite or type on the keyboard or otherwise start the program running again.  If you know that your websocket is used only by one script, then that script should close it when it ends.  You can catch errors; the stop button is (I think) the only thing you can't catch.

**Comment by cycomachead** [comment]
There is now a "when I am [stopped]" option, so calling a JS block should work there.
