### ISSUE TITLE
Feature Request (easy, low priority): letter ( ) of ( ) should have the same 1,last,random as item ( ) of ( )

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#2108]
This wouldn't change anyone's existing use of the block (hopefully), but people who would use it in the future would find it works just like item, giving easy access to the last letter in the sentence and a random element in the sentence...

**Comment by jmoenig** [comment]
Good idea, Dan, I like it. Assigning myself to it...

**Comment by jmoenig** [comment]
... of course, thinking about this some more, it's the old ```length of``` discussion all over. We could simply eliminate either the green reporters in the ```operators``` category or the red ones in ```lists```. Personally I'd opt (again) to get rid of the red list ones...

**Comment by brianharvey** [comment]
Nyet!  (I'm in the middle of a book about how the former soviet republics adapted to capitalism.)

Yes, a string is an array of characters, and so all the operations on strings have corresponding operations on arrays.

If we wanted _users_ to think of strings as arrays, we would invent another datatype Character to be used in blocks such as Unicode conversion.  How you arrange primitives depends on how you want users to think, not on how things are implemented.

But we want users to think about strings as _words_, or as _sentences_ if they're made of words.  That's why the green block is named LETTER rather than ITEM; the latter would be ambiguous, because it might mean the third letter or the third word.  (It also explains why LETTER and not CHARACTER.  We want users to think about words and sentences.)

In a perfect world, sentences would be implemented as lists of words.  But lists don't _look_ like sentences; they're these funny boxes with the items arranged vertically.  So we use strings for both words and sentences, and that's why we can't have generic functions FIRST and BUTFIRST that look at the type of their input to know whether to report the first letter or the first word.  We can't distinguish a word from a one-word-long sentence by looking at the internal type.  So we need FIRST LETTER and FIRST WORD functions.

In God's language, we have LIST-REF and STRING-REF as separate functions.

**Comment by jmoenig** [comment]
Okay, okay. OTOH I do believe that having fewer blocks would make Snap! less intimidating and more inviting, and one way to achieve this would be to let blocks handle closely related / similar operations on different data types, such as ```item / letter of``` and ```length of```. But I get it that you disagree and I'm not going to push it. How do you feel about Dan's original suggestion?

**Comment by brianharvey** [comment]
Sure, that's fine.

I don't agree, by the way, with your premise about fewer blocks = less intimidating, except when you take it to the extreme of hiding all but five primitives.  More palette categories might be less intimidating; that's why Scratch added an Events palette.  I think we should probably separate Objects from Control.  But in any case, I don't think eliminating two blocks would make any difference to intimidation.

**Comment by jmoenig** [comment]
Note to self: The only issue with this - otherwise easily implementable - feature is that it will require all the translations to be updated.

**Comment by jguille2** [comment]
Yes, we must also change 'letter %n of %s' to 'letter %idx of %s' in all translation files.

If you want to reassign this task... I can do it... and I said nothing more about _length of_ block :sunglasses:

**Comment by gdavid04** [comment]
> I think we should probably separate Objects from Control.

What about separating Other from Variables? I don't like that every Other block i add shows up in Variables. (i made an extension that allows creating categories and saves them with projects - and separates other from variables - it won't work with the latest source for some reason - it can be very useful when having lots of custom blocks)

**Comment by brianharvey** [comment]
I think we all agree in principle, but last time it came up, Jens was reluctant to take space away from the actual palettes.  Is that still the case, Jens?

**Comment by jguille2** [comment]
For me, current behavior is not bad. I'm happy with the 8 actual tabs.

But if you the "Other" tab (it's also fine for me), you have to propose also another tab (a new pair of tabs to fill the space). In [Snap4Arduino](http://snap4arduino.rocks/run/) we have the "Other tab" because we have also an "Arduino" tab.

Then, I guess your suggestion is to have a  new couple ("Lists" and "Other" tabs) and then, as Dan said, _tabs_ (10) will be equal to _categories_.

It's not a bad choice... but I'm not sure. (Maybe I'm becoming more conservative every day). The evaluation is not the same for a new design as for a new change. You have to think about the new users ... but also about the rest ... who will look for things where they were before.

**Comment by brianharvey** [comment]
"but also about the rest ... who will look for things where they were before."  I don't think this will be a problem, but if that's the concern, we could (perhaps only temporarily) leave the Variables palette as it is now, but _also_ have a Lists palette and an _Other_ palette (except that I think the latter should really show all custom blocks).

And I think while we're at it we should provide for two more ("provide for" includes choosing the two colors, so users get sensable choices) with user- or library-settable names, for things like "Arduino" or "Network" or "Graph."

**Comment by gdavid04** [comment]
So, custom categories? I made an extension that allows creating custom categories (and adds some categories and blocks). Sadly it breaks some things with the current source. (i had an older source and a few things need to be changed in the extension to work correctly with the latest source) I can send the current source code of my extension if you want. (and the source version / zip i had) Also, i totally support the idea! One more thing: it might make sense to put the lists tab right under the variables tab and put the other tab to the left, like this: (there's an objects tab in the image where the other tab should go)
![image](https://user-images.githubusercontent.com/25725819/41082206-cfa0c34a-6a2d-11e8-8ca7-810a04a2be7d.png)
The image was taken from my extension.
