### ISSUE TITLE
Problems with svg images generated by vector editor

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap--Build-Your-Own-Blocks#2125]
Hi!

I reported (by mail) some issues about new Vector Editor... but it was still in process. Now I see the _v4.2 RC_ commit and then, I want to report it here... and I will try to fix them (I think it was only a problem with svg headers).

- I can create svg costumes and edit svg costumes created by vector editor. But I can't edit other svgs (from Snap! library or imported)
- I can export svg costumes created, but the file is not right. I can't edit it with a desktop vector editor.
- And so, exported svg costumes can not be imported in other projects (they are not fine svgs).

I'll take a look about this. Do you have a date for the 4.2 release? Depending this date I'll try to check more things... and PR a Catalan language update.

**Comment by jmoenig** [comment]
Hi Joan, the first of these bullets (not being able to edit other svgs) makes sense, the second one doesn't, I guess. The way I understand it the current vector paint editor only simulates a few shapes, and if it comes across one it doesn't render itself, it'll simply throw an error and open the default "rotation center only" editor in Snap. 

Maybe @bromagosa can chime in on the second issue. I don't have any SVG editor installed on my laptop to check on this myself. Maybe I should ;-)

I wanted to release 4.2 early Monday morning our time (so it'll be up on Monday when schools in the U.S. start). But I guess one or two more days of testing won't do much harm, in case you need them,

Of course, we'll probably end up with a few minor follow-up releases for translation updates and small bug-fixes anyway, so that deadline isn't a very hard one.

Thanks!

**Comment by jguille2** [comment]
Ok,

I'll try to my best this weekend (it's difficult to find time,because here we are at the end of the course). But a quick fix will be easy... I see exported files have _ascii encoding references_ (like _%20_ instead _whitespaces_) and this is the first break.

Continue...

**Comment by jmoenig** [comment]
No rush, Joan. As I've pointed out earlier, we can always follow up with small maintenance releases...
