### ISSUE TITLE
French langage not available with tools 

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#2132]
Hello,

I noticed that french langage is not available with tools. 
It is a problem and someone noticed it reading an article I wrote on _Snap!_  here : 
http://irem.univ-reunion.fr/spip.php?article917

If I use only english langage, the script looks nice and homogeneus.
![snap-factoriellenonrecursif-en](https://user-images.githubusercontent.com/17542520/41955836-c4875710-79f2-11e8-8f09-4a2d5cd7a668.png)

And in french langage, there is a real problem of langage cohesion.
![snap-factoriellenonrecursif-fr](https://user-images.githubusercontent.com/17542520/41955866-dfeef71a-79f2-11e8-8a3a-0510106884c0.png)

In France, _Snap!_ makes its way step by step in the minds of the decision-makers at the "Conseil Supérieur des Programmes"
And I think that it is important to think about the cohesion of the choice of a langage.

To stay homogeneus, I think I am going to code in english with my students from the beginning of the next school year (which begins here in Reunion Island in august).

**Comment by jguille2** [comment]
Hi @nathalierun ,
All libraries blocks are custom blocks and we can not translate them by translation lang files.

But now you can translate them (and all your custom blocks) easily.

- Edit a custom block and, a right click over the block will open a dialog with the _translation_ option
![translate1](https://user-images.githubusercontent.com/2926315/41980181-270679a6-7a26-11e8-9c61-bd92a2b1b4fb.png)

- In some blocks, you will see the Deutsch translation. This is the way to add other translations
![translate2](https://user-images.githubusercontent.com/2926315/41979660-eb62d4b8-7a24-11e8-8ca1-91675118b0b0.png)
- I'll try to translate all libs into Catalan and submit a PR. The same could be done into French.
![translate3](https://user-images.githubusercontent.com/2926315/41979869-619375fc-7a25-11e8-9696-7bff05d454b9.png)

**Comment by nathalierun** [comment]
It is not possible with variables like 
![sans titre script pic](https://user-images.githubusercontent.com/17542520/41984100-db8bbc00-7a40-11e8-85f1-0a954f0f00eb.png)

**Comment by jguille2** [comment]
Hi @nathalierun 
- [a new clone of []] is a primitive (not a custom block). So, its translation must be on lang-fr.js
If you suggest a translation of this, I'll update the translation file. The same if you see other untranslated strings in Snap! IDE.

- A Pull Request is what we do to propose to Jens changes in the code.
Anyway, if you want to pass me the proposals, I'll do the changes. Yes! I will add Catalan and Spanish translations... and I'll add also your French proposals.

I ask you something like this:
- Snap IDE:
```javascript
a new clone of _
un nouveau clone de _
```
- Tools lib:
```javascript
empty? _
_ vide?

_ in front of _
_ en face de _ (or _ en tête de _)
```
... (all blocks from tools... and if you want to do the same with other libs...)

If you have time to do this, I'll do the rest.

**Comment by nathalierun** [comment]
Hi **@jguille2** 
Ok, I can try to do this.

First of all, I notice that some blocks don't appear in french when we choose the french langage in Snap IDE:
1. 
![somme suitearithmetique script pic 1](https://user-images.githubusercontent.com/17542520/42052416-d2113e36-7b1f-11e8-975a-c9ee0f1c66d1.png)
fr:jouer la note  _ pendant _ temps
2. 
![somme suitearithmetique script pic 2](https://user-images.githubusercontent.com/17542520/42052862-03c1977c-7b21-11e8-9188-8b4fbb284da9.png)
fr:étiquette _ d'une taille de _

- Tools lib:

```
tell _ to _
fr:dis à _ de _


ask _ for _
fr:demande à _ de _

if _ then _ else _
fr:si _ alors _ sinon _

for _ = _ to _ _
de:für _ = _ bis _ _
fr:pour _ allant de _ à _ _

catch _ _ 
fr:attrape _ _

throw _
fr:lance _

if _ do _ and pause all $pause-1-255-220-0
fr:si _ faire _ et mettre tout en pause $pause-1-255-220-0

join words _
fr:fusionne les mots _

list $arrowRight sentence _
fr:liste $arrowRight phrase _

sentence $arrowRight list _
fr:phrase $arrowRight liste _

word $arrowRight list _
fr:mot $arrowRight liste _

list $arrowRight word _
fr:liste $arrowRight mot _

map _ over _
fr:appliquer _ à _

empty? _
fr: _ vide?

keep items such that _ from _
fr:laisser les items tels que _ de _

combine with _ items of _
fr:combine avec _ les items de _

for each _ of _ _
fr:pour chaque _ de _ _

numbers from _ to _ 
fr:nombres de _ à _ 
```

I hope it is what you were waiting for...

For the other libraries, one by one...

**Comment by jguille2** [comment]
Ok @nathalierun,

Yes 'play note' block is a primitive just like 'a new clone'... and also 'tell' and 'ask' blocks. I'll update French laguage with these definitions.

And also I will work with tools library (for me is also better going one by one)

I'll post my results here...

Joan

**Comment by jguille2** [comment]
Hi @nathalierun ,
I've done the work! And the PR is just pulled in #2135. If it is ok ... you will find all your translations for the next release.

In the meantime, I post here the tools...
[tools.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2147389/tools.zip)

Then...
- You can use this tools.xml to import tools lib with your French translation running.
- You will see a updateFrench.xml file with only one block
![frenchblock](https://user-images.githubusercontent.com/2926315/42067895-12c740b4-7b49-11e8-96a0-fdaa2964dac4.png) This block adds the 4 fixes commented (play note, a new clone, tell and ask). This will be in Snap! soon... but maybe you want some screenshot...

**Comment by nathalierun** [comment]
Hi @jguille2,

Thank you for your efficiency. I don't need the sreenshots (I know those blocks).
But - I'm so sorry - I'm made a big misunderstanding for the translation of the block  `tell _ to _`. The right french expression for this must be : 
```
tell _ to _
fr:dis à _ d'exécuter _ 
```
Moreover, to be sure of my translation proposal, could you give simple exemple of : 
`ask _ for _`, `catch _ _`, `throw _`,

The french translation I gave for  `throw _` is also wrong. It may be  `fr:jette _` but I have to see a simple exemple to confirm this translation...
I'm sorry for this additional work.

**Comment by nathalierun** [comment]
I just found in the lang-fr.js (line 394) this : 
'play note %n for %n beats':
'jouer la note %n pour %n temps',
it is more compatible with this translation : 
'rest for %n beats':
'faire une pause pour %n temps', (line 392)

**Comment by brianharvey** [comment]
I think «lancer» is a better translation of "throw" than laisser.  As for "catch," when I ask Google about "throw and catch a ball" it suggests «attraper» even though whenever I hear that word I think about practical jokes.  As for "ask," it should really be something like «demander de _ la valeur de _».  Imho.

**Comment by brianharvey** [comment]
About music, I'm dubious about translating "beats" as «temps» because that makes it seem as if it expects a value in seconds.  Google suggests «battements».  Another candidate is «pulsations».  But I'm neither a musician nor a native French speaker.

**Comment by nathalierun** [comment]
My doubt came when I read in the help of `throw _ ` :  

> Exit early from a script

So I think that "lancer" alone is strange. It could be "lancer dehors", but it is ugly. That is why I prefer "laisse"... 

In french, we don't say «demander de _ la valeur de _» but «demander à _ la valeur de _».
So effectively, it would be better to say this : 
```
ask _ for _
fr:demande à _ la valeur de _

```

About music, I also prefer "pulsations" for "beats" . I can ask for a musician.

**Comment by nathalierun** [comment]
@brianharvey 
The strict translation of "throw" in french is "jette". So attrape/jette would be very clothe to catch/throw. 
But when I see this : 
![somme suitearithmetique script pic 3](https://user-images.githubusercontent.com/17542520/42078124-5ff90aa0-7b8c-11e8-8c46-3db38b1eade4.png)
I am sure that I understood the opposite (something that "stop the script") when I read the help : 
<img width="757" alt="capture d ecran 2018-06-29 a 11 07 24" src="https://user-images.githubusercontent.com/17542520/42078196-a505b36e-7b8c-11e8-91eb-9b3d51191496.png">

So you are right ! It is definitively "lance" the right word. So the translation could be 
`fr:quitte vers _`  ou `fr:quitte et lance _` for exemple.

**Comment by nathalierun** [comment]
@brianharvey 
On Wikipedia fr I see : 

> le beat (« battement ») est le temps de la mesure ou pulsation ;

So, the translation of "beat" can be either "temps" or "pulsation".

**Comment by nathalierun** [comment]
@jguille2 

So here are finally the changes to do, if @brianharvey agrees with them.

- Snap! IDE

```
play note _ for _ beats
fr:jouer la note _ pour _ temps

```
- Tools lib

```
tell _ to _
fr:dis à _ d'exécuter _ 

ask _ for _
fr:demande à _ la valeur de _

throw _
fr:quitte et lance _

keep items such that _ from_
fr: laisser les items tels que _ dans _ 

```

**Comment by jguille2** [comment]
Hi @nathalierun and @brianharvey,

I don't speak French but the problem, as in other translations (even in original Engish) is about: the right shortest strings, general expressions for blocks with inputs (maybe with different meanings) and a global vision (about the other blocks already translated).

Of course, @nathalierun, I will update the translation with your decisions (I see now your last post)... but I share my comments:

- PLAY NOTE
As you've said, the others blocks translate _beats_ to _temps_ and _tempo_ to _tempo_
So, for coherence, my proposal is 'jouer la note %note pour %n temps'. It was the original translation... and I've only update _%n_ for _%note_ fixing the issue.
This is just your last proposal :heavy_check_mark: 

- TELL and CALL
I understand the idea to change _de_ for _d'exécuter_ and _de_ for _la valeur de_. But I think this is not necessary. In fact, is the same in all languages. Sometimes (when you choose an action or a reporter) the preposition is not the best. But is shorter and clear. It is just "Tell somebody to do something" and "Ask somebody for someting"...where _do something_ is a command and _something_ is a reporter.
![frenchshort](https://user-images.githubusercontent.com/2926315/42084549-45caad9e-7b8e-11e8-870b-bbbd387b9137.png)
Here we have differences with your last proposal. Waiting for your decision... :question: 

- CATCH and THROW
I think we don't need to spend much time here (I did it for Catalan and Spanish and I didn't find better solutions). The real meaning of these blocks are not evidently... and even _catch_ and _throw_ are not showing clearly this meaning. If we want to improve this representation, maybe the discussion is about the blocks itself and its English representation. For me, the best solution is keep the same short idea.
So, for me _lance_ is fine. But _quitte et lance_ is also good. :question: 

- LAISSER
For me, "laisser les items tels que - de -" is better because in all Snap! is "de _list_" is used. But of course, I can change it to _dans_ here. :question: 

I wait for your decisions and I'll update our PR.

Joan

**Comment by nathalierun** [comment]
@jguille2 

- TELL and CALL
In this image : 
https://user-images.githubusercontent.com/2926315/42084549-45caad9e-7b8e-11e8-870b-bbbd387b9137.png
the first block is correct `fr:dis à _ de _` and is probably the correct translation.
but the second is not expressed in correct french langage at all.
In this context, it would be better to say `fr:demande à _ sa _` but I need other exemples to see if it fits. Because it could be :  `fr:demande à _ sa/son _` (according to the gender of the word : here, `position x` is feminine gender so `sa`is correct).

- CATCH and THROW
If the best solution is the shortest idea, `fr:lance _ ` is better.

- KEEP...
 `fr:laisser les items tels que _ de _` is it better ? Probably.
But, when I open the block, I see with this translation a sentence which seems strange to me : 
![somme suitearithmetique script pic 4](https://user-images.githubusercontent.com/17542520/42092226-2c727c7a-7bb9-11e8-9b4d-f7d36c2b9a57.png)
Could you give me a simple concrete exemple ?
But I think you are right and it is `... _ de _` the accurate translation.

**Comment by jguille2** [comment]
Hi @nathalierun ,

All your comments are affecting to many languages (as Spanish and Catalan) because we need maching (in gender and number) between adjectives and nouns.

And the only solution is to remove them from the blocks. And yes, if your input (maybe a name) has not its adjective... the sentence is poor... but now, we have this limitation to play with flexible constructions.

And the important thing (as I said) is to look at the whole Snap! translation, because we are only translating a few blocks... and this matter is already decided. For example:
We have many blocks ending with "de _list_". Depending of _list_, maybe the right form was _de_ or _des_, or _de l'_... but it's chosen a generic _de_.

I don't want to be heavy with this. My proposal is to keep current PR (with your initial proposals) because is fine. Later, you can consider all French translation and think about global changes (for example, if is better "dans _list_" than "de _list_"

Joan

**Comment by brianharvey** [comment]
I feel strange disagreeing with a native speaker about how to say something in French, but «laisser» just doesn't make sense for "keep" to me.  It sounds as if the non-matching items are deleted from the original list.  Rather, we are making a _new list_ containing a subset of the original items.  So how about «tenir»?  And I think that settles the «de» vs. «dans» question in favor of «de».

But I agree with Joan that it's hopeless to get gender correct; users get to name things, so whatever gender you pick is bound to be wrong some of the time.  Right now English-speaking feminists are inventing nongendered pronouns such as "herm" for "her/him"; is that happening in French too?  (Although in English gendered words apply only to people; all things are neuter.  So maybe the politics are different in French.)

**Comment by nathalierun** [comment]
@brianharvey 
So, let choose `garder` instead of `laisser`for the translation of keep.
Otherwise, I am not a feminist woman. I just love my native french language which is a very beautiful and refined language with many shades. I try to make the translation readable and meaningful.

@jguille2 @brianharvey 
Finally I suggest, if you all agree with me : 
- TELL and CALL
```
tell _ to _
fr:dis à _ de _
ask _ for _
fr:demande à _  sa _
```
(or for the last one `fr:demande à _ _` )


- CATCH and THROW
```
throw _
fr:lance _
```

- KEEP...
```
keep items such that _ from _
fr:garder les items tels que _ de _
```

**Comment by brianharvey** [comment]
I am just noticing that you translate "items" as «items».  Is that really the idiomatic choice?  Google suggests «éléments» for items in a list, or «articles» for items in a set.  «Items» is fine with me if you really picked it as the best choice rather than because you thought you couldn't change the technical term.

**Comment by nathalierun** [comment]
Please read https://fr.wiktionary.org/wiki/item
"Nom commun" section.
<img width="346" alt="capture d ecran 2018-06-30 a 09 18 19" src="https://user-images.githubusercontent.com/17542520/42121780-981e03a8-7c46-11e8-9b2c-30c9a9b1f820.png">

**Comment by brianharvey** [comment]
OK, got it.  Thanks.

**Comment by jguille2** [comment]
Hi @nathalierun ,

Changes (your last proposals) are submitted. I think you can close this issue... and keep looking at #2135 to track this feature.

Joan

**Comment by nathalierun** [comment]
Thank you @jguille2
