### ISSUE TITLE
Calling a ring reported from a block results in the ring itself.

### ISSUE THREAD

**Issue by kephas** [jmoenig/Snap--Build-Your-Own-Blocks#2136]
The following code tries calling reporter rings.  But if the ring is produced in a block, and that block is put directly in `call`, it won't get called but returned as-is.
![capture du 2018-07-01 00-52-41](https://user-images.githubusercontent.com/762421/42129685-1fb09b48-7ccc-11e8-9681-b54de21e6c18.png)
![capture du 2018-07-01 00-52-52](https://user-images.githubusercontent.com/762421/42129689-547c2fe0-7ccc-11e8-9994-2e3f00ee4f2e.png)
The problem seems to be when an input is typed as a reporter (which is the case in `call`). The only difference between `non-working caller` and `working caller` is that the first input of the latter is typed as any type.
![capture du 2018-07-01 01-14-08](https://user-images.githubusercontent.com/762421/42129726-ae48b52e-7ccd-11e8-8b15-009ef269e303.png)
Weirdly enough, the problem doesn't arise when it's not the outer reporter that's called but a variable containing it's reported value (as seen in the last example with input `40`).

**Comment by kephas** [comment]
https://snap.berkeley.edu/snapsource/snap.html#present:Username=kephasp&ProjectName=reporter%20bug

**Comment by brianharvey** [comment]
Your "non-working caller" block works fine.

As a debugging aid, I added an ASK block:
![nwc](https://user-images.githubusercontent.com/3885074/42129845-5c535f04-7c86-11e8-8e33-ff032c8f5fed.png)
And here's what I saw:
<img width="420" alt="nwc-say" src="https://user-images.githubusercontent.com/3885074/42129847-6c59373e-7c86-11e8-8426-f85bf84865f4.png">

Your block is being called with "reporter factory" (hereafter RF) itself as input.  You were expecting it to get the result of calling RF, but RF isn't called in your main script -- it has a ring around it, which prevents calling it.

So, to get your script to work the way you want it to, you have to right-click on RF in this instruction:
![bad](https://user-images.githubusercontent.com/3885074/42129873-1612f206-7c87-11e8-8a62-faee68f16c1a.png)
and select "unringify" from the menu:
![good](https://user-images.githubusercontent.com/3885074/42129876-2877a338-7c87-11e8-9330-8c5006484899.png)

Your fourth test works because there's no ring around RF in the SET block, so RF is actually called.

**Comment by Jonathan50** [comment]
In your example, the REPORTER FACTORY block itself is in a ring. Try right clicking on it and choosing unringify.

**Comment by brianharvey** [comment]
Hah, I beat you by 16 seconds.  :P
