### ISSUE TITLE
As of today I can't open any of my saved projects

### ISSUE THREAD

**Issue by DyslexicAwe** [jmoenig/Snap--Build-Your-Own-Blocks#2161]
I get this error message (in both Chrome and Firefox):

![1 08](https://user-images.githubusercontent.com/16387241/43510447-eddb3b56-9575-11e8-98b9-ae51da55db3d.png)

**Comment by brianharvey** [comment]
There was a planned outage of the Berkeley web servers.  Clearly I didn't post this in enough places, sorry.  It's supposed to be over at 9am Berkeley time.

That shouldn't affect the cloud, though, so I'm leaving this open.

**Comment by cycomachead** [comment]
Can you try again and see if things are working?

The server was meant as a backup, not as perfect replacement because we have no time to really do things the right ways... whoops. Hopefully things will be better for the next outage...or we'll just avoid them entirely. :) 

The issue was that the redirect wasn't pointing at the right source for project storage. I'll fix this for next time, but ideally by then everything will be smoother.
