### ISSUE TITLE
A block for exporting csv data

### ISSUE THREAD

**Issue by jonbus** [jmoenig/Snap--Build-Your-Own-Blocks#2198]
Dear colleagues:

Is there any way to use a "block" to export csv data to a file (mydata.txt) in the computer? I found this manual way
![irudia](https://user-images.githubusercontent.com/520114/44712546-52ce8680-aab1-11e8-8ee1-1f001e8f4bf8.png), but It would be more useful for as, to use an automatic way to save the data.

Thanks in advance,

Jon.

**Comment by KingDavid12** [comment]
@jonbus Unfortunately, there is no such block. This is because the browsers don't let Javascript code safe data to a file without user interaction in a way that can't be done with a custom block. What you could do, is set up super simple local server with CORS, and then send requests to the server, and have the server save the data to a file.

**Comment by jonbus** [comment]
@KingDavid12 Thank you again !!!
For this moment, we'll do it manually ;-) In the next version I'll consider to learn how to install a simple local server in a Pendrive (place we want to store the file.txt).

Jon.

**Comment by KingDavid12** [comment]
@jonbus Your welcome.
