### ISSUE TITLE
Problems with some svg costumes

### ISSUE THREAD

**Issue by nathalierun** [jmoenig/Snap--Build-Your-Own-Blocks#2209]
Hello,

When I import some svg pictures in the costume zone, they appear either empty or too big in the scene and the svg editor doesn't let me reduce the image.

<img width="1236" alt="capture d ecran 2018-09-15 a 18 44 24" src="https://user-images.githubusercontent.com/17542520/45587730-e9f16600-b91a-11e8-854d-7a58066cf560.png">

<img width="1102" alt="capture d ecran 2018-09-15 a 18 42 46" src="https://user-images.githubusercontent.com/17542520/45587682-240e3800-b91a-11e8-801c-c4c697b060fd.png">

It happens with this svg file for example :
https://www.dropbox.com/s/y4eqn7bf0ce1160/PrismaticNetwork1.svg?dl=0
I have the problem on Firefox Quantum 62.0, Safari 11.1.2, Google Chrome Version 69.0.3497.92 on MAc OSX El Capitan (10.11.6). Those browsers seems to be updated browsers.
I have the same problem on Linux (Ubuntu 16.04) with Firefox and Chromium.

The same image is troncated here :
<img width="1231" alt="capture d ecran 2018-09-15 a 18 43 09" src="https://user-images.githubusercontent.com/17542520/45587677-15c01c00-b91a-11e8-8dfb-c5fd34e6e4c7.png">

With those files, they appears as empty costumes :
https://www.dropbox.com/s/q0pfrgbsoq5uxmf/Cute-Cartoon-Butterfly.svg?dl=0
https://www.dropbox.com/s/gkcwgc056fmimhh/PrismaticNetwork5.svg?dl=0

<img width="575" alt="capture d ecran 2018-09-15 a 18 57 25" src="https://user-images.githubusercontent.com/17542520/45587666-deea0600-b919-11e8-9398-10f35cd3d596.png">

My students have also the same problem with a lot of svg images downloaded on http://openclipart.com . (images are either empty, either too big and we cannot resize them).
We work with Snap! 4.2.1.4
Does anybody have the same problem ? 
Thank you in advance for your answer

**Comment by jguille2** [comment]
Hi @nathalierun ,

The problem is with the svg files.

1. Note 0.
Snap vector editor can only edit _svg files_ created into Snap! (with the same vector editor). Other _svg files_ can't be edited.

2. Fist image.
The image is too big. You can use
![resizeblock](https://user-images.githubusercontent.com/2926315/45591156-24bec280-b94a-11e8-90e1-7db4bf11eed8.png)
And you will see the whole image.

    Other alternative... Edit the _svg file_ (out of Snap, with a vector editor like Inkscape) and change the size. First, you must change _document properties_ to select a maller size, and after this, resize the image and keep it into the document area.

3. Second image (the image that it is not appearing)
Here the problem is that the image is out of the document view.
You can edit the _svg file_ (with a vector editor soft) an, in "document properties" you will see there are a displacement (x and y of the visualitzation box). Set this values (x and y) to 0. And after this, do the same that above (the image is also too big).

Here I post the changes into the two images I've tested.
[images.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/2386159/images.zip)

Joan

**Comment by nathalierun** [comment]
I got it ! Thank's a lot, Joan ! I close the issue.
