### ISSUE TITLE
Snap! on Retina Displays

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#383]
This definitely isn't a priority, but there's a problem on retina displays, at least the 15" Macbook Pro (Safari, sometimes Chrome but not FF) where there's 'shadows' of blocks being shown after they're being dragged.

See this video, since that's the easiest. The 'ghosting' disappears when you click the background. 
https://drive.google.com/file/d/0Bz4PCnNknwnkSWpMeWFqVXlrbHc/edit?usp=sharing

Also, Snap is kinda blurry (especially text) on Retina screens. Is there anyway we could tweak morphic so that it uses the full pixel area of the screen? Currently it seems to be just  using the half pixel size that's then scaled up.

**Comment by bl-nero** [comment]
The simple trick with scaling just one canvas element won't help, because every element creates its own canvas, and it has to be scaled accordingly. If you set the scale on the outermost canvas, then you'll end up drawing zoomed versions of low-resolution images on the same canvas, with equally poor results.

There are two solutions:

1. As a temporary stop-gap measure, I'd suggest using the image-rendering CSS property, partially supported by the latest versions of Chrome and FF. It can just display the pixelated, low-resolution UI. I'll prepare a pull request this week.

2. A full solution would be more challenging, since it would require resizing all of the canvas elements. I'm making some experiments now.

**Comment by cycomachead** [comment]
@bl-nero Yeah, I tried that a bit, but didn't get super far. Feel free to poke around #628

**Comment by bl-nero** [comment]
I managed to get a bit further; the only thing left behind is SymbolMorph. Here's my approach: create every canvas in the device resolution, and immediately apply the scaling factor. However, it's tricky: whenever you refer to canvas' width or height properties, you get device-pixel values, so you need to carefully scale these things. Also, whenever you change canvas dimensions, you need to apply scaling again, because the transformation matrix is reset.

I'm considering using a simple canvas polyfill that would just hijack read and write access to the width and height properties; that would solve our problems for now, and prevent them from reappearing in the future. An alternative solution is to write a couple of utility functions for converting dimensions, but then you risk forgetting about using them.

Here's what I've got now:

<img width="1440" alt="screen shot 2015-10-12 at 09 57 00" src="https://cloud.githubusercontent.com/assets/9391503/10423537/a47bca64-70c7-11e5-93d4-64677a6f410f.png">

**Comment by bb010g** [comment]
@bl-nero Could you put up your fork? I'd like to take a look at the code to see how those alternatives would work.

**Comment by bl-nero** [comment]
@bb010g Here you go: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/compare/master...bl-nero:retina-hd

It's a work in progress, a bit unstructured (this is why I thought about the polyfill approach) and incomplete. It also doesn't take `backingStorePixelRatio` into consideration like #628 does.

**Comment by cycomachead** [comment]
Thanks for sharing! I'll take a look when I can as well!

I'm excited by this! That looks great so far! :)

**Comment by cycomachead** [comment]
I do have one comment (so far :stuck_out_tongue:) before this is pulled, but
`window.devicePixelRatio` doesn't work in IE 9 or 10. We probably want a wrapper around that which in older browsers.

**Comment by bb010g** [comment]
Any particular reason why there's so much commented out code? That should be cleaned if it serves no more use before merging.

**Comment by bl-nero** [comment]
As I said, it's a WIP, incomplete, full of trial-and-error attempts, and
not intended to be merged.

On Tue, Oct 13, 2015, 06:38 Brayden <notifications@github.com> wrote:

> Any particular reason why there's so much commented out code? That should
> be cleaned if it serves no more use before merging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/383#issuecomment-147599525>
> .
>
-- 
--
Bartosz Leper

**Comment by bl-nero** [comment]
I almost got it working perfectly; the only bug I'm seeing is that the sprite editor doesn't work correctly, but everything else displays as it should.

Meanwhile, could someone somehow assign the bug to me?

**Comment by bl-nero** [comment]
OK, so here's the new approach: https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/compare/master...bl-nero:retina-polyfill. This branch includes some code from #628 and the retina polyfill for all features used by the Snap! UI (this most probably doesn't mean that every single feature of Canvas has been covered; only these really used).

Known bugs (as of now):

* UI gets wonky when dragging the window between a built-in retina display and a non-retina external monitor (this is a really, really small issue).
* When saving a project with sprites drawn or imported on retina, they get saved on a high-dpi canvas. As a result, when importing the project on a non-retina version, they are twice as big. This issue is a blocker, and I think I'm gonna solve it by whitelisting sprite images as low-dpi images. However, I'd like to know what you think about it: **should I only make scripts low-dpi, or should I also make the entire stage pixelized?** Any input would be appreciated.

**Comment by bl-nero** [comment]
Victory! (I hope so). I finally made it work, and now Snap! looks beautifully on my Mac:

![liss](https://cloud.githubusercontent.com/assets/9391503/11768051/63c32302-a1c1-11e5-947f-b1417c984e38.png)

**Comment by show0k** [comment]
@bl-nero I tried your branch retina-polyfill on a Ubuntu based distribution and all is not perfect.
On chromium/Chrome if I zoom on the page, the size of some shaders is not changed and it looks very weired (150% zoom):
![capture du 2015-12-13 22 29 47](https://cloud.githubusercontent.com/assets/3891499/11769525/984a3368-a1e9-11e5-93c6-ed3a8c21189b.png)

**Comment by bl-nero** [comment]
Ouch, that looks bad. Thanks! I'll look into it.

On Sun, Dec 13, 2015, 22:40 Théo Segonds <notifications@github.com> wrote:

> @bl-nero <https://github.com/bl-nero> I tried your branch retina-polyfill
> on a Ubuntu based distribution and all is not perfect.
> On chromium/Chrome if I zoom on the page, the size of some shaders is not
> changed and it looks very weired (150% zoom):
> [image: capture du 2015-12-13 22 29 47]
> <https://cloud.githubusercontent.com/assets/3891499/11769525/984a3368-a1e9-11e5-93c6-ed3a8c21189b.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/383#issuecomment-164300438>
> .
>
-- 
--
Bartosz Leper

**Comment by cycomachead** [comment]
Tidy-ing issues up! So far retina display support is working! :)
