### ISSUE TITLE
Radical Idea / Question: Run and Launch Names?

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#687]
So, this is something I've been thinking about after looking over student questions from the past semester, and this one came up a bit more frequently than I expected.

The distinction between when and launch is confusing to most students. Usually, i describe the blocks as this:

    launch is like a "run" block, while run is really like a "run and wait" block. 

Students usually seem to get this distinction because it follows the rest of the Scratch paradigm of "x" and "x and wait" blocks. I'd propose changing the names, but that would actually be a bit problematic because the meaning of "run" would be even more confusing for existing users.

Is there possibly a better word than "launch" or some other way of describing the blocks?

**Comment by brianharvey** [comment]
I say, "LAUNCH is analogous to BROADCAST; RUN is analogous to BROADCAST AND WAIT."  My intuition about what "run" means is different from yours: it means EVAL.  The metaphor of LAUNCH is that the new task takes off from the dock and goes its own way, while the landlubbers carry on with their lives.  :-)

PS:  Consistency is the hobgoblin of small minds.  Otherwise GLIDE would be called GLIDE AND WAIT!

**Comment by cycomachead** [comment]
> I say, "LAUNCH is analogous to BROADCAST; RUN is analogous to BROADCAST AND WAIT." My intuition about what "run" means is different from yours: it means EVAL. The metaphor of LAUNCH is that the new task takes off from the dock and goes its own way, while the landlubbers carry on with their lives. :-)

Well, yeah, I usually compare to broadcast as well. 

I mean, I'd just as easily call launch "fork"...but that doesn't mean much to normal people.
