### ISSUE TITLE
Nesting sprites

### ISSUE THREAD

**Issue by geaplanet** [jmoenig/Snap--Build-Your-Own-Blocks#694]
The manual makes references to nesting sprites, but it isn't clear how to do it. Could anyone explain a little bit this?

Thanks in advance.

**Comment by brianharvey** [comment]
Grab a sprite from the sprite corral and drag it onto another sprite on the stage.  You'll see a gold halo when you're in the right place.  Then let go.  The first sprite (from the corral) is now attached to the second (on the stage), so moving the latter also moves the former (but not vice versa).

**Comment by sburech** [comment]
I find the sprite body in costumes but I am unable to find the sprite parts for the arm that is used on page 8 of the manual.

**Comment by brianharvey** [comment]
Right, you're supposed to make it yourself in the paint editor.  Duplicate the body costume, then edit the copy to erase all but the arm.

**Comment by sburech** [comment]
Hi Brian,
Thank you.  I am sure I will have many more stupid questions as I explore SNAP! (although I did not see a reference to the paint editor on page 8).  My grandson’s school is about to initiate SNAP! and I wanted to get a heads-up, since they are asking for volunteers.  
And, by any chance are you the author of the three volumes “Computer Science” LOGO style” that my oldest daughter tackled years ago when she won her local science fair with a demonstration of AI on the Apple IIe.
Stan Burech

> On May 22, 2016, at 12:03 PM, Brian Harvey <notifications@github.com> wrote:
> 
> Right, you're supposed to make it yourself in the paint editor. Duplicate the body costume, then edit the copy to erase all but the arm.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/694#issuecomment-220849705>

I would appreciate confirmation of receipt of this email by you.

**Comment by brianharvey** [comment]
Yup, that's me!

This is why it's labelled "Reference Manual" rather than "Tutorial."  It does have some tutorial examples, but I haven't even tried to ensure that you can start at zero and work through it in order.  But I'll add a footnote next revision.  (I know we need a tutorial, too, but one thing at a time.)

**Comment by sburech** [comment]
Well, I am honored to meet you.  I may be wrong, but it seems to me that many of the LOGO procedures I have retained from years ago can easily be rewritten to operate on SNAP! once I master the SNAP! graphics interface.
Stan

> On May 22, 2016, at 12:47 PM, Brian Harvey <notifications@github.com> wrote:
> 
> Yup, that's me!
> 
> This is why it's labelled "Reference Manual" rather than "Tutorial." It does have some tutorial examples, but I haven't even tried to ensure that you can start at zero and work through it in order. But I'll add a footnote next revision. (I know we need a tutorial, too, but one thing at a time.)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/694#issuecomment-220852095>

I would appreciate confirmation of receipt of this email by you.

**Comment by brianharvey** [comment]
Thank you!

Yes, part of the initial motivation for Snap<i>!</i> was that there were things I could do in Logo that I couldn't do in Scratch.  Scratch has been hugely successful, partly because of their brilliant design and partly because of the Internet, but in certain ways it was a (deliberate) step backwards, and I wanted to have my cake and eat it too.

**Comment by sburech** [comment]
Attached below is the letter that was sent out from my grandson’s school that led me to find SNAP!  I assume SNAP! like LOGO is interpretive, not compiled, so programming errors are easily uncovered.  I look forward to the tutorial when you get around to writing it.  The BASIS students are very sharp and will tire quickly of cute graphics unless they can be shown that neat procedures in SNAP! can be created.  Most of them are familiar with Scratch, but like my grandson, has moved onto other interests.  (He is fiddling around with video editing in Final Cut Pro, Motion and After Effects.)
Stan


> On May 22, 2016, at 1:03 PM, Brian Harvey <notifications@github.com> wrote:
> 
> Thank you!
> 
> Yes, part of the initial motivation for Snap! was that there were things I could do in Logo that I couldn't do in Scratch. Scratch has been hugely successful, partly because of their brilliant design and partly because of the Internet, but in certain ways it was a (deliberate) step backwards, and I wanted to have my cake and eat it too.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/694#issuecomment-220852993>

I would appreciate confirmation of receipt of this email by you.

**Comment by brianharvey** [comment]
No attachment?

You might look at the curriculum at http://bjc.edc.org for ideas.
