### ISSUE TITLE
switching to another sprite/the stage while editing a sprite-local block may make it appear in the other sprite's palette

### ISSUE THREAD

**Issue by jmoenig** [jmoenig/Snap--Build-Your-Own-Blocks#724]
from Piazza.

**Comment by luis140219** [comment]
Jens, I have a solution. Please remove the Block Editor like the Scratch Team did in Scratch 2.0. You can still create blocks via Make a block. The trick is putting the block scripts in the scripting area and NOT in the block editor area. This turns things more organised and less obscure.

**Comment by jmoenig** [comment]
Okay, I can't reproduce this bug anymore. Dunno how I thought I did.

@luis140219 nope, editing blocks in a separate space is crucial for abstraction. Scratch 2.0 doesn't even have global blocks ("for all sprites"), and also doesn't let you build your own control structure blocks. Also, Scratch 2.0 doesn't have mutable parameters and not even temporary variables ("Script variables"). Personally I think that Scratch's "Define" hat block in the same scripting area as the other event scripts is a mistake, because it confounds Scratch "scripts", which are highlighted as they are executed with "definitions", which aren't.

**Comment by jmoenig** [comment]
opening a new issue for the right bug...

**Comment by luis140219** [comment]
Yeah, Jens, with the removal of "Make a Variable" from the Block Editor, now "script variables" is a very useful alternative. Your dialog "Make a Block" should create a "Define" script instead of a Block Editor. The block can even be a reporter or a predicate. This is a crucial extension to Scratch ("Make a Block" with choice of category and shape, the Script Variables block, the List block, first class procedures).
