### ISSUE TITLE
Is there a way to load and display an image?

### ISSUE THREAD

**Issue by sharived** [jmoenig/Snap--Build-Your-Own-Blocks#729]
I want to be able to display an image (.tiff file) on the fly and can't figure out how to do this.  Is this possible?

**Comment by cycomachead** [comment]
> I want to be able to display an image (.tiff file) on the fly and can't figure out how to do this. Is this possible?

By on the fly, do you mean via a HTTP request? Basically, the only real way to handle images like this is via Costumes, or stage backgrounds, which are just called `Costume` in code.

Currently, you can't do this with the native HTTP block, but it should definitely be possible with `JS Function` You should be able to get the raw image data, and create a new `canvas` element with that data and then add a costume. Here's a similar example to get you started:
https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/blob/master/objects.js#L5380-L5388

Converting a an already existing image (as a data blob) to a canvas can sometimes be weird depending on the context. This is one way to do it:
http://h3manth.com/content/convert-any-image-html5-canvas

**Comment by sharived** [comment]
Thanks for the quick response.  For more clarification, I have the image and want to display it.  It seems like the stage background would be the right place.  I haven't used js as of yet.  I assume I put the code in this block.

![image](https://cloud.githubusercontent.com/assets/1163591/6434526/de402f9e-c03f-11e4-9ae7-2c049a1e196a.png)

Do you have any simple examples you can point me to?  I can't find anything in the help.

**Comment by cycomachead** [comment]
> For more clarification, I have the image and want to display it. I

Ah, if you already have the image locally, you can just drag it onto Snap<i>!</i> and it will be saved. (You should also be able to use the import command to load a file).

For JS function there are examples when you "Open" a new project, click the Examples tab and there's a set of projects and open the one called JSFunctions. The block operates in context of the current sprite/stage, so that's what `this` referrs to. See this very simple screenshot:
![screen shot 2015-03-01 at 7 43 17 pm](https://cloud.githubusercontent.com/assets/1505907/6435117/5853e126-c04b-11e4-8d44-04b2ced7982b.png)

**Comment by bromagosa** [comment]
I actually have a block in a fork of mine that stamps an image from a URL into the Stage, and I find myself using it really often. If the Snap! crew thinks it would be nice to have it in trunk I can of course issue a pull request.

![image](https://cloud.githubusercontent.com/assets/1016697/6438281/e772d570-c0c7-11e4-8949-848cf265704f.png)

**Comment by sharived** [comment]
I think this would be a great addition!  In the meantime can you share your
code?

Thanks,
Shari

**Comment by bromagosa** [comment]
There it is:

https://github.com/bromagosa/Snapi/blob/5ce48fd29dc9b5f5f38696801b96080b929e7125/snapi/threads.js#L357

**Comment by sharived** [comment]
Thanks,  unfortunately I am struggling with trying to convert this code
into a block within my snap code.  It is dependent on other items in the
code which I don't seem to have access to (or else I don't know what I'm
doing).  For example the first error I get is - "cannot read property
receiver of undefined".  I think I'll have to wait until your block is
incorporated into the trunk.  Oh well, this would have been a really cool
feature.

**Comment by Gubolin** [comment]
> For example the first error I get is - "cannot read property
receiver of undefined".

Change the first line to `var sprite = this` and it works.
![stamp_url](https://cloud.githubusercontent.com/assets/5623169/6530678/35ebc946-c433-11e4-9ae1-f0a8f239a1c6.png)

**Comment by sharived** [comment]
Thanks so much!  That worked!!  I still think it would be great for this to be a permanent addition.

**Comment by sharived** [comment]
Do you know of a way to setup the image without using a URL.  I have access to the image data but I currently don't have a way to access it through a URL.  I've been searching around, but don't see if there is a way to do this.  So for example if I have generated some image data can I display it with the drawImage function.

Thanks,
Shari

**Comment by Gubolin** [comment]
You could use `data:image/png;base64,` as URL prefix followed by the image encoded as base64.
You could also download the Snap*!* source, place the image in the downloaded folder (let's say as `pic.png`) and set `img.src` to `pic.png`.

**Comment by bromagosa** [comment]
Yep, what @Gubolin suggests works. You'd have to remove the ``http://`` part from your code though:

``img.src = url;``

Then, for cohesion, the name of the block should not show ``http:/`` either.

**Comment by jmoenig** [comment]
Why don't you import the picture into a sprite's wardrobe and stamp it from there? Does it have to be dynamic? (Just curious). Thanks!

**Comment by bromagosa** [comment]
@jmoenig, sometimes it does have to be dynamic. When I found I needed this block I was working with a weather API that provided URLs to hundreds of images representing different weather conditions, so importing them into costumes would be nearly impossible.

There are other scenarios, like pulling an image from an image search service depending on the user input, or like pulling a random image from a webservice like this:

![image](https://cloud.githubusercontent.com/assets/1016697/6553018/73851f94-c64c-11e4-873a-2c02306057ee.png)

**Comment by luis140219** [comment]
Here's how to include luismark.js and jQuery with JS Function (requires Tools first):
![script-include-libraries](https://cloud.githubusercontent.com/assets/8597264/6554951/e8140e5e-c658-11e4-8672-c2bf9a3fcf9e.png)

**Comment by sharived** [comment]
Thanks all!  The data:image worked for me.   Yes, I need this to be dynamic.  I'm going to be displaying images from a camera.  I have developed a camera for lego mindstorms (will be kickstarting it shortly)  and am using Snap! as my primary programming language.  I really like Snap!  - thanks for making it possible :)

**Comment by jmoenig** [comment]
wow, @sharived , that sure sounds *very* exciting! I can't wait to find out more about your kickstarter!!

**Comment by sharived** [comment]
Thanks.  I'll send a link to the kickstarter once it's live (trying to get my video done...)
This is a USB camera that connects to an Ev3 running Ev3Dev or to RaspberryPi + BrickPi.  The camera can detect shapes and colors and capture images.  I created a Snap! API for the camera and the motors.  Here's a sneak peak of the camera API to give you a better sense of what it does (https://github.com/10Imaging/RoboSnap/wiki/Snap-Camera-Blocks)

**Comment by jmoenig** [comment]
This is totally cool, @sharived ! A camera mounted on a robot is such an obvious yet awesome extension. I've had a look at your API and it looks great! Of course, I don't have an Ev3 myself, but this could just be a reason to get one.

In your instructions (https://github.com/10Imaging/RoboSnap/wiki/RoboSnap-with-Snap!-on-the-Ev3) you could probably combine steps 2 and 3 into a single one by providing a shell script that also starts your standard browser with your API pre-loaded (using the #open: or #cloud: url "switches").

Oh, and I've got more questions yet: Are you also going to support compiling Snap scripts (via codification) and embedding them? Here's the reason I'm asking: In Germany you're up against "Open Roberta" - http://www.open-roberta.org/en/welcome/ - (basically a government backed Google Blockly clone that the Fraunhofer institute claims to have developed). Your camera, however, along with a full-fledged API seems to be so much more fun, offer so much more engagement and a richer interaction with the robots. That's why I'm excited!

**Comment by jmoenig** [comment]
Okay, some more ideas for the camera:

* You could make blocks that directly import camera shots as costumes into Snap
* You could probably offer a block that streams what the camera sees directly to the stage (or to its pen trails layer)
* There are some image masking primitives inside Snap that let you filter pictures by color, this could be used for collision detection etc.)

**Comment by jmoenig** [comment]
Oh, and a final idea: Have you considered attending this year's Scratch Conference in Amsterdam? It would be awesome to demo your camera and to give a workshop: http://www.scratch2015ams.org/

**Comment by sharived** [comment]
Thanks so much for the feedback!
Yes I plan on improving the startup sequence - hadn't thought about starting the browser via a script and pre-loading my API - will definitely do that as well.
Didn't even know about Roberta - sounds interesting.  Maybe they want to support my camera! - I only created the motion API because I had to. 
I hadn't heard about codification before - I'll look into it, but it seems very doable.
Great camera ideas - I'll look into them.
I just finished the block that this issue was based on 
![snap_show_last_picture](https://cloud.githubusercontent.com/assets/1163591/6581505/9c4572a8-c714-11e4-8a52-159749645c79.png)
This takes the image you captured and displays it on the stage.  I think this is similar to your second bullet.  I'll make it so that you don't have to always save the image, this will speed things up so that the images can be streamed.
I don't see the image masking primitives - what are they called?

I'd love to participate in the conference!  I'll sign up and hope that I can find some cheap lodgings.  Looks like they are trying to coordinate some host families - that would be great.

**Comment by jmoenig** [comment]
Awesome, @sharived , I just saw your workshop proposal for the Scratch Conference. This is going to be great fun! Incidentally, since you'll be there anyway, you might consider also an ignite talk ("this is my cool gadget - come to our workshop and be sure to stop by our poster") and definitely a poster. A poster (and a table on which you can demo stuff) are especially great because it'll reach almost everyone who's at the conference.

**Comment by jmoenig** [comment]
Oh, if you need any help/explanations with exploring Snap's "codification" mechanism for compiling and embedding blocks code in robots (so they can operate untethered) just holler!

**Comment by bromagosa** [comment]
By the way, if you want to package your solution into a desktop app so you don't depend on particular browser versions and configs, you may want to take a look at [nwjs.io](http://nwjs.io). It's a library that mixes browser javascript and Node.js, allowing you to turn virtually any web app into a desktop app.

That's what I've been using in Snap4Arduino and I couldn't be happier with the results :)

**Comment by sharived** [comment]
@jmoenig -can you sign me up for an ignite talk and poster/table - want to get as much visibility as possible!  Didn't realize I can choose multiple items.

BTW, I'm already operating untethered.  I use bluetooth on the EV3 and WIFI on the Raspberry Pi.  I'm guessing running locally on the robot would be faster and wouldn't require a computer - are those the benefits?  I guess I haven't experimented with different browser versions - are there compatibility issues?

**Comment by jmoenig** [comment]
@sharived you can just go to the website and use the online form to submit more proposals (you can also simply reuse what you've already written). I think it would be great if you also gave an Ignite Talk and did a poster / table!

Yep, I've seen that you're operating wirelessly, which is terrific! I think I meant "autonomous", although that might be slightly misleading, too. I'm not even sure about the benefits. Actually, I believe there are probably *way* more benefits if you run the controlling software on a computer, rather than compile it and transfer it onto the robot. But I've noticed that some schools (in Europe) prefer to embed code rather than having a laptop control a robot. But I'm not a teacher, perhaps someone with more knowledge could chime in ... @bromagosa ?

**Comment by bromagosa** [comment]
I'm also with @jmoenig in preferring interactivity over autonomy. However, it is true that needing to keep a computer always on and connected to your device -even without a cable- can be a hassle in some specific setups. @sharived, in your case, since you're dealing with an educational robot, I don't think this will be much of an issue though!

Still, embedded computers are becoming so cheap and powerful that you could just attach a BeagleBone or a RapberryPi to your device (an EV3, an Arduino, etc) and forget about codification. Also, take in account there are lots of things you'll never be able to codify and compile, such as sprite collision, color detection, message broadcasting or lambdas, meaning that having the compile-and-push functionality will in turn require the user to give up most of what Snap! has to offer...

Hope it helped!

**Comment by sharived** [comment]
@jmoenig - I was trying to try improving my startup.  In particular you comment from March 10th - In your instructions (https://github.com/10Imaging/RoboSnap/wiki/RoboSnap-with-Snap!-on-the-Ev3) you could probably combine steps 2 and 3 into a single one by providing a shell script that also starts your standard browser with your API pre-loaded (using the #open: or #cloud: url "switches").
Do you have any more info on this?  I tried guessing the syntax but didn't figure it out.

**Comment by jmoenig** [comment]
Hi, @sharived . You make a project that has the custom blocks for controlling the camera and either save  (and share) it on the SnapCloud, or upload it to your own server (which also can be a local server).

In case you are sharing the project with the API to your camera on the SnapCloud your can then have your shell script open Snap! using the #cloud: url switch. This will simply open your project in edit mode without starting it right away. Here's an example:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=Double%20Jurassic%20Park

if the same project is hosted on another server, you an use #open: instead of #cloud: like this:

http://snap.berkeley.edu/snapsource/snap.html#open:http://snap.berkeley.edu/snapsource/demo/Double%20Jurassic%20Park.xml

Also, if you *export* the custom blocks making up your camera API you can make *that* xml file accessible on a (non-Snap-Cloud) server, and start Snap! the same way (using #open:), in which case Snap will start with an empty project and only load your blocks.

Does that make sense?

**Comment by sharived** [comment]
It does make sense.  Thanks!

**Comment by RatGit** [comment]
Hi All, I am attempting to do the same thing as "**sharived**" for our own STEM Learning Kit product, (see [http://www.linksprite.com.au](http://www.linksprite.com.au) for more details). The plan is to implement an image processing library in Snap! with such features as:

- Image Capture
- Grey Scaling
- Colour Mapping
- Colour Sensing
- Optical Flow Sensing
- Motion Detection
- Edge Detection
- Shape Detection
- Optical Character Recognition
- Shape Recognition
- Facial Recognition
- Blob Counting
- etc...

I am using Lighttpd as our local web server running Snap! on our pcDuino boards in the kits. Camera snapshots are stored as a file called "/tmp/images/snapshot.jpg". There is a symbolic link to this folder in the "/var/www" folder so that the web server can access it and I have made sure that the file and folder permissions are set accordingly, (ie. "owned by www-data").
When I use the technique to stamp camera snapshots on to the stage initially described by "**Gubolin**" it always works the first time, but fails to update the image on subsequent calls... see below:

![Stamp Snapshot Script](http://learning.linksprite.com.au/files/stamp-snapshot-script.png)

Just in case it was due to a web server caching issue, I've tried accessing it as a URL with a random string argument and setting the following Lighttpd caching options, all to no avail:

_server.stat-cache-engine    = "disable"
server.network-backend      = "writev"_

At this point I am stuck and would appreciate any suggestions...

ps. I'd also like to know how to "clear" the stage, (ie. fill it with a particular colour, eg "White"). This would prevent previous images saved to the stage to be preserved between script loads.

Thanks in advance...

**Comment by RatGit** [comment]
pps. Should
`if (isWarped) {sprite.startWarp();}`
actually be ?
`if (!isWarped) {sprite.startWarp();}`
