### ISSUE TITLE
Ringifying variables

### ISSUE THREAD

**Issue by mikemm27** [jmoenig/Snap--Build-Your-Own-Blocks#732]
I am not completely sure it is a bug but something strange happens.
I discovered the following in a more complex context but, to fix
the point, I refer to a very simple example.

I would define a block 'putval' with two parameters, 'var' of Reporter type and
'val' of Any type. Through the first parameter the block receives a variable  'name' 
and sets that variable with the value received in the second parameter. 
The way I found in BYOB was to ringify the name of a (global)
variable when I call the block putval and insert the first actual parameter (the second
parameter is not problematic), whereas in the body of the definition of 'putval' 
I drag-and-drop the 'var' name (the copy of the first formal parameter of the block)
onto the arrowed list in the first slot of a 'set variable' command.
This is allowed in BYOB and it works. By the way, to read the content of the variable
in the 'putval' body you should apply the 'call' block to 'var'. Even if I import this
BYOB program in Snap, it appears absolutely similar to the original and works.

Now, If I try to re-code the program from the scratch in Snap, I fail
because I cannot drag-and-drop the first parameter 'var' in putval onto
the first slot of the set command in its body. Moreover, I was not able to find any other
shortcut to solve the problem (which can be summarized so: I want to act
in the same way on different variable in different times, coding a sub-block). 

Thus, the two questions are:

1 - is the difference between BYOB and Snap in this respect explicitly wanted
or is it a bug?

2 - If it is wanted, is there any other correct solution of the problem?

Thank you for your help.
mike - Padova - Italy

**Comment by jmoenig** [comment]
Hi Mike,

I'm not exactly sure whether I totally understand your issue, but it appears you want to access a variable by its name to change its value from within a custom block.

Here's a project which - sorta - does what you want (I think)

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=swap%20variables

instead of a variable *name* it lets you drop a variable *reporter* into an input to be manipulated by the custom block.

Does that help?
Thanks!

**Comment by mikemm27** [comment]
Yes, perfect. The swap function is another typical example. Adopting a similar approach,
now my putval block works well.

Thank you so much, Jens, for this almost immediate help, hoping it is of interest to others.
mike

**Comment by jmoenig** [comment]
Ah, I'm really glad this worked out for you, thanks for letting me know!

**Comment by james1293** [comment]
FWIW, I found this really helpful to make a different-syntax assignment block (instead of `set _ to _`; it's `_ = _`). See this project 

https://snap.berkeley.edu/snapsource/snap.html#cloud:Username=pianoj&ProjectName=C_style_int_and_assignment

Background: I'm trying to work on (yet another) Arduino block editor. I wanted one that allowed easy creation of new blocks, and I always found [BlocklyDuino](https://blocklyduino.github.io/BlocklyDuino/blockly/apps/blocklyduino/) to be challenging in that regard.
