### ISSUE TITLE
passing variables in a fuction which has unevaluated parameters of the same name

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#752]
I've been experimenting with the swap custom block
![swap](https://cloud.githubusercontent.com/assets/8059587/6822878/ad8b27fa-d2eb-11e4-9e74-a882d2b65aad.png)
it works OK if you pass variables with names other than the parameter names(that is 'a' and 'b').
But if you pass variables 'a' and 'b'
![swapcall](https://cloud.githubusercontent.com/assets/8059587/6822913/028882d4-d2ec-11e4-97f8-b2d7ca1c7f57.png)
it does not work.
Same thing happens in rerorter type parameters, and in lambda functions.

P.S: This is related with issue #732

**Comment by jmoenig** [comment]
Yes. Hmmm. The reason for this is that the SET block - if it is given a ringified variable blob instead of a variable name - simply takes the label of the ringified variable block and looks up the variable of that name. In this case the SET block looks up the variable named "a", and the parameter named "a" is in a nearer scope than the global variable named "a".

So, the fix for this would be to look up the variable within its original context. I think I can do that.

Thanks!

**Comment by jmoenig** [comment]
Yup, the fix I was outlining totally works! I've got it running in my dev version(s) and I'll push it later today. Thanks again, @haritop

**Comment by jmoenig** [comment]
... and then it also works with temporaries (script variables), which used to be an issue @MMSequeira encountered a while ago.

Hang on, while I finalize the fix!

**Comment by jmoenig** [comment]
Okay, can you please test your project again?
My own little test cases are here:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=swap%20variables

press green flag: swap globals
press left arrow: swap sprite-locals, same-named as block parameters
press space: swap temporaries, same-named as block parameters

Please let me know if it doesn't work for you.
Thanks!

**Comment by haritop** [comment]
Works nicelly, and I think better than BYOB.
Thank you very much.

**Comment by jmoenig** [comment]
Thanks for checking and letting me know!
