### ISSUE TITLE
Two proposals

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap--Build-Your-Own-Blocks#754]
1. Provide an "on load" event.
    I think this would be useful for projects running in presentation mode, and not only. 
    A special message like "onload", transmmited from Snap when the project is loaded and intercepted 
    by "when i receive ..." hat block, could do it.

2. Disable block execution by clicking (storable option).
    This could enable the teacher to switch between an interpreter-like mode to a compiler-like, and vice 
     versa.
     In my opinion, this option has two advantages:
     a. Gives students a more "genuine" feeling of Event Driven Programming, since everything that is executed is connected to some event.
     b. Forces kids to create an algorithm to solve a problem. I've noticed that in the begining, when they do not fully apprehend the notion of algorithm, they try to create programs by just clicking on blocks. I think, that gives them a wrong impression about programming.

**Comment by brianharvey** [comment]
(1) No; (2) probably not.

1:  Since we live in a world in which we are encouraging people to download projects written by people they don't know, they should have a chance to read the project before deciding whether to run it or not.

2.  You might have a chance on this; Jens fiercely opposed hiding primitives for three years before finally going along with it.  But in general, we do not prioritize changes whose purpose is to *prevent* people from doing what they want.  The goal is for people to think programming is fun, not to think that it's just like school.

**Comment by haritop** [comment]
I got your point proffessor Harvey. I didn't see the big picture.
Thank you for your comment.
