### ISSUE TITLE
data files

### ISSUE THREAD

**Issue by gherson** [jmoenig/Snap--Build-Your-Own-Blocks#755]
Is there a mailing list?  It seems i can't categorize a new issue as a Suggestion, etc.

(Github.com is having problems today... Page requests are timing out with "This webpage is not available" etc fwiw.)

Is there a development roadmap?  Any plan to snap in functionality allowing read/write of data files?  Would that be rejected if offered as a JavaScript contribution?

**Comment by gherson** [comment]
I also have other feedback to leave, such on the manual.  I'll leave it here if no response.

**Comment by bb010g** [comment]
Standalone JSON serialization to strings wouldn't hurt and should be pretty cheap (we already do serialization on save); I don't know about file IO. I'd think it wouldn't be too much of a bother w/ the Snap*!* style, but I don't think you can really get arbitrary file access for easy reading and writing to files...

**Comment by gherson** [comment]
Not arbitrary file access, the ability to read and write files somewhere safe. 
 
Real world computing is largely about data processing, and I'd try to show that when teaching.

**Comment by bb010g** [comment]
So, something akin to [read file into (variable)] & [write (variable) into file] that would pop up dialogs for location?

**Comment by cycomachead** [comment]
Right now, there's no direct file system access, and there can't be due to web security. (At least not without some work arounds).

You can "import" and "export" variables as long as it's text data. (I believe the extension also needs to be `.txt`) Create a variable, and have the watcher showing on the stage and then right click on the watcher to use those menus.

You can also use the http block to get content stored on other websites.

**Comment by gherson** [comment]
Yes, @bb010g, where variable can be a list, and No to a mandatory dialog: there should be a safe/allowed directory, so that the desired filename therein can be specified in the Snap! block by the Snap! programmer.

@cycomachead, here is a nice workaround: "FileSaver.js implements the HTML5 W3C saveAs() FileSaver interface in browsers that do not natively support it. There is a FileSaver.js demo that demonstrates saving various media types." -- https://github.com/eligrey/FileSaver.js

**Comment by cycomachead** [comment]
> @cycomachead, here is a nice workaround: "FileSaver.js implements the HTML5 W3C saveAs() FileSaver interface in browsers that do not natively support it. There is a FileSaver.js demo that demonstrates saving various media types." -- https://github.com/eligrey/FileSaver.js

Hmm I've seen filverSaver but when I last looked at it, it was a bit buggy, though it seems to have come a long eay. You could test this in current Snap<i>!</i> using a JS function block that loads the script and calls the right APIs if you wanted. 

The other much more involved option (especially for loading data) would be to create a simple web server in Python or nodeJS (that can be run from something like http://localhost:8000/) which exposes OS level calls to reading and writing files and all that stuff. You could then use the HTTP block to get files. (And in theory write files too, but pasing data through the current HTTP block is a little tricky.)

**Comment by gherson** [comment]
Eventually should be made easy but I like the JS function block idea, thanks.  If i try it i'll report back.

**Comment by brianharvey** [comment]
This is a needed feature, absolutely.  I'd prefer to avoid the external webserver solution because schools would never allow it.  If HTML5 gives us a way, terrific.  (At worst, the same overgrown-cookie feature that we use for save-in-browser could be used.  But that makes it hard to see the file outside of Snap!.)  FileSaver sounds ideal.
