### ISSUE TITLE
Event queue doesn't queue multiple 'broadcast' events

### ISSUE THREAD

**Issue by deader69** [jmoenig/Snap--Build-Your-Own-Blocks#769]
When broadcasting the same event multiple times, only one of them makes it into the event queue.

This happens only with 'broadcast', not 'broadcast and wait'.

Here's a simple Snap app that demonstrates the bug.
I 'broadcast' foo four times, but only receive one.
But I get all four foo events if I use 'broadcast and wait'.

  http://snap.berkeley.edu/snapsource/snap.html#present:Username=deader-tcssm&ProjectName=BUG%20broadcast

**Comment by Logalicioustuff** [comment]
Confirmed! :o

**Comment by brianharvey** [comment]
Yeah, it's nothing special about broadcast, it's a {feature,misfeature} (you choose) of event handling in general in Snap<em>!</em>.  If a script is running and the event that triggered it happens again, one of two things happens: (1) the default is to do what Scratch does: abandon the partially-completed script and start it again from the top; (2) if you select "thread-safe scripts" in the settings menu, then the second event is just ignored.  It turns out that the Scratch behavior is what you want if you're generating music, because a new note is more important than the decay of the old note so that you keep the beat correctly.  But if you're modifying the program state (such as the values of global variables) and you abandon a script in the middle, you may end up with inconsistent values.  The official right thing, we know, is to buffer the events and get to them once the first one finishes.  It's on the list, but then we have to decide whether this is a third behavior, or if we break old programs.

**Comment by deader69** [comment]
That's what I feared... the 'bug' is actually a 'feature'... Although I'd say it's a horribly hack, an incorrect "solution" to a problem. And now we have to live with it, for backwards compatibility?

I can also see where other apps will break... despite Snap! 'simplicity', the multi-threaded nature opens the door to super-deep sync issues, as you said. And it is so easy for kids to accidentally be generatin the same event from multiple different points in their code, without knowing it. Ignoring events makes it user-friendly for kids, more forgiving... but also teaches them bad programming practices.

And I haven't even talked about auto-repeat from the keyboard!

FYI, this all came up when I was trying to write a 'simple' Morse code app. Each dot or dash is drawn via an event, so sending SOS in Morse code generates 9 events (...---...)

And like I said, the problem is compounded when users hold a key down, because auto-repeat (which is very os/user-specific setting) generates a whole lot of key events in a short timeframe.

It really breaks my heart that the event queue is broken, because then I'd almost have to re-implement a queue myself, just to get stuff working. Guess I'll convert my dot/dash and other events into custom blocks and function calls, to sidestep this bug... err, I mean, FEATURE. Should probably be LOUDLY documented somewhere, because it took me a while to realize it wasn't my fault, lol!

Thanks for the quick and detailed explanation!
