### ISSUE TITLE
Weird Snap! Bug that makes it unable to open projects

### ISSUE THREAD

**Issue by lmock** [jmoenig/Snap--Build-Your-Own-Blocks#798]
![error](https://cloud.githubusercontent.com/assets/5467107/7560144/e44d58be-f774-11e4-9774-19518d773231.JPG)

Because this is a student project, I've shared the link with you from Google Drive.

@cycomachead because he's familiar with the issue

**Comment by jmoenig** [comment]
thanks, investigating...

**Comment by jmoenig** [comment]
there appear to be two unused "leftover" custom reporter definitions for ```"#'s in rows %grid"``` in the project source that conflict with a later version...

(still investigating....)

**Comment by jmoenig** [comment]
... actually, there's another custom reporter definition that looks somehow fishy: ```"# of #'s %grid"```

(still investigating...)

**Comment by jmoenig** [comment]
okay, here's a possible cause:

```"# of #'s %grid"````

there is an apostrophe after the pound sign: ```x's```. This is specifically prevented in the block editor (apostrophe's cannot be used within block labels - hey, it's wrong English grammar for plurals anyway :-) - because they are used internally. How did your student force this one in? Did they edit the raw XML with a text editor?

(still investigating...)

**Comment by jmoenig** [comment]
... well, that doesn't seem to be the real problem ...

(still investigating...)

**Comment by jmoenig** [comment]
got it!

(now fixing it...)

**Comment by cycomachead** [comment]
I doubt they edited the XML directly...

Also, when I was testing this project -- Safari just hung and never displayed an error. I'm using 8.0.5.

**Comment by jmoenig** [comment]
the problem is the extra apostrophe which never should've gotten into the block spec. There are a few issues that can arise when resorting to "power-user" features such as adding inputs with the percent sign prefix, especiall in conjunction with apostrophes. Snap doesn't completely prevent these in the UI, which I'm fixing now. The other issue is whether I can fix the existing project to load correctly (I think it's possible, though...)

**Comment by jmoenig** [comment]
I was able to fix the project (sent to you via email just now).

I’m not yet sure how to prevent this from happening in Snap itself. The problem is that single quotes are part of Snap’s “power-user” notation for variable names. You can specify multi-word parameter names by putting them into single quotes:

	```my block %’my special parameter’```

creates a block with an input named “my special parameter”.

Therefore I cannot simply ignore the single quotes and apostrophes if the user also uses a percent sign in the spec (if they don’t Snap does, indeed filter them out). The only fool proof solution I can think of right now would be to disable the percent-sign shortcut altogether, but that’s probably not going to be appreciated, either :-)

So, while I mull over this please let your students and TA’s know that “though shalt only use single quotes in block specs to delimit multi-word input names”.

**Comment by cycomachead** [comment]
> I’m not yet sure how to prevent this from happening in Snap itself. The problem is that single quotes are part of Snap’s “power-user” notation for variable names. You can specify multi-word parameter names by putting them into single quotes:
> 
> my block %’my special parameter’
> creates a block with an input named my special parameter.

Woah... I didn't know you could actually do that! 

Personally, while I think this is nice, if it is indeed the cause of a bug -- why not allow only single word variable names when using a `%` shortcut? I'd personally wager that's how it's used 90% (or more) of the time anyway. 

As far as solutions, you should be able to check for only two `''` after single `%` and before the next `%` (or end of the input text), since I'm also assuming variables aren't allowed to use `'`.
Still, this does seem unecessarily complex for something I don't think is used terribly often.

**Comment by jmoenig** [comment]
well, the shortcut notation is an - undocumented! - power user feature, so ...
Thing is, Snap uses the above multi-word notation internally, and also for the inputs you create using the "normal" way (by clicking on the little plus signs or by turning a label word into an input). Therefore, if we want a fool proof way to support power users (which may be an oxymoron...) we might want to re-design the parser of the block dialog. This is on the list for 4.1 anyway...
