### ISSUE TITLE
URL HTTP:// request error

### ISSUE THREAD

**Issue by mmaggio100** [jmoenig/Snap--Build-Your-Own-Blocks#799]
When i do the http://(public url it doesnt work so i went here:) https://snap.berkeley.edu/SnapManual.pdf for help.. WELL after doing what it said with the cons thing it doesnt work help i had a great idea and i would love to do it!

**Comment by jmoenig** [comment]
Can you tell me more about the problem? I don't understand the part about "cons". Thanks!

The HTTP block relies on the server of the accessed site to allow sharing resources as a web service. Unfortunately many website do not allow this yet (Look up "CORS" on Google). This is not Snap specific and there is actually nothing Snap can do about this, it's the responsibility of the website you would like to access. If it is your own server, make sure to enable CORS (again, look it up).

**Comment by studej** [comment]
@jmoenig I think that @mmaggio100 complains because of instructions in manual telling you to use in http block corsproxy.com website which is currently unavailable (http://www.corsproxy.com/)

**Comment by cycomachead** [comment]
@brianharvey This is a snap manual issue :-)

corsproxy is now dead -- so we could / should remove the reference to it. A (current) alternative is cors.io though the manual should simply also say "Google for a CORS Proxy if this link isn't working" (or something). 

You're gonna hate me for saying this -- but I'm gonna say it still -- want to put the manual in some VCS somewhere so others can help? :-)

(Though I think it's written in Word? Which would be too bad, because I'd _love_ to turn the manual into a webpage.)

**Comment by jmoenig** [comment]
>I'd love to turn the manual into a webpage

+1

**Comment by bb010g** [comment]
[**@cycomachead**](https://github.com/cycomachead) commented on [Jun 25, 2015, 11:55 PM PDT](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/issues/799#issuecomment-115551260 "2015-06-26T06:55:54Z - Replied by Github Comment Enhancer"):
> (Though I think it's written in Word? Which would be too bad, because I'd _love_ to turn the manual into a webpage.)

Markdown would work well. You can convert that into HTML and (w/ something like Pandoc) LaTeX for a nice PDF.

**Comment by cycomachead** [comment]
> Markdown would work well. You can convert that into HTML and (w/ something like Pandoc) LaTeX for a nice PDF.

Yeah, I'd use Pandoc as a start. I'd like Markdown as well, but @brianharvey Is the main one writing, so it's kinda useless to use a format if the authors don't like it.

**Comment by bromagosa** [comment]
Hey, about corsproxy, it's fairly easy to set up a simple service that proxies HTTP requests. Since we work a lot with APIs, we were using it *a lot*, so when it died we just set one up in a server of ours.

We're using an npm package called [corsproxy](https://www.npmjs.com/package/corsproxy) that works wonderfully.

**Comment by cycomachead** [comment]
> Hey, about corsproxy, it's fairly easy to set up a simple service that proxies HTTP requests. Since we work a lot with APIs, we were using it all the time, so when it died we just set one up in a server of ours.
> 
> We're using an npm package called corsproxy that works wonderfully.

Yep, I have one too for BJC, same package I believe. :-)

(The nice benefit here is that I don't have to put proxy in the URL so that it works in overly-restrictive schools. Hahah.)

**Comment by brianharvey** [comment]
So, wait, are you saying you have a solution that BJC teachers can use?  Where?

**Comment by cycomachead** [comment]
For a proxy server? Not any more... Well I could try again, but it's not going to be any more stable than crossorigin.me

Anyway, it was running on heroku but got disabled b/c it apparently violates there TOS.
