### ISSUE TITLE
iPad: Sounds do not play

### ISSUE THREAD

**Issue by andcarey** [jmoenig/Snap--Build-Your-Own-Blocks#819]
When editing my project I can play the sounds and they work just fine in the sounds tab.  But when I run the project they do not play.

**Comment by jmoenig** [comment]
yeah, I really wish I knew why :-(

**Comment by birbilis** [comment]
if you mean in browser, then does iPad have browser dev tools that you can open somehow to see error messages?

**Comment by cycomachead** [comment]
I does -- you can use a web inspector when tethered over USB. However, when trying this no events we logged to the console and no messages were reported. :(

**Comment by andcarey** [comment]
Hi Michael, I tried this as well and also did not see any errors.  I tried
replicating what the snap code does (see this jsbin
http://jsbin.com/nuburotihu/1/) and this works on the iPad, so there must
be some code that runs in snap after this that interferes with the audio.

Basically I copied the code from the Sound.prototype.play function in
object.js (line 6359) and also copied the way snap loads the sounds from
the XML model starting at IDE_Morph.prototype.rawOpenCloudDataString in
gui.js (line 3088).  Snap fetches the XML for the project which is
contained with a <snapdata> element.  This contains the media tag (see
below) which includes the sounds as a base64 encoded string (its truncated
in the text below, the actual sounds I tried is 280kB long).  So my code in
the jsbin pretty much loads and plays the sound the same way as snap does
and it works, however when snap runs it makes no sound.  I'm pretty much
stuck for now ... the only thing I can do now is continue stepping through
the snap code to see if there is anything that interferes with the sound,
eg. pauses it, unloads it ?!?.

<media name="Sound1" app="Snap! 4.0, http://snap.berkeley.edu"
version="1"><sound name="Halloween_Vocals-Mike_Koenig-517765553"
sound="data:audio/mp3;base64,//uQZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGluZ…cY2X+iXRLEoKg1WCoLHsGvWGoNAUCnZV31A0DQMhoeCrk4K0xBTUUzLjk4LjRVVVVVVVVVVVVV"
mediaID="Sprite_snd_Halloween_Vocals-Mike_Koenig-517765553"/><sound
name="Hammering"
sound="data:audio/mp3;base64,SUQzAwAAAAAHdlRDT04AAAAHAAAAQmx1ZXMAVElNRQAAAAYAAAAyM…AAAAAAAAAAAAAAAAAAAAAAAAAyMDEyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
mediaID="Sprite_snd_Hammering"/></media>"

If anyone has any other ideas, let me know.  Happy to keep trying things
and debugging this over the next few days.

Thanks,
Andy.

**Comment by andcarey** [comment]
@jmoenig @cycomachead I used the same sound that I used in this snap project:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=andcarey&ProjectName=Sound1

**Comment by birbilis** [comment]
trying that url of @andcarey with IE11/Win8.1 I see that one can't press space key, the focus seem to go to the browser addressbar. Also the message of Snap! saying "Fetching project from cloud" at start could show a big cloud icon with some arrow pointing downwards that animates from inside the cloud to outside (downwards) and then again (non-palindrome loop) slowly till the file comes (it takes some time btw before you see the next message "opening project")

**Comment by cycomachead** [comment]
Interesting, that's good to know it still works. 

I've been trying to debug with a built-in Snap<i>!</i> note, which also doesn't play, nor does it error.

Output from the Safari Console when I was trying things: 
(Dev mode is only to ensure that Snap! Wouldn't catch any errors.)
```
> ide = world.children[0]
< IDE_Morph
> ide.switchToDevMode()
< undefined
> n = new Note()
< Note
> n.play()
< undefined
> n.stop()
< undefined
```

So, that didn't work. Other point of note: The block clicking sound (which I usually don't use anyway) is also not playing.

I tried the project @andcarey linked, and indeed I can't play audio on click. HOWEVER, directly tapping the "Play" button in the sounds panel does indeed work! 

With only 5 minutes of digging -- this appears to be an iOS limitation that only allows 1 audio context to be playing at a time. This SO question seems to suggest a work around, but I haven't had a chance to look into it yet:
http://stackoverflow.com/questions/12517000/no-sound-on-ios-6-web-audio-api

(If this is as result of the same issue: That iOS limitation has been present since iOS 6, and it is still present in iOS 9 so, we're gonna be stuck with it for at least 15 more months, probably. :( )

**Comment by cycomachead** [comment]
Tag #235 And making that the main issue, but it seems like there's no a great solution here. :/
