### ISSUE TITLE
Why hide some options in File menu ?

### ISSUE THREAD

**Issue by fredlefred** [jmoenig/Snap--Build-Your-Own-Blocks#831]
I wonder why the "Save To Disk" option is hidden and need a shift click to be shown ?
It would be better if this option is always shown.

**Comment by brianharvey** [comment]
Because it doesn't work in every browser.  In general, shift-click options are either not fully debugged, browser-specific, or otherwise unreliable.  (Exception:  Some of the shift-click options in the settings menu are formerly-controversial ones that are now set by default, shift-hidden just to keep the menu from being overwhelmingly large.)
