### ISSUE TITLE
Error when dragging a sprite nested in another sprite while moving

### ISSUE THREAD

**Issue by trumank** [jmoenig/Snap--Build-Your-Own-Blocks#875]
When dragging a child of a parent sprite while the parent is being moved within a script causes the script to error and yields this:
```
Type Error
Cannot read property 'center' of null
```
[Test case](http://snap.berkeley.edu/snapsource/snap.html#present:Username=bh&ProjectName=ferris)

**Comment by jmoenig** [comment]
Thanks! this will be fixed in the next release (sometime next week). The right thing to do, of course, is to pick up the whole composite sprite when you pick up one of its parts, which is how it's going to be (you'll still be able to adjust the position of parts by "sliding" them using the "move" option in their context menus, which will also be improved).

**Comment by jmoenig** [comment]
I've fixed this in yesterday's release.

**Comment by jmoenig** [comment]
fixed
