### ISSUE TITLE
[Minor feature request] Why can't you change a command to a reporter (by clicking the hat part of the hat block) after you've hit "ok"?

### ISSUE THREAD

**Issue by ddgarcia** [jmoenig/Snap--Build-Your-Own-Blocks#879]
I believe you can go the other way (reporter to command) but not the other way around, so I'm wondering why that is and whether it can be fixed.
dan

**Comment by jmoenig** [comment]
you can change anything to anything as long as it isn't in use

**Comment by ddgarcia** [comment]
Open

http://snap.berkeley.edu/snapsource/snap.html#present:Username=mypham&ProjectName=between%20lab

and right click on "(5) between? (0) and (10)" command block, choose edit, click the hat, and there's no way to make it a reporter. I don't believe it's in use. What am I missing?

**Comment by jmoenig** [comment]
the block is 'in use' because it's *in the scripting area* :-)

**Comment by ddgarcia** [comment]
Ah! Sorry. Is there a reason why that is? We can dynamically adjust parameters, why not commands<->reporter? I assume it's because it's too hard to pop reporter->commands out of the enclosing "holes" and commands->reporters out of their place in a block stack?

**Comment by jmoenig** [comment]
The reason isn't that it's hard but that it would accidentally break - potentially lots and lots of - user scripts, both in the main scripting area, but also inside block definitions. And then  changing the type back wouldn't "fix" those scripts again. I believe this would be the biggest nightmare for TAs imaginable!

Also, most Snap scripts aren't "named", so we'd have to come up with all kinds of new tools to enumerate them in order to show the affected changes to users. I bet that most students and most teachers wouldn't be aware that changing the *shape* of a block can break scripts and other blocks.

**Comment by ddgarcia** [comment]
This isn't any worse than "delete block definition", or "delete" (which is way too close to "duplicate" in the meny for my comfort level) as an undoable action?  Perhaps all three should be behind a "are you SURE you want to do this? (you won't be able to undo) How about saving the file first as a new name and then come back here and try it again" alert? That's not totally meant to be tongue-in-cheek, enough of my students have accidentally clicked delete when they meant to select duplicate (me too) that I think it should be behind a confirm dialog box, and this could too...

**Comment by jmoenig** [comment]
I think it is actually worse than "delete", because 1) "delete" prompts you to explicitly acknowledge whether you really want to delete it (it's the only "nag" dialog in Snap, btw):

![delete](https://cloud.githubusercontent.com/assets/2596285/8819512/2c97b1bc-304d-11e5-8e4c-1fe287864a5a.png)

And 2) You know things can break when you delete stuff, but you don't expect things to break badly when it's easy to change them.

So, you know, you *can* change a block, just make sure it's not in use :-)

**Comment by cycomachead** [comment]
I'm closing this since it's not going to get fixed anytime soon, but I do think Dan has a point. I'm also changing the tags. ;)

The "delete" problem that Dan mentions is the _context_ menu for a script, allows "deleting" a block from a script without a confirmation, which has led to many a distaster. 

The changing the block type could issue a warning, and it wouldn't be terrible. (Also if you change from report → predicate (or vice versa), there should be no warning since that's a stable change.)

I will say, that a warning would definitely be useful in some cases, because I've found while in the early stages of developing a project it's useful to change block types. I'll often have a lone block out and want to change the type, but dragging it in and out is a bit of a pain.
