### ISSUE TITLE
Custom Events In Hat Blocks

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#886]
Would it be possible to extend the way that hat blocks work to allow for other custom events?

Today I was talking with a student how it would be useful to do `when I am touching OTHER SPRITE`
However, I think it could be interesting to think of other cases where you could just drop in a predicate in a hat block. 

I know that this is fairly equivalent to a "forver if <condition> then broadcast <message>`, but was also wondering if this functionality were "native" if there could be any performance improvements, aside from just code cleanup.

**Comment by jmoenig** [comment]
It's certainly possible to make a generic hat block that takes a predicate. I've been experimenting with such a hat block back in BYOB. But there are seveal issues, because hat blocks are always "live" (something students and teachers sometimes forget, they believe that you have to press the green flag first to "activate" the project).

You're right that if the event is handled "natively" by Morphic it's way more performant, see the batch of additional events I've added to the "When clicked" hat. So, we might at one point add more of these primitives ("touching" would be a good one, I guess).

**Comment by cycomachead** [comment]
Yeah, it was the `when clicked` stuff that got me thinking.

I also got a sphero recently, and have been playing around with the API and the existing Snap! stuff. The interactivity with hardware that has an accelerometer and custom hat blocks would be _realllllly_ fun.

**Comment by cycomachead** [comment]
Fixed some time ago. :)
