### ISSUE TITLE
Question: Recommended Way to "Stop" a launched process

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#896]
Is there a "good" way to stop a particular launched process in Snap<i>!</i>?

I've seen students try this, which they expect to work, but doesn't. (And it makes sense why it doesn't work...)
![launch](https://cloud.githubusercontent.com/assets/1505907/8945971/301b5494-3541-11e5-9480-3af82563c14e.png)

You can use the `STOP all other scripts in this sprite` block, but that seems a bit heavy handed. 

This would be a totally new thing, but what about a "process ID" that's returned by a launch / call function and have the `stop` block take in a process ID? That makes sense to me, but I don't know if that would be super intutitive... Perhaps there's a better way that I'm missing...

**Comment by jmoenig** [comment]
since we don't have first-class threads you have to build your own using semaphores.

Off my head: Two closures can share the same non-local var, so you can have the launched one poll the variable at intervals (e.g. inside a "repeat until (some text on the non-local var)" and the other can be the switch that kills the thread by changing the shared non-local var. Make sense?

**Comment by cycomachead** [comment]
> Off my head: Two closures can share the same non-local var, so you can have the launched one poll the variable at intervals (e.g. inside a "repeat until (some text on the non-local var)" and the other can be the switch that kills the thread by changing the shared non-local var. Make sense?

Yeah, I think another TA had also suggested that.
