### ISSUE TITLE
export project as pure javascript script?

### ISSUE THREAD

**Issue by ppKrauss** [jmoenig/Snap--Build-Your-Own-Blocks#906]
The projects on Snap have an XML representation... And about a Javascript representation?

**Comment by jmoenig** [comment]
good question! I've been contemplating a more text-like serialization encoding for scripts. On the other hand, that's precisely what Snap's "Codification" feature is about: Already you can transpile Snap scripts into any textual programming language...

**Comment by ppKrauss** [comment]
Hi! is "any language" an ambitious project? :-)
Nowadays "unify all in Javascript" is a tendency, I think JS is the main language to be exported, and takes advantage of all Snap's libraries.

**Comment by jmoenig** [comment]
Well. Snap has a different execution model than JavaScript. For one, JS doesn't have threads, it's not (yet) tail-call optimized and doesn't expose continuations. So, just because the 4.0 version of Snap happens to be *implemented* in JS that doesn't mean projects written in Snap would translate to (even human readable) JS, same as Python programs don't export to C, even though the Python VM happens to be written in C.

But, coming back to codification, do you know about this feature? Here's an example:

http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=jens&ProjectName=Codification

IMO this is even cooler...

**Comment by ppKrauss** [comment]
Hum... Sorry my curiosity/ignorance, but I not understand the path between A and B,

  A. "[Snap! runs in your browser. It is implemented using Javascript](http://snap.berkeley.edu/)"
  B. "Snap has a different execution model than JavaScript" (@jmoenig  above)

Ok, you say "(...) just because the 4.0 version of Snap happens to be implemented in JS that doesn't mean projects written in Snap would translate to (even human readable) JS (...)", but I am a programmer, and I know that we can always "encapsulate" (by functions, references or objects) the dirty code into "human readable".

**Comment by brianharvey** [comment]
I think the bottom line here is that most projects, if translated to JS, will need the Snap<i>!</i> source code included with them in order to run.  So if your goal is to turn a project into an independent program, that can't be done (except for examples such as FizzBuzz that don't use graphics).  If your goal is to make the program run faster by avoiding an interpreter on top of an interpreter, that would work more or less straightforwardly for a single script.  But what Jens is saying is that if you have multiple sprites, or multiple scripts in the same sprite, you still need the Snap<i>!</i> scheduler to handle the (pseudo-)parallelism.  What I'd find interesting would be to translate each custom block into JS, install it as a primitive block, and see how much that would speed things up.

**Comment by cycomachead** [comment]
> So if your goal is to turn a project into an independent program, that can't be done (except for examples such as FizzBuzz that don't use graphics).

I wouldn't say that... It's perfectly possible to complie Snap<em>!</em> projects to any other enviornment which mimics turtle graphics. It can be done for Python without too much overhead, and it could even be done for JS if you allow for any implementation of Turtle graphics. (Be it nathan's Pixie, or PencilCode's turtle.js library). 

But yeah, if you're compiling code, you will always have to deal with the fact that the compilation target doesn't act like the source. 

I think it really depends on what you're trying to accomplish. 

For example:
In Snap<em>!</em>:
REPEAT UTNIL <false> {
// code
}

_could_ be translated as:
```js
while (true) {
// code
}
```
If all you want to do is show how _syntax_ maps, or handle (most) single threaded code, but this code wouldn't run like Snap<em>!</em> runs code because you can't have two `while` loops running at the same time in JS. 

> What I'd find interesting would be to translate each custom block into JS, install it as a primitive block, and see how much that would speed things up.

This would indeed be interesting! Though I wonder how much of a difference it would make...
