### ISSUE TITLE
Feature Request: Improved Share

### ISSUE THREAD

**Issue by davelai** [jmoenig/Snap--Build-Your-Own-Blocks#927]
Currently, sharing a project is not very intuitive. 

Goal: Share ProjectB

If I have ProjectA open, I can select to "open" a project and share "ProjectB" from that screen. ProjectB will turn bold and appear to be shared. But then if I choose cancel opening a project, the share process is also canceled (and I have no way of knowing this).

If I have ProjectA open, I can select "save-as" and share "ProjectB" from that screen too... but then do I need to save ProjectA to overwrite ProjectB? (rhetorical question) If I hit cancel, the share process is also canceled. 

Suggestion: Only have the option to share an open project. Remove the "share" option from within "open" and "save-as" and add a "share" from the main drop-down menu. This should allow you to share the currently open project (and possibly save at the same time). Share should only appear as an option for already-saved projects. ...at least this is an idea on how to improve share.

Thank you.

**Comment by cycomachead** [comment]
> If I have ProjectA open, I can select to "open" a project and share "ProjectB" from that screen. ProjectB will turn bold and appear to be shared. But then if I choose cancel opening a project, the share process is also canceled (and I have no way of knowing this).

AFAIK, once you click share, the project gets shared regardless of whether you open it. I don't know if there's a confirm though. 

I do think being able to make non-open projects shareable is useful, but I'm not sure how often this is used b/c it's not easy to get the shared URL.



> Remove the "share" option from within "open" and "save-as" and add a "share" from the main drop-down menu.

I don't know if we want to remove the buttons, but a "Save and Share" option has come up sometimes. 
#714

**Comment by cycomachead** [comment]
Also would it possible to allow me to start tagging issues. :-) @brianharvey

**Comment by davelai** [comment]
Once you click share, the project does NOT necessarily get shared.... it's dependent on your next action (cancel? save? open? etc)... that's what's confusing and not intuitive (and why a better "share" is suggested). =)

If once you click share, the project should be shared, then this is not currently happening and I would change my feature request to a bug fix request. Right now, if you share projects in the save-as or open dialog box, they become bold and appear to be shared... but if you click cancel on that save-as or open dialog box, then the share doesn't actually happen.

I like the idea of sharing open/closed/unsaved/saved projects, but I'm trying to simplify the suggested idea because as-is, the share behavior is very confusing and not simple.

I like #714 ! I should probably have commented this suggestion there... sorry.

**Comment by cycomachead** [comment]
> Once you click share, the project does NOT necessarily get shared.... it's dependent on your next action (cancel? save? open? etc)... that's what's confusing and not intuitive (and why a better "share" is suggested). =)

What do you mean by this? Like the URL doesn't change or that it's not accessible still to others? What you're saying seems to contradict the way Snap<i>!</i> is _supposed to_ work. Perhaps there may be a bug if things aren't working correctly. 

Here's what I see happening:
* Open an empty Snap<i>!</i> window and am logged in
* Open the Open Dialog
* Find an unshared project (not bolded)
* Click Share
* Project is bloded
* Snap<i>!</i> says "Sharing..."
* Snap<i>!</i> says "Shared"
* I click cancel
-- Now, this project is publicly accessible even though the URL doesn't change because it's not the currently open project, but it _is_ shared.
* Click "Open..." again
* Open the recently-shared project (It's still bolded, and the button says "Unshare" when it's selected)
* Click the Open button
* The URL now shows the public URL

I don't disagree that the current process is messy and confusing, but there is currently a use for the sharing function to be on non-opened projects. (Personally, I wouldn't mind seeing that change, but others might.)

> I like #714 ! I should probably have commented this suggestion there... sorry.

This is totally fine too! Multiple issues can help make it clear when more than one person is having trouble.

As an aside, I'm tagging #649 because having buttons in a disabled state also clears things up.

**Comment by davelai** [comment]
Hmm, I can't reproduce what I was saying either. I'm honestly puzzled. Your steps work for me now.  Call me crazy, but this wasn't the behavior given those same steps earlier today. Perhaps there is a scalability/load issue during the high school day to explain my craziness? Snap seems to work more smoothly after hours for me... =)   If this happens again, I'll try to reproduce it while recording the screen or something. Thanks for looking into this--possibly just user error on my behalf too!

**Comment by brianharvey** [comment]
@cycomachead : I don't know; how would I do that?

**Comment by cycomachead** [comment]
> @cycomachead : I don't know; how would I do that?

@brianharvey I'd need to be added as a collaborator in the repo settings.

**Comment by brianharvey** [comment]
Oh.  I'll take it up with Jens when he gets back from vacation.
