### ISSUE TITLE
Sound Importing - Especially Long Sounds

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap--Build-Your-Own-Blocks#987]
In NYC, students are having trouble uploading sounds (especially one that is 10 min long).

If there is a limit, can larger files be blocked from upload with an explanation to the user?

**Comment by jmoenig** [comment]
the is no limit, but it's not a great idea to upload massive media in limited bandwidth situations. You know, especially when a whole class uploads a lot of media more or less at the same time, bandwidth will go down. There is no way for Snap to find this out, however. I have projects with over 50 MB's of media and they work just fine (although for other reasons that might not be such a good idea ^^)

**Comment by maryfries** [comment]
Ok, I'll add something about that to the TG too...

**Comment by cycomachead** [comment]
@jmoenig We do need to handle something. In the past year I've seen an increasingly large number of student / teacher errors resulting from lots of media. The primary thing seems to be Snap! cloud (or snap or something weird) reporting "time out" errors when trying to load large (>=30MB in the cases I've seen) projects from the cloud.

**Comment by jmoenig** [comment]
@cycomachead what do you suggest? Inventing arbitrary quotas won't help, because ... they're arbitrary, based on unreliable heuristics.

Here's a project my kids made a few years ago that is basically a stop-motion animation with a ton of pictures, 33 MB's in total. I've just now saved it to the cloud - no problem at all, and I could share and open it on another computer - also no problem at all, neither on Chrome nor any other browser. And bear in mind that accessing the Snap cloud is actually noticeably slower from over here (Germany) than from the US:

http://snap.berkeley.edu/snapsource/snap.html#present:Username=jens&ProjectName=Jurassic

Can you open this project? I mean, yeah, it takes a few minutes both to save and to download, but that's to be expected, right? An it totally works.

**Comment by cycomachead** [comment]
I can open it. The problem is usually that things are internittent. By using another web server or `curl` I'm almost always able to open the same projects, but for some reason the XHR aspect seems to be causing problems. I have to admit I had no real idea why, and intermittent computer things just make me sad because computers are supposed to be consistent, darn it! I don't really know much about the Snap<i>!</i> Cloud, so I can't really offer many thoughts there.

**Comment by cycomachead** [comment]
I also have a 35mb audio file project which often opens fine for me, but not always. It seems to have no bearing on my internet connection, FWIW. I've had successes and errors on both stable (hard wired) and unstable (campus wifi) connections.
