### ISSUE TITLE
Long Scripts hit internal Canvas size limit (rendering oddities.)

### ISSUE THREAD

**Issue by cycomachead** [jmoenig/Snap--Build-Your-Own-Blocks#997]
See Sprite (15) in this student project. It appears like things work correctly, but the background isn't being drawn. 

http://snap.berkeley.edu/snapsource/snap.html#present:Username=cycomachead&ProjectName=buggy-student-MT

**Comment by cycomachead** [comment]
I have this weird hunch something could be realted to #20 but I have no idea for sure.

**Comment by jmoenig** [comment]
Interesting! Looks like a memory issue to me, maybe the GPU runs out of texture memory to create the huge bitmap that would be the scripting area. In fact, the scripting area wasn't created at all...

**Comment by cycomachead** [comment]
Yeah, it seems like a browser issue, since pretty much everything else works correctly.

Also, try opening this project in Safari...I get browser / process crash reports on the whole project, which is a bit odd.

**Comment by jmoenig** [comment]
Yes. I've got a whole list of browser issues that have been increasing lately without any changes on Snap's side. Safari has gotten very unstable and often simply crashes. I've already reported this to Apple. What's worse, Safari does the same in iOS, simply crashing and reloading the page. Turns out it's even way worse if Safari is opened locally (not via a webserver). This is a bummer, because it affects Brandon's iOS app.

Ach, browsers!

**Comment by cycomachead** [comment]
Yeah, also in flat design mode the background is off-write. It seems like some rendering thing. I might try to investigate but I don't know if I'll get far.

**Comment by cycomachead** [comment]
OK! Got something interesting! I removed the last two scripts and the background automatically returns! There is indeed some hidden threshold, but I have't measured it yet.

**Comment by cycomachead** [comment]
Ahhhh, it appears that right around 32,800 is a problem. Which I guess means, it's very like 32,768px is the max height.

**Comment by cycomachead** [comment]
The one thing I did realize is that when the limit is hit, there is no context menu or anything, so perhaps a Snap<i>!</i> imposed limit would be good.

**Comment by jmoenig** [comment]
Yeah, I wonder why that is the case, though. Inspecting the morph reveals that the bounds are, in fact, set correctly. I'm assuming that the only thing that fails is the transparency detection, because that requires access to image data. If that's true then simply changing the ScriptMorph's "noticesTransparentClick" property to "true" should solve it (which might be a good idea anyway).

(... trying this right now...)

Yes!! Morphic is awesome :-D

So, switching to dev mode, right clicking on a block so you get the hierarchy menu you can inspect the ScriptsMorphs and simply change its "noticesTransparentClick" setting to "true", and then save it. Now you can switch back to user mode and you get the context menu again. Maybe it's a good idea to change it, as it's an optimization anyway...

**Comment by cycomachead** [comment]
Oh, nice! That sounds like a good fix. That way, if you rearrange scripts you can still easily "clean up" and shrink the extra space. :)

**Comment by cycomachead** [comment]
Closing this because the main error is handle-able. :)

However, I have noticed that things like "script pic.." on scripts this big will report a blank image with no warnings... (this is also the case for the "all scripts pic" function). I don't know what should be done about those? We can't (easily) fix anything, but we could issue a warning.
